### ISSUE TITLE
Black Polygons on Intel iGPU

### ISSUE THREAD

**Issue by poudink** [Vita3K/Vita3K#1012]
I recently started having issues with polygons getting rendered solid black on my laptop with integrated graphics. I found that the issue affected Run Sackboy Run and Persona 4 Golden, though I didn't really test any other games. https://github.com/Vita3K/Vita3K/pull/1006 fixed the issues with Persona 4 Golden, but Run Sackboy Run remains broken.

**Comment by sunho** [comment]
Run sackboy run glitch is from other factor. IIRC it was related to background depth or stencil.

**Comment by poudink** [comment]
Well it's still Intel-exclusive, isn't it?
