### ISSUE TITLE
cmake: generate project erreur

### ISSUE THREAD

**Issue by Zangetsu38** [Vita3K/Vita3K#1037]
Last cmake version working with it is 3.17.5 
After update cmake on last version (3.19), i get error on generate project

![image](https://user-images.githubusercontent.com/5261759/100169711-63eee380-2ec4-11eb-893e-bd6066464b23.png)

# Issue:
Information by @1whatleytay 
>so as for ext-boost
b2 seems to prefix library names with lib for windows
and as of 3.19 cmake will absolutely not pick up on this
you may have to delete the prefixed lib in ext-boost for the following libraries
![image](https://cdn.discordapp.com/attachments/408917186254733317/780989811632111656/fgdfaswdasd.PNG)
since we copy them we can probably rename them in the batch script
this is a workaround for now though, the root of the problem is probably somewhere in our configuration or is a boost/cmake bug

**Comment by scribam** [comment]
I am using these CMake options `-DBOOST_ROOT=C:\local\boost_1_75_0 -DCI=ON` locally with the prebuilt windows binaries installed (https://www.boost.org/users/download/), it works fine.

**Comment by Zangetsu38** [comment]
yes but here issue is only for build by gen-window

**Comment by FrostMonarch95** [comment]
Anyone solve this problem?

**Comment by FrostMonarch95** [comment]
as mentioned by https://github.com/Vita3K/Vita3K/issues/672#issuecomment-651409123
git clean -dfx -f
git submodule update --init --recursive

**Comment by Zangetsu38** [comment]
No it totaly diferent and i no remember have close it

**Comment by Zangetsu38** [comment]
Oki i forget bookmist have fixed it
