### ISSUE TITLE
Analog and L/R button no works on A Rose in the Twilight and Yomawari game

### ISSUE THREAD

**Issue by Zangetsu38** [Vita3K/Vita3K#1055]
# Issue: 
- [x] Analog no respond, only digital button works, fixed by @scribam on pr #1069                                  
- [x] L/R buttons no works, fixed by @scribam on pr #1069 

# Screenshots:
- Ingame with Analog no works
![image](https://user-images.githubusercontent.com/5261759/102786326-9bf02600-439f-11eb-8da4-b215bed23c60.png)

- Manual controller screen
![image](https://user-images.githubusercontent.com/5261759/102787033-becf0a00-43a0-11eb-8ada-9bc8ddc10e80.png)

# Log
[vita3k.log](https://github.com/Vita3K/Vita3K/files/5724750/vita3k.log)

**Comment by Zangetsu38** [comment]
other Info
this game with same dev have also analog issue
image](https://user-images.githubusercontent.com/5261759/103192183-0d683100-48d8-11eb-8446-6c2d090157d0.png)

**Comment by Zangetsu38** [comment]
@scribam you can check this issue please, if ou are familiar with input code
both game with same devloper have exactly same issue with analog no worrrrks, and is Playable for first eept thii

**Comment by Zangetsu38** [comment]
@scribam i see juste here after some time play with your pr, but have also issue for L and R no works, This yomawari screen bellow and a rose have same issue

**Comment by Zangetsu38** [comment]
fixed no on last PR #1069

**Comment by poudink** [comment]
Wait, the PR isn't merged yet. I think it's too early to close this.

**Comment by Zangetsu38** [comment]
oi know, but is approved and good, so is merged soon
