### ISSUE TITLE
Touch screen/Button no respond for few game

### ISSUE THREAD

**Issue by Zangetsu38** [Vita3K/Vita3K#1072]
# About
- some game have issue with touchscreen or boutton no respond, like if game waitin g other things, net dialog or any things

# Issue: 
- On Invizimals The Resistance, nothing respond
![image](https://user-images.githubusercontent.com/5261759/141607063-c9262e14-936f-479e-9f10-216a399f0f8f.png)
- nothing respond here too
![image](https://user-images.githubusercontent.com/5261759/141607086-efbcc019-c56d-4dd4-9580-f75d494a6d79.png)
- same here
![image](https://user-images.githubusercontent.com/5261759/141607090-8c9bcb71-aa5b-47a7-911d-026929e07901.png)
- on it too
![image](https://user-images.githubusercontent.com/5261759/103331135-ca879400-4a64-11eb-81f2-5fc4c0f1d8fd.png)

# Log
- Sackboy
[vita3k.log](https://github.com/Vita3K/Vita3K/files/7531451/vita3k.log)

- Little deviant
[vita3k.log](https://github.com/Vita3K/Vita3K/files/7531461/vita3k.log)

- Table Top Racing
[vita3k.log](https://github.com/Vita3K/Vita3K/files/7531462/vita3k.log)

**Comment by pent0** [comment]
Retest human

**Comment by Zangetsu38** [comment]
You thinks i have already tested some time lol have Nevers get fixed, like table racing

**Comment by pent0** [comment]
Okay human :(

**Comment by hobyst** [comment]
[Invizimals The Resistance](https://github.com/Vita3K/compatibility/issues/498) also shows this issue. A language selection menu appears but the game doesn't react to any kind of touch event from the emulator.

**Comment by Zangetsu38** [comment]
> [Invizimals The Resistance](https://github.com/Vita3K/compatibility/issues/498) also shows this issue. A language selection menu appears but the game doesn't react to any kind of touch event from the emulator.

Yes i have notices too
