### ISSUE TITLE
Front end

### ISSUE THREAD

**Issue by petmac** [Vita3K/Vita3K#110]
I think the developers have mostly settled on Qt as our UI framework of choice.

**Comment by VelocityRa** [comment]
What about an immediate mode GUI like [dear imgui](https://github.com/ocornut/imgui)?
Obviously not native, but it's much lighter, much easier to deal with and can achieve almost everything we want at the moment.

It can do some pretty [crazy](https://cloud.githubusercontent.com/assets/8225057/20628927/33e14cac-b329-11e6-80f6-9524e93b048a.png) stuff with very little code/effort.

**Comment by Rinnegatamante** [comment]
I was going to suggest this too, there are several cool GUI like these. 
Might be worth a look.

**Comment by VelocityRa** [comment]
Decaf uses it btw, has a neat debugger too. Here's an old version:
![image](https://user-images.githubusercontent.com/6632271/38058319-16778044-32eb-11e8-83d3-b639c824bd07.png)

**Comment by petmac** [comment]
I'd be on board with it. For some reason I thought you favoured Qt.

**Comment by VelocityRa** [comment]
We've had imgui for a while now, closing this.
