### ISSUE TITLE
Add NONPDRM support!

### ISSUE THREAD

**Issue by AyderProgramic** [Vita3K/Vita3K#1219]
If this is not possible to implement, then close my question!

**Comment by IllusionMan1212** [comment]
nonpdrm dumps are already supported. check https://vita3k.org/quickstart.html to learn how to correctly dump your games using it.

**Comment by AyderProgramic** [comment]
My game of this format gives an error, it does not show the game icon at all!!

**Comment by Zangetsu38** [comment]
Is because you have manualy extract zip inside app, you need using install this zip with using file/install zip vpk
