### ISSUE TITLE
Add an option to exclude GUI from build for better portability

### ISSUE THREAD

**Issue by makemefeelgr8** [Vita3K/Vita3K#1224]
Hi all, I've been trying to build Vita3k for Android. After some tinkering, it compiled just fine, but then it got to libraries and it was like:

```
ld: error: unable to find library -lgtk-3
ld: error: unable to find library -lgdk-3
ld: error: unable to find library -lpangocairo-1.0
ld: error: unable to find library -lpango-1.0
ld: error: unable to find library -lharfbuzz
ld: error: unable to find library -latk-1.0
ld: error: unable to find library -lcairo-gobject
ld: error: unable to find library -lcairo
ld: error: unable to find library -lgdk_pixbuf-2.0
ld: error: unable to find library -lgio-2.0
ld: error: unable to find library -lgobject-2.0
ld: error: unable to find library -lglib-2.0
```
Basically, it says there is no GTK (and GTK dependencies). It might be tricky to get it working like this.

So, is there a way to skip generation of GUI and build a command line executable with less dependencies? Ideally, resulting app would just launch a game in a new window without menus/options/GTK.

**Comment by Zangetsu38** [comment]
android wut ? for why ? lol

**Comment by makemefeelgr8** [comment]
Why not? It would be really convenient to game on the go.

**Comment by Zangetsu38** [comment]
Because is very too early lol

**Comment by sunho** [comment]
You can actually do it by rewriting interface.cpp even now. But, to make this practically compatible with android, it requires tons of additional efforts. We're slowly preparing things to support android eventually.
