### ISSUE TITLE
Games with non-standard TITLE_ID don't work

### ISSUE THREAD

**Issue by hobyst** [Vita3K/Vita3K#1226]
# Description
Games with `TITLE_ID` longer than 9 characters make Vita3K crash due to a memory allocation error, and render the emulator unusable until the user uses `Vita3K -d {TITLE_ID}` to delete the game. 
- After game installation, a notification appears on the emulator confirming the successful installation of the game, and it even shows the game icon properly, indicative of a successful decryption. However, it doesn't get displayed as a new item on the installed games list.
- Error message gotten after installing the game and re-opening the emulator (release build):
  ```log
  spdlog error: std::bad_alloc
  terminate called after throwing an instance of 'std::length_error'
    what():  basic_string::_M_create
  ```
- Error message gotten in a debug build:
  ```log
  spdlog error: std::bad_alloc
  Vita3K: ../vita3k/util/src/util.cpp:56: auto logging::init(const Root &, bool)::(anonymous class)::operator()(const std::string &) const: Assertion `0' failed.
  ```
- Error gotten after running `Vita3K -r {TITLE_ID}`
  ```log
  Segment violation ('core' generated)
  ```
The game this error was found with is the PlayStation Vita included game Welcome Park, which although on the file system structure gets referenced as `NPXS10007`, it's true `TITLE_ID` as specified on several files inside the game package structure (such as `param.sfo`, among others) is `IV0001-NPXS10007_00-WELCOMEPARK01234`. It has been dumped using NoNpDrm by copying the contents at `pd0:` into `ux0:` and running the game as normal, then NoNpDrm detects the game and generates a `.rif` file. The rest of the process is the same as with any other game.

The error might also be UI-related, as if the user has a large list of games installed on the emulator, the error and its following crash will only happen if the user scrolls down enough for the emulator to have to display the game on the list.

# Testing setup
- OS: Ubuntu 20.4.2 LTS
- CPU: Intel Core i7-6700HQ
- GPU: NVIDIA GeForce GTX 960M

**Comment by pent0** [comment]
The emulator generally assumes ID to be 8 length. Probably easy to fix I hope

**Comment by Zangetsu38** [comment]
ise have found why that crash, all is fine, is just hmm complicated lol system app like welckom back is actually no compatible for works inside ux0
