### ISSUE TITLE
"Please note that the purpose of this project is not to enable illegal activity"

### ISSUE THREAD

**Issue by AlexN64gamer** [Vita3K/Vita3K#1232]
... what illegal activity? even Sony abandoned the console is closing the online store in a few days, the purpose SHOULD be the preservation of physical and digital media that wouldnt be accesible in ANY other way than emulation, understand that developers, please, emulation is preservation, im not doing anything ILLEGAL when the same company that is the owner of the rights closes everything and is not allowing me to download any game anymore, most people is nor rich and cant afford the full Ps Vita library in the years it was supported.

**Comment by pent0** [comment]
We are just keeping ourself safe from legal issues, complaining here no help. Go elsewhere

**Comment by AyderProgramic** [comment]
Emulator piracy is possible, but only in Maidump!
