### ISSUE TITLE
About loading a custom skprx

### ISSUE THREAD

**Issue by TheSnowfield** [Vita3K/Vita3K#1275]
Can Vita3K load a custom skprx compiled with HENKaku?
I'm debugging a game via Vita3K. 
There's the skprx I needed. [kubridge](https://github.com/TheOfficialFloW/kubridge)   

Thanks for your help!

**Comment by Zangetsu38** [comment]
is techncaly possible yes, load module with game

**Comment by Zangetsu38** [comment]
> 
> 
> > is techncaly possible yes, load module with game
> 
> That's means I must load the skprx manually in the main thread like loading a suprx?

emu load some module on boot app like pvf/ft2 and pre-loaded module but no idea if can works for you module

**Comment by TheSnowfield** [comment]
> > > is techncaly possible yes, load module with game
> > 
> > 
> > That's means I must load the skprx manually in the main thread like loading a suprx?
> 
> emu load some module on boot app like pvf/ft2 and pre-loaded module but no idea if can works for you module

Okay, I will try that. Thanks!

**Comment by sunho** [comment]
You can absolutely load modules by SceKernel function or stubs. But, we can't load encrypted modules. You might want to decrypt it first.

**Comment by sunho** [comment]
Keep in mind that kernel modules usually don't work. Because we usually emulate the user land.

**Comment by TheSnowfield** [comment]
> e.g. We emulate libkernel module instead of actual kernel functions. So something like ksceKernelStrncpyUserToKernel will not work.

You are right. It's actually not working.
I have tested the skprx. 
The log prints several warnings about the module called the unimplemented function.

```
[13:26:15.895] |W| [unimplemented_impl]: Unimplemented ksceKernelStrncpyUserToKernel import called.
[13:26:15.895] |W| [unimplemented_impl]: Unimplemented ksceKernelMemcpyUserToKernel import called.
[13:26:15.895] |W| [unimplemented_impl]: Unimplemented ksceKernelAllocMemBlock import called.
[13:26:15.896] |W| [unimplemented_impl]: Unimplemented ksceKernelCreateUserUid import called.
```

**Comment by sunho** [comment]
Right, you can alloc or strcpy using userland api but I'm quite sure that's not what you want. If you tell me what's you're trying to do more specifically, I can help out further.

**Comment by TheSnowfield** [comment]
> Right, you can alloc or strcpy using userland api but I'm quite sure that's not what you want. If you tell me what's you're trying to do more specifically, I can help out further.

I'm trying to load an ELF file into memory manually in userspace.
I'm sure the virtual address in the program segment must be mapping to memory like using the mmap2 function.
Cause there is no API called `VirtualProtectEx` in VitaSDK like win32 to change a block of memory permission,
So I guess I have to allocate the linear memory in the kernel space use kubridge.

**Comment by sunho** [comment]
In vita3k, you can just do it by copying memory to anywhere; we don't check permission at all. There's going to be some hassle with import stubs and relocation, but it's not impossible. (and you'd have to deal with this even on physical hw anyways...)

**Comment by TheSnowfield** [comment]
> In vita3k, you can just do it by copying memory to anywhere; we don't check permission at all. There's going to be some hassle with import stubs and relocation, but it's not impossible. (and you'd have to deal with this even on physical hw anyways...)

I got it. Thanks!
