### ISSUE TITLE
Some boost problem

### ISSUE THREAD

**Issue by ericfernandesferreira** [Vita3K/Vita3K#1306]
Hello everyone, until about 3 months ago i was able to compile vita3k without problems in my Slackware, but recently i have not been able to do it anymore due to a problem in the boost.

I will put the exit here if you can help me please. 

mkdir -p build
cd build
  cmake \
    -DCMAKE_C_FLAGS:STRING="$SLKCFLAGS" \
    -DCMAKE_CXX_FLAGS:STRING="$SLKCFLAGS" \
    -DCMAKE_INSTALL_PREFIX=/usr \
    -DUSE_VULKAN=ON \
    -DCMAKE_BUILD_TYPE=Release ..
  make -j9

The error:

-- Check if compiler accepts -pthread
-- Check if compiler accepts -pthread - yes
CMake Deprecation Warning at external/SPIRV-Cross/CMakeLists.txt:15 (cmake_minimum_required):
  Compatibility with CMake < 2.8.12 will be removed from a future version of
  CMake.

  Update the VERSION argument <min> value or use a ...<max> suffix to tell
  CMake that the project does not need compatibility with older versions.

-- SPIRV-Cross: Finding Git version for SPIRV-Cross.
-- Found Git: /usr/bin/git (found version "2.31.1") 
-- SPIRV-Cross: Git hash: 3c43f055
-- Found Vulkan: /usr/lib64/libvulkan.so  
CMake Error at /usr/lib64/cmake/Boost-1.76.0/BoostConfig.cmake:141 (find_package):
  Found package configuration file:

    /usr/lib64/cmake/boost_system-1.76.0/boost_system-config.cmake

  but it set boost_system_FOUND to FALSE so package "boost_system" is
  considered to be NOT FOUND.  Reason given by package:

  No suitable build variant has been found.

  The following variants have been tried and rejected:

  * libboost_system.so.1.76.0 (shared, Boost_USE_STATIC_LIBS=ON)

Call Stack (most recent call first):
  /usr/lib64/cmake/Boost-1.76.0/BoostConfig.cmake:258 (boost_find_component)
  /usr/share/cmake-3.20/Modules/FindBoost.cmake:594 (find_package)
  external/psvpfstools/CMakeLists.txt:8 (FIND_PACKAGE)

**Comment by hobyst** [comment]
The build system of Vita3K is configured to compile and use [a custom fork of Boost](https://github.com/Vita3K/ext-boost), and because of that you don't directly run CMake but run `./gen-linux.sh` to get it properly set up. Just running CMake on the root of the repository isn't enough to set up your compilation environment and you need to first run `./gen-linux.sh` to compile Boost and generate the Makefiles and then use `cmake --build build-linux` to compile Vita3K.
