### ISSUE TITLE
Black screen on title PCSG00275 (Yakuza Ishin companion for vita) and PCSG00503 (Yakuza 0 companion for vita)

### ISSUE THREAD

**Issue by OnoMichio** [Vita3K/Vita3K#1339]
console shows that for PCSG00275, it attempts to seek but it gets stuck, freezing the game 
![image](https://user-images.githubusercontent.com/32009437/118851693-f13a5000-b8c9-11eb-8e07-61fc31fe2645.png)

**Comment by Zangetsu38** [comment]
invalide issue, using all time last build for check

![image](https://user-images.githubusercontent.com/5261759/118851972-9ce79e00-b8d2-11eb-94c6-a51a69dfeeba.png)

**Comment by sunho** [comment]
Use dynarmic maybe

**Comment by Zangetsu38** [comment]
unicorn show obligatory firt logo is corner side, but yes, need dyrnamic for after

**Comment by OnoMichio** [comment]
weird, for me it just black screens

**Comment by pent0** [comment]
You can use PKG version for store + enable Dynarmic in configurations

**Comment by OnoMichio** [comment]
solved that, thanks
