### ISSUE TITLE
Fix make install

### ISSUE THREAD

**Issue by aimileus** [Vita3K/Vita3K#14]
Currently, `make install` doesn't install the Vita3K binary. It does a couple of libraries and headers, which may conflict with the ones provided by the system package manager. For example, `capstone.h` is also provided by the `capstone` package and shouldn't be installed by Vita3K.

**Comment by TingPing** [comment]
So here is a patch but I'm not sure how the `shaders` are used at runtime as the path probably needs to be defined at build time for it to load.

```diff
From d01dc157961fc8fe7cc184290be7b669c212f8f6 Mon Sep 17 00:00:00 2001
From: Patrick Griffis <tingping@tingping.se>
Date: Mon, 29 Jan 2018 13:40:06 -0500
Subject: [PATCH] Install executable on Unix

---
 src/emulator/CMakeLists.txt | 14 +++++++++++---
 1 file changed, 11 insertions(+), 3 deletions(-)

diff --git a/src/emulator/CMakeLists.txt b/src/emulator/CMakeLists.txt
index 6f22f95..e28b64d 100644
--- a/src/emulator/CMakeLists.txt
+++ b/src/emulator/CMakeLists.txt
@@ -48,9 +48,11 @@ vpk.h
 )
 
 target_link_libraries(emulator PRIVATE cpu elfio host modules nids vita-toolchain)
-set_target_properties(emulator PROPERTIES
-	OUTPUT_NAME Vita3K
-	RESOURCE shaders)
+set_target_properties(emulator PROPERTIES OUTPUT_NAME Vita3K)
+
+if(NOT UNIX)
+	set_target_properties(emulator PROPERTIES RESOURCE shaders)
+endif()
 
 if(WIN32)
 	add_custom_command(
@@ -62,3 +64,9 @@ if(WIN32)
 		COMMAND ${CMAKE_COMMAND} -E copy_if_different "${PROJECT_SOURCE_DIR}/external/unicorn/windows/libgcc_s_seh-1.dll" "$<TARGET_FILE_DIR:emulator>"
 		COMMAND ${CMAKE_COMMAND} -E copy_if_different "${PROJECT_SOURCE_DIR}/external/unicorn/windows/libwinpthread-1.dll" "$<TARGET_FILE_DIR:emulator>")
 endif()
+
+if(UNIX AND NOT APPLE)
+	include(GNUInstallDirs)
+	install(TARGETS emulator DESTINATION "${CMAKE_INSTALL_BINDIR}")
+	install(DIRECTORY shaders DESTINATION "${CMAKE_INSTALL_DATADIR}/Vita3K")
+endif()
-- 
2.14.3
```

**Comment by TingPing** [comment]
> For example, capstone.h is also provided by the capstone package and shouldn't be installed by Vita3K.

As far as I can tell there is no way to stop a subdirectory from installing things other than patching it.

**Comment by TingPing** [comment]
Ah nevermind I found the option for that, will submit PR.

**Comment by petmac** [comment]
This should be working correctly now.

**Comment by TingPing** [comment]
@petmac The issue of Vita3K not getting installed wasn't. As I mentioned above I just wasn't sure where `shaders` should be installed at runtime and suspect we would need to modify that look up path.

**Comment by VelocityRa** [comment]
@TingPing Vita3k assumes that the `shaders/` and `shaders-builtin/` are in the _same directory as the executable is_. See <https://github.com/Vita3K/Vita3K/blob/398b4afdbc3237d4e3741cd7e7370decea58b814/src/emulator/CMakeLists.txt#L99-L100> for details.

**Comment by VelocityRa** [comment]
Unfortunately none of the devs use linux for development, that's why the linux experience isn't up to par.

**Comment by Zangetsu38** [comment]
state of this ?

**Comment by pent0** [comment]
No feedback so far for such long time, if you have any more issues please open another issue.
