### ISSUE TITLE
Hope to provide Unity game support

### ISSUE THREAD

**Issue by Moqi01** [Vita3K/Vita3K#1404]
I'm a game developer and I want to use this simulator to test Unity games.
Hope to provide Unity game support.

**Comment by Moqi01** [comment]
![image](https://user-images.githubusercontent.com/27811532/121897955-67d43d00-cd12-11eb-8435-f1e1e70e5a2c.png)

**Comment by Zangetsu38** [comment]
Unity request libkernel and ver more stuff

**Comment by TheSnowfield** [comment]
#1024

**Comment by Zangetsu38** [comment]
oups forget, is done now
