### ISSUE TITLE
"Open Pref Path" menu option cannot access folders with spaces in the name

### ISSUE THREAD

**Issue by YvanDroid** [Vita3K/Vita3K#1423]
Changing the pref_path for the system storage to a folder that contains spaces in the path name causes the "Open Pref Path" menu option to become non-functional.
Stating "The system cannot find the file F:\Storage\Actual." 
The path for the new pref_path was  "F:\Storage\Actual Documents\Random Stuff That I Mess Around With\Vita3k\pref_path/"

This can be temporarily worked around by using a folder name that does not have spaces in it. Example: "F:\Vita3k"

**Comment by Zangetsu38** [comment]
Yes i know, i have see this issue also i have try to fix
