### ISSUE TITLE
Thophy details lang

### ISSUE THREAD

**Issue by Croden1999** [Vita3K/Vita3K#1434]
could add a translation of this 'Details' content? thx Vita3K team with developers.

![1](https://user-images.githubusercontent.com/61804715/128568171-eb487e24-5e96-498c-958e-5d3bba557d86.png)
![2](https://user-images.githubusercontent.com/61804715/128568191-6c9950ec-90d9-4236-b2cf-e5b51f62ca85.jpg)

**Comment by Zangetsu38** [comment]
OUPS :D ok i look

**Comment by Zangetsu38** [comment]
straange, translate is already here 🤔

**Comment by Croden1999** [comment]
> straange, translate is already here 🤔

yea, but it doesn't translate

**Comment by Zangetsu38** [comment]
no, i said, translate string is already inside file, just is strange

**Comment by Croden1999** [comment]
> no, i said, translate string is already inside file, just is strange

alright, thx a lot
