### ISSUE TITLE
Support 32-Bit for Vita3K

### ISSUE THREAD

**Issue by BenFourArms39023** [Vita3K/Vita3K#1446]
Hi! I want to know why I can't get to play Vita3K is because it's for 64-bit and I want to play it on a 32-bit laptop.

**Comment by Croden1999** [comment]
u should installed 64-bit system, and to play Vita3K emulator. maybe your issue is closed .

**Comment by BenFourArms39023** [comment]
?!?!?!?! I'M NOT OLD ENOUGH FOR A 32-BIT FREAKING PC OK?!

**Comment by pent0** [comment]
There will be no support for 32-bit machine, I hope you can upgrade to 64-bit machine soon.
