### ISSUE TITLE
Crash at system save loading (PCSG00489 - Legend of Heroes: Trails in the sky SC - Revolution)

### ISSUE THREAD

**Issue by ShadyDemoness** [Vita3K/Vita3K#1480]
[PCSG00489 - [英雄伝説 空の軌跡 SC Evolution]Dynarmic.log](https://github.com/Vita3K/Vita3K/files/7426952/PCSG00489.-.SC.Evolution.Dynarmic.log)
[PCSG00489 - [英雄伝説 空の軌跡 SC Evolution]Unicorn.log](https://github.com/Vita3K/Vita3K/files/7426953/PCSG00489.-.SC.Evolution.Unicorn.log)
I tried both CPU Backends here. Is this something that will be fixed or is the error on my side?

**Comment by GamingDucking** [comment]
i am pretty sure the game now goes ingame now.

**Comment by Zangetsu38** [comment]
yes  is fixed
