### ISSUE TITLE
[bug] Cannot open app on MacOS Monterey 12.0.1

### ISSUE THREAD

**Issue by kytosai** [Vita3K/Vita3K#1508]
OS: MacOS Montery 12.0.1
Macbook pro 16inch 2019 base option (intel i7, 16GB RAM, 512GB SSD, VGA: Radeon 5300M)

I downloaded macos app at: https://github.com/Vita3K/Vita3K/releases/tag/continous 

But when i run app the following error occurs with message "The Application "Vita3K.app" can't be opened"

![Screen-Shot-2021-11-23-at-13.58.36.jpg](https://s1.uphinh.org/2021/11/23/Screen-Shot-2021-11-23-at-13.58.36.jpg) 

---

After try with version "master-osx-v5010.zip" at: https://github.com/Vita3K/Vita3K/releases/tag/master-v5003 

But when i run the app there is no app window open

**Comment by Zangetsu38** [comment]
![image](https://user-images.githubusercontent.com/5261759/143005695-09c8d3fe-7a49-490b-ab6b-04bffe9b64e6.png)

**Comment by kytosai** [comment]
> ![image](https://user-images.githubusercontent.com/5261759/143005695-09c8d3fe-7a49-490b-ab6b-04bffe9b64e6.png)

Thanks you, i can start app !

But i cann't play Dynasty Warrriors 8 Extreme legend :( .. crash when i start game 

![Screen-Shot-2021-11-23-at-20.25.26.jpg](https://i.imgur.com/fRzvFUK.jpg)

**Comment by Zangetsu38** [comment]
for that, check compat, and ask on discord, but this game no works yet
