### ISSUE TITLE
a software that will make finding compatability problems 500x possibly more quick

### ISSUE THREAD

**Issue by exaltedkiller** [Vita3K/Vita3K#1589]
the name of the software is cheat engine
cheat engine lets you change the game speed from 2x to 500x more quick in the game
pretend the game is 12 hours long
pretend you change the speed to 30x 
you will be able to complete the game in 24 minutes
hack your health with cheat engine to try to dont die in the game
change the game speed movee in the game till you find a compatablity problem
save the game and exit cheat engine and exit the game so all the original game software structure goes back to its original state
 start the game again to the saved game now you at the compatablity problem with original software structure

you work 8 hours a day(pretend every game is 12 hours long) you will be able to complete 20 games a day
you will be able to complete 600 games in 30 days, in 2 mounths 1200 games will be completed

you emulator creator tell me if you will try this or anybody that knows how to fix game compatablity problems

download link for cheat engine
https://cheat-engine.en.uptodown.com/windows

**Comment by Croden1999** [comment]
it is invaild.
