### ISSUE TITLE
About install pkg / zip (nonpdrm games) issue

### ISSUE THREAD

**Issue by Croden1999** [Vita3K/Vita3K#1597]
When [EMPTY] is displayed during PKG installation or ZIP decryption, the installation is blocked. Request to Vita3K Team and devlopment fix the issue. Thx a lot.

**Comment by Zangetsu38** [comment]
> When [EMPTY] is displayed during PKG installation or ZIP decryption, the installation is blocked. Request to Vita3K Team and devlopment fix the issue. Thx a lot.

Vancouver share screen ? I no remember this 🤷‍♂️

**Comment by Croden1999** [comment]
sorry, Mr. Zangetsu. my computer is block when i update bios. but i can say the games id, such as PCSG00899 and PCSH00142.

**Comment by Croden1999** [comment]
thx Mr. @Zangetsu38. it is fix on [#1598](https://github.com/Vita3K/Vita3K/pull/1598)

**Comment by Zangetsu38** [comment]
Ah ? 🤔 ok lol

**Comment by Croden1999** [comment]
alright, the EMPTY still exists.

**Comment by Croden1999** [comment]
> 好吧，EMPTY 仍然存在。

![-5af85a86a6fefa50](https://user-images.githubusercontent.com/61804715/166618339-e19ff8eb-69a9-4a6d-b583-dbf21f7ab884.png)

**Comment by Zangetsu38** [comment]
where is problem ? empty can be normal, ignore it

**Comment by Croden1999** [comment]
If show the [EMPTY], the installation process will get stuck.

**Comment by Croden1999** [comment]
> where is problem ? empty can be normal, ignore it

If show the [EMPTY], the installation process will get stuck, Mr. Zangetsu.

**Comment by Zangetsu38** [comment]
> > where is problem ? empty can be normal, ignore it
> 
> If show the [EMPTY], the installation process will get stuck, Mr. Zangetsu.

absolutely not, i have get empty like that very lot time, is normal, just ignore it, no hafve any probleme, install can take veyr lot time, need wait

**Comment by Croden1999** [comment]
> > > where is problem ? empty can be normal, ignore it
> > 
> > 
> > If show the [EMPTY], the installation process will get stuck, Mr. Zangetsu.
> 
> absolutely not, i have get empty like that very lot time, is normal, just ignore it, no have any probleme, install can take veyy lot time, need wait

i got it, thx Mr. Zangetsu again.

**Comment by pka4916** [comment]
![image](https://github.com/Vita3K/Vita3K/assets/34923634/4b084246-a21c-44a3-800f-328fbb2a9054)
