### ISSUE TITLE
Doom Wads not showing

### ISSUE THREAD

**Issue by cybertronicgames** [Vita3K/Vita3K#16]
How do I run home-brews?
![screenshot 139](https://user-images.githubusercontent.com/14711758/35543957-81b7a4a6-052d-11e8-90c6-42f6e637eee4.jpg)
![screenshot 140](https://user-images.githubusercontent.com/14711758/35543960-8456e168-052d-11e8-9f5a-c40ebffffebe.jpg)

**Comment by petmac** [comment]
Apologies. SceIo functions for scanning directories are not yet implemented. I will get to them though.

**Comment by cybertronicgames** [comment]
@petmac Thanks for the reply! I great hope for this emu.

**Comment by Ghabry** [comment]
I started working on a very basic implementation of stat and dir-stuff to get EasyRPG Player working. Guess will also work for Dome. Will do a PR when I have the WinApi-part finished.

**Comment by cybertronicgames** [comment]
@Ghabry Awesome!
