### ISSUE TITLE
Taiko no Tatsujin freeze after booting

### ISSUE THREAD

**Issue by I-LoveCpp** [Vita3K/Vita3K#1600]
My hardware : 
CPU : 11th Gen intel 15-1135G7 
GPU : intel Iris Xe
RAM : 8GB
[PCSG00551]Taiko Drum Master : V Version  freeze after booting
My log : [vita3k.log](https://github.com/Vita3K/Vita3K/files/8024535/vita3k.log)
I would appreciate it if u could fix the issue.

**Comment by benderscruffy** [comment]
please close as this should be on the compatibility github
