### ISSUE TITLE
Re:Zero - kara Hajimeru Isekai Seikatsu - Death or Kiss Nonpdrm [PCSG00933] Boots but no visuals.

### ISSUE THREAD

**Issue by FidencioYzaguirreIII** [Vita3K/Vita3K#1601]
The game boots but am left with a black screen. The intro plays and the game is receptive to buttons. I can tell from audio that I can navigate the menus. Only problem is that I can't see the game.

Links for info on game.
https://rezero.fandom.com/wiki/Re:Zero_-DEATH_OR_KISS-
https://vndb.org/v19890/chars

**Comment by Zangetsu38** [comment]
no open issue for that, is already know issue, if you want update, looking compatbility here, and create issue when game no already exist, with follow instruction
https://github.com/Vita3K/compatibility/issues

**Comment by pka4916** [comment]
![image](https://github.com/Vita3K/Vita3K/assets/34923634/0e8a8be1-247c-446a-b61a-45b319541bb5)
