### ISSUE TITLE
遇到的一些模拟器问题

### ISSUE THREAD

**Issue by cblhjy** [Vita3K/Vita3K#1612]
在玩春物遇到沉默模式无法继续下去，画面会卡住
![05T SRBX{WQ@HVR{HSYQ66L](https://user-images.githubusercontent.com/99587908/154795711-a056751c-da0e-478c-b4e7-c28942f62558.png)
。

**Comment by Zangetsu38** [comment]
for issue of game, using compatbility github, search if game already exist, and open issue and follow instruction, and in english only please
https://github.com/Vita3K/compatibility/issues
