### ISSUE TITLE
Legend of Heroes: Trails in the Sky 3rd Evolution - Blackscreen on startup.

### ISSUE THREAD

**Issue by ShadyDemoness** [Vita3K/Vita3K#1617]
Vita3K Version: v0.1.4 2423-f5073260
Config: Default (logs and cache are from default settings, but tried as many combinations as possible, still got only two different results: crash with Spir-V or no crash but black screen without it.)
CPU: AMD Ryzen 9 5900X 12-Core Processor
GPU: AMD RX 6700 XT

PS: Own a copy on my vanilla Vita
The game seems to load fine until a certain point but stops without error or anything: no crash, no nothing, just black screen. Enabling Spir-V causes a crash at every start of the game, while disabling it gives an eternal black screen.

Log File:
[vita3k.log](https://github.com/Vita3K/Vita3K/files/8117725/vita3k.log)

Shaderlog:
[Shaderlog - PCSH10082.zip](https://github.com/Vita3K/Vita3K/files/8117731/Shaderlog.-.PCSH10082.zip)

Shader Cache:
[Shader Cache - PCSH10082.zip](https://github.com/Vita3K/Vita3K/files/8117735/Shader.Cache.-.PCSH10082.zip)

I hope this helps.

**Comment by Zangetsu38** [comment]
no open new issue here, i said, report state on github of compatibility

**Comment by ShadyDemoness** [comment]
ah ok now i understand. Sorry  for the trouble

**Comment by Zangetsu38** [comment]
> ah ok now i understand. Sorry for the trouble

in first, check if game is already listed here
https://github.com/Vita3K/compatibility/issues
if not, open new issue and follow instruction

**Comment by ShadyDemoness** [comment]
Got it, wasn't listed so made a new one with the instruction
