### ISSUE TITLE
macOS version not opening

### ISSUE THREAD

**Issue by AM7999** [Vita3K/Vita3K#1620]
The macOS version of Vita3k is not opening yes i did allow it to run in System Preferences.
After looking in Vita3K/Contents/MacOS, the binary opens with TextEdit

<img width="750" alt="Screen Shot 2022-02-23 at 3 54 41 PM" src="https://user-images.githubusercontent.com/62681612/155430794-57970939-a9b0-4597-a1c4-b1fbbde7541d.png">

<img width="260" alt="Screen Shot 2022-02-23 at 3 55 09 PM" src="https://user-images.githubusercontent.com/62681612/155430818-6bc403d9-1ae0-431f-80aa-d9b3fdaac217.png">

**Comment by Croden1999** [comment]
u can see the issue. [#1508](https://github.com/Vita3K/Vita3K/issues/1508)
