### ISSUE TITLE
Any chance for macOS 10.14.6 support?

### ISSUE THREAD

**Issue by eisnerguy1** [Vita3K/Vita3K#1643]
I unfortunately can't upgrade my laptop beyond macOS 10.14.6 right now. Is there any chance the macOS requirements when building the app could be lowered? I've tried compiling it myself but I constantly get errors at this stage:

```
Failed to clone 'external/soundtouch'. Retry scheduled
Cloning into '/Users/eisnerguy1/Downloads/_Chrome/Vita3K/external/soundtouch'...
fatal: unable to access 'https://codeberg.org/soundtouch/soundtouch.git/': SSL certificate problem: certificate has expired
fatal: clone of 'https://codeberg.org/soundtouch/soundtouch.git' into submodule path '/Users/eisnerguy1/Downloads/_Chrome/Vita3K/external/soundtouch' 
```

Any help would be greatly appreciated. Thanks! :)

**Comment by Zangetsu38** [comment]
Your error no relate us, is problèmes in your side

**Comment by eisnerguy1** [comment]
Wait, my request for Vita3K to be compatible with macOS 10.14.6 has nothing to do with the project? That would be the simplest solution if it's possible.

**Comment by Zangetsu38** [comment]
No, your error is get by trying clone project, in try download sou touch, you have ssl error, no relate vita3k project att all

**Comment by merryhime** [comment]
@eisnerguy1 Your computer is unable to retrieve files from the git repository located at https://codeberg.org due to a certificate verification error on your end. We would recommend fixing your operating system's SSL certificate stores appropriately as you normally would.
