### ISSUE TITLE
--pkg command line does not respect pref-path

### ISSUE THREAD

**Issue by VibeNL** [Vita3K/Vita3K#1664]
Installing via de commandline seems to install to the default folder instead of the pref-path set.

Commandline used: Vita3K.exe --pkg "<path>"  -zrif "<string>"

If there is a parameter i'm missing, let me know

**Comment by garygan89** [comment]
Ditto I had the same problem too. Even tried to create ntfs junction for the `c:\Users\<USER>\AppData\Roaming\Vita3K\Vita3K\ux0` to point to my emulator path but no avail.

Installing game is fine but upon loading Vita3k emulator, the game didn't show up in the list. Had to resort to manual method now using GUI, but installing 2000+ titles is gonna take time and not systematic!

**Comment by garygan89** [comment]
@Macdu Thanks for the pull request, hope this will be merged to master and it will then build a release ;)

**Comment by VibeNL** [comment]
Fantastic, thanks 👍
