### ISSUE TITLE
Cannot open app on Mac (Intel)

### ISSUE THREAD

**Issue by LordAcid666** [Vita3K/Vita3K#1679]
App not start.
Using latest build on 21 april 2022

Checked also in privacy for blocked app, but nothing reported.
_______________________________________________________
iMac (Retina 5K, 27-inch, Late 2015)
MacOS Monterey 12.3.1 (21E258)
3,2 GHz Intel Core i5 quad-core
Ram 24 GB 1867 MHz DDR3
Graphic card: AMD Radeon R9 M390 2 GB

**Comment by CatGreen90** [comment]
I believe this is because the app itself is unsigned but includes a signed SDL2 framework. AFAIK the only way to fix this would be to sign the app or include only libSDL2-2.0.0.dylib.

**Comment by ArbestRi** [comment]
Please close this issue

**Comment by Macdu** [comment]
Closing for now, as Mac is no longer supported, might reopen if needed when Mac support is added back with the Vulkan build.
