### ISSUE TITLE
Issue with game

### ISSUE THREAD

**Issue by NinaNight** [Vita3K/Vita3K#1701]
Hello! :D 
It's just a small issue. I wanted to play the game Diabolik Lovers Vandead Carnival and everything worked fine till I started the game. The background would either be upside down or not spawning at all. That was okay, till I saw the characters and the speech boxes - which would either not despawn when clicking continue or would take atleast a whole minute, which led to not being able to see wich character was talking at the moment, because of the text boxes overlapping. 
Is there anything I can do to make the game work better or is there any solution in general? If not then I'm sorry for bothering.
Hope you're alright :D

**Comment by benderscruffy** [comment]
please close as this should be on the compatibility github

**Comment by scribam** [comment]
Diabolik Lovers: Vandead Carnival [PCSG00472] is playable: https://github.com/Vita3K/compatibility/issues/662
Open a new issue if something is not working correctly
