### ISSUE TITLE
Newest build of May 28 turns uncharted Golden Abyss to red-only color 

### ISSUE THREAD

**Issue by Brutal-sam** [Vita3K/Vita3K#1771]
texture issue? also when the coin in the loading screen became multiplied in the new releas
![jjy](https://user-images.githubusercontent.com/94696121/170842360-db95a222-b287-44d1-b599-2b1e2e17b6ab.JPG)
![jjjjjh](https://user-images.githubusercontent.com/94696121/170842370-38375d22-1dfb-4690-8e2e-ca30d6afeae5.JPG)
![iiiii](https://user-images.githubusercontent.com/94696121/170842374-f363d970-b236-4aba-a435-76464e393273.JPG)
e

**Comment by Zangetsu38** [comment]
no regression, render have only get improvement, but missing some part of code for fix multiple coin, for red color is not news, is random bug on it
