### ISSUE TITLE
CaveStory regression

### ISSUE THREAD

**Issue by IllusionMan1212** [Vita3K/Vita3K#178]
Cave story regressed.
I'm confident PR #172 regressed it, before the PR it used to just skip over sceKernelWaitThreadEnd, but after it just hangs on where it used to say "unimplemented sceKernelWaitThreadEnd" with the first two threads waiting forever.

Before the PR Log:
[vita3k.log](https://github.com/Vita3K/Vita3K/files/1948807/vita3k.log)

After the PR Log:
[vita3k.log](https://github.com/Vita3K/Vita3K/files/1948812/vita3k.log)

**Comment by Rinnegatamante** [comment]
I suspect this is cause we actually raise up threads waiting in sceKernelWaitThreadEnd only if sceKernelExitThread when we should raise up threads also when:
1) They simply return
2) sceKernelExitDeleteThread is called

**Comment by Rinnegatamante** [comment]
Partially fixed with https://github.com/Vita3K/Vita3K/pull/179 that should implement 1
