### ISSUE TITLE
Tales of Hearts R missing texture on latest build

### ISSUE THREAD

**Issue by X0Reactor** [Vita3K/Vita3K#1781]
In Tales of Hearts R, at the Seaville Armory. There is the statue that wears armor. On original hardware, the armor shows up normal. Using **Vita3K latest master 0.1.5 2601-f803e615**, the head of the armor renders perfectly fine but the body only shows blacked out texture.
This is how the texture should look on actual hardware.
![TOHRN](https://user-images.githubusercontent.com/61639060/171093825-a4e4e617-adb9-4d29-8b7d-7942a420d1c1.jpg)

And this is how Vita3k renders the armor statue.
![TOHRV3K](https://user-images.githubusercontent.com/61639060/171093898-ee55572f-5be2-44f5-9266-7126f0581c96.jpg)

As I said, the head armor is rendered perfectly fine, just the body doesn't. The log is attached below.
[vita3k log.zip](https://github.com/Vita3K/Vita3K/files/8802052/vita3k.log.zip)

Windows 10 Pro 21H1
OS Build: 19043.1052
GPU: GTX 1660 TI
CPU: i9-9900k
24gb DDR4-Ram
Edit: Forgot to add my specs.

**Comment by MarcoEstevez** [comment]
I just get a black screen, how did you make it work, does it requires any special settings

![image](https://user-images.githubusercontent.com/3447089/171102038-c5909db2-ff93-4bc2-8a94-5a6a37f34532.png)

**Comment by RainKikyou** [comment]
The current solution, you can try to switch the scene multiple times to get the correct texture

**Comment by Macdu** [comment]
For the black screen, you need to go to settings, configuration, check manual and automatic then enable libhttp.

For the graphic issue, I am aware of it, I am currently working on fixing it (along with the remaining overworld map graphic issues).

**Comment by Macdu** [comment]
Closing this issue as it was moved to Vita3K/compatibility#354 (being game specific).
