### ISSUE TITLE
Error - (number) of archive(s) did not found compatible content.

### ISSUE THREAD

**Issue by Stexico** [Vita3K/Vita3K#1788]
My game *Asphalt Injection [PCSE00007] (v01.00)* is not being showed or installed into the emulator...
Neither the .vpk or .zip files is working and I converted the .rar file into a .zip file... FYI 
The issue is on the latest version *v0.1.5 2603-8da6c6f*
Please look into this ASAP...
I want to play this game peacefully

**Comment by Macdu** [comment]
Sorry, we can't help you here. You need to dump your own games from a ps vita.

**Comment by Stexico** [comment]
Okay then.

**Comment by Stexico** [comment]
I'll use a another emulator if it works.
