### ISSUE TITLE
Fixed Guest Virtual Memory Allocation

### ISSUE THREAD

**Issue by illusion0001** [Vita3K/Vita3K#1799]
Currently guest memory allocation is not fixed and will allocate anywhere, one boot of the emulator can be at `0x11F4B940000` and another can be at `0x19ECDE40000`.

Edit: preferably matching base elf addr but +`0x400000000`, `0x481000000` for easier monitoring of memory.

**Comment by Macdu** [comment]
Good idea, it will make debugging easier too!
