### ISSUE TITLE
About delete addcont/dlcs dialog.

### ISSUE THREAD

**Issue by Croden1999** [Vita3K/Vita3K#1827]
we should need the 'Delete DLCs' dialog to avoid deleting DLCs by mistake, and to keep or delete the DLCs.
![2022-06-09-161706](https://user-images.githubusercontent.com/61804715/172800875-500093d0-248a-4112-9f5d-1e7e12325b06.jpg)

**Comment by Zangetsu38** [comment]
ah yes, is debug option, i no have it on my vita

**Comment by Croden1999** [comment]
i add the dialogs, need some time to complete it.

- dlc/addcont
![36bf05b9e71f0aa6](https://user-images.githubusercontent.com/61804715/228670760-54d55864-083c-407c-a3b1-126c04f78ecd.jpg)

- license
![572b0524b1cf2939](https://user-images.githubusercontent.com/61804715/228670936-d299b365-ce9d-4f33-9d73-2e673faee978.png)
