### ISSUE TITLE
Be explicit about fullscreen functionality in the GUI

### ISSUE THREAD

**Issue by DukeSkinny** [Vita3K/Vita3K#1839]
At the moment you can maximize the window, but this leaves the menu bar visible. I request a proper fullscreen mode, preferably with commandline functionality.

**Comment by Zangetsu38** [comment]
last time i have tested commandline no works for it

**Comment by DukeSkinny** [comment]
I'm not sure I understand, but nevertheless a fullscreen mode would be appreciated. Even if it can't be triggered using commandline. A shortcut (Ctrl + F?) may be a good idea.

**Comment by Zangetsu38** [comment]
is actually F11 for enable/disable full screen.

**Comment by DukeSkinny** [comment]
It seems you're correct! In that case, I request that this becomes more evident in the GUI. I'll change the issue title.

**Comment by Zangetsu38** [comment]
i have pr one things, for can using option for when you boot apps it switch on fullscreen
