### ISSUE TITLE
Potential Memory Leak

### ISSUE THREAD

**Issue by FromAlaska** [Vita3K/Vita3K#185]
I was looking through some code and I found a potential memory leak in /Vita3K/src/emulator/modules/SceGxm/SceGxm.cpp on function `EXPORT(void, sceGxmDisplayQueueAddEntry, Ptr<SceGxmSyncObject> oldBuffer, Ptr<SceGxmSyncObject> newBuffer, Ptr<const void> callbackData)` on line 354. `DisplayCallback *display_callback = new DisplayCallback();` was called, but never gave the memory back to the system. I recommend fixing the issue by calling delete or use a smart pointer.

**Comment by bentokun** [comment]
Isn't delete the pointer makes the value pushed in the display queue invalid? [Take a look](
https://github.com/Vita3K/Vita3K/blob/master/src/emulator/modules/SceGxm/SceGxm.cpp#L371)

**Comment by bentokun** [comment]
I think when popped the value, it's moved to an unique pointer to be destroyed. (See Vita3K queue implementation)

**Comment by 1whatleytay** [comment]
This line doesn't exist anymore. Assuming the issue is fixed (although there are other leaks in gxm).
