### ISSUE TITLE
next macos build?

### ISSUE THREAD

**Issue by Grien25** [Vita3K/Vita3K#1856]
Any updates on a macos build? Running an intel mac but probably will upgrade soon to an m1/2 MacBook. 

Thanks!

**Comment by Zangetsu38** [comment]
> Any updates on a macos build? Running an intel mac but probably will upgrade soon to an m1/2 MacBook.
> 
> Thanks!

is currently full droped, and no thinks task supoport on m1, is no real cpu

**Comment by epic-bruh-moment** [comment]
The most likely opportunity in which macos support will be back is if
1. A developer gets their hand on an apple silicon machine
2. If the Vulkan build is properly developed and can be translated via MoltenVK

Vita3K currently relies on OpenGL and apple has completely deprecated it.

**Comment by Macdu** [comment]
Yes, I will soon start working on the vulkan build. But until it is ready for use (and has no issue with MoltenVK), MacOS will no longer be supported.

@epic-bruh-moment indeed you are right, I will remove macos from the readme.

**Comment by epic-bruh-moment** [comment]
I hope progress on it goes well. I saw that the vulkan build is taking baby steps in workflows via compilation.

Vita3k has lately been developing in strides thanks to developer effort and pull requests and I hope said momentum carries through.

**Comment by shinra-electric** [comment]
This issue can probably be closed, since the x64 macOS version is back. 

(Maybe can open another one about Apple Silicon support instead)
