### ISSUE TITLE
Can the full screen yellow border be changed to black?

### ISSUE THREAD

**Issue by a419416951** [Vita3K/Vita3K#1861]
Can the full screen yellow border be changed to black?
![{ X(MT0@M@6`S0{_8PQCBXT](https://user-images.githubusercontent.com/55371090/174085668-9bfda9c4-1e5c-4371-9fa4-a2503159b644.jpg)

**Comment by Zangetsu38** [comment]
no

**Comment by Macdu** [comment]
I guess we can add an option to choose what color we want the background color to be.

**Comment by Ristellise** [comment]
No.

Reason for yellow screen was afaik was to see how the game draws. There is a diff (Game renders vs Not rendering) between black screen and a yellow screen.

At the current stage it would be still helpful to have a yellow screen to debug if the game renders or not.

**Comment by deatrocker** [comment]
Would be nice, if we will be able to choose color

**Comment by JohnGodgames** [comment]
or just crop those lines...

**Comment by illusion0001** [comment]
Couldn't find it, color is `247,198,0` but closet I could find was this. https://github.com/Vita3K/Vita3K/blob/c974e550dda79b58b8429a6678b2d25453ab5012/vita3k/gui/src/private.h#L31

**Comment by Zangetsu38** [comment]
> No.
> 
> Reason for yellow screen was afaik was to see how the game draws. There is a diff (Game renders vs Not rendering) between black screen and a yellow screen.
> 
> At the current stage it would be still helpful to have a yellow screen to debug if the game renders or not.

BIG THX
