### ISSUE TITLE
An issue while inputting name(PCSE00871 [A.W. : Phoenix Festa])

### ISSUE THREAD

**Issue by pupilplay** [Vita3K/Vita3K#1868]
[vita3k.log](https://github.com/Vita3K/Vita3K/files/8934057/vita3k.log)

https://user-images.githubusercontent.com/107766873/174449977-25cc6a8e-a540-4217-ae12-e02154ebd40a.mp4

It's the issue that the inputbox popped out and disappeared in a moment which prevents me from typing or submitting.
I wonder whether it can be fixed by configuration or it will be fixed in the future update.

**Comment by Macdu** [comment]
This is a game specific issue, please post it in the compatibility repository.

**Comment by Croden1999** [comment]
is a input dialog issue. I run another region of this game found the same problem.

**Comment by Zangetsu38** [comment]
strange, it working before 🤔  in very old build
