### ISSUE TITLE
CMake build directory

### ISSUE THREAD

**Issue by FromAlaska** [Vita3K/Vita3K#187]
I've noticed CMake builds the MakeFile in the parent directory instead of the build directory. Would someone be able to fix this issue? I'm currently having issues trying to build this application on my Macbook.

Thanks,

Jim

**Comment by scribam** [comment]
@FromAlaska Does the answer from petmac solve your issue?

**Comment by scribam** [comment]
@FromAlaska Any updates?

**Comment by FromAlaska** [comment]
> 
> 
> @FromAlaska Any updates?

Hey, sorry I've been busy for a while. I can still take a look at it, soon though. I'll pull the current version and give you a full report on it. 

Thanks though!

**Comment by sunho** [comment]
Please reopen this if you still see problem.
