### ISSUE TITLE
issue with two games

### ISSUE THREAD

**Issue by kannaginomori** [Vita3K/Vita3K#1870]
Dear developer: 
When I play PCSG00528 (SWEET CLOWN ~午前三時のオカシな道化師~) and PCSG00991 (月影の鎖 ―狂爛モラトリアム―), I face the same issue: after I play them for some time (about fifteen minutes), the vita3k v0.1.5 2682 crashes and exits suddenly. I try to play them a lot of times, but I face the issue every time. 
If you can fix the bug, I will appreciate you extremely. 
Your Sincerely User.

**Comment by Zangetsu38** [comment]
thx for repport, but using repo of compatfor this 👌
