### ISSUE TITLE
Vita3k Untested Games

### ISSUE THREAD

**Issue by Triticum0** [Vita3K/Vita3K#1876]
Lots of games In the vita Libray are untested, making them not on your website. Counting from the [Vita wiki entries](https://en.wikipedia.org/wiki/List_of_PlayStation_Vita_games_(A%E2%80%93L)) there are 1517 (1310?) games, If you included region variations and demos it is probably in the 1000s.

I make a quick list in a google doc for you to do as you wish. It's Not completely accurate as I don't know vita Libray/Japanese at all, so games with a Japanese title/not matching the wiki entry + any games with a bracket at the end of the title didn't get flagged by power tools.
https://docs.google.com/spreadsheets/d/1OO4SHtpgF7pU1_ACA7q1Ej2cRm3_WLKlnOtnNFsXGW4/edit?usp=sharing

Edit: I Fixed the link

**Comment by Triticum0** [comment]
Mabey the title is a bit disingenuous all I'm saying is not all game are listed on your website

**Comment by GeorgeSpiggott** [comment]
I couldn't find Rayman Legends on the compatibility list. My copy won't install so I assume it should be in the 'nothing' section. 

https://vita3k.org/compatibility.html?lang=en

**Comment by GamingDucking** [comment]
Backup your Rayman Legends with NonpDrm.

**Comment by Triticum0** [comment]
compatibility list has improved since 22 so will close
