### ISSUE TITLE
AMD Driver 22.7.1 bugs

### ISSUE THREAD

**Issue by benderscruffy** [Vita3K/Vita3K#1989]
just updated the driver and lots of games just come up with a yellow screen and the music playing in the background
warning for anyone about to upgrade stick to 22.5.1

**Comment by SomeonefromArg** [comment]
Same here

**Comment by DisasterIncarnate** [comment]
same deal for steam deck, same games show up fine in windows such as Dead Nation & MotorStorm RC, in steam deck desktop/linux mode i get a yellow screen with audio playing in the background.

**Comment by scribam** [comment]
@benderscruffy can you check if you still have your issue with the latest amd driver?
