### ISSUE TITLE
Multiple GXM threads

### ISSUE THREAD

**Issue by IllusionMan1212** [Vita3K/Vita3K#201]
OpenTyrian (and possibly more hbs) has more than one SceGxmDisplayQueue.

![image](https://user-images.githubusercontent.com/36709480/39431464-1707fc4a-4c91-11e8-800a-e2890e8ae1c3.png)

Link to the homebrew: https://vitadb.rinnegatamante.it/#/info/14

Log: 
[vita3k.log](https://github.com/Vita3K/Vita3K/files/1960879/vita3k.log)

**Comment by Rinnegatamante** [comment]
This happens cause sceGxmTerminate actually doesn't destroy SceGxmDisplayQueue thread.
