### ISSUE TITLE
Any idea how to install a game from game folder

### ISSUE THREAD

**Issue by Triramama** [Vita3K/Vita3K#2011]
i've got a game that's not a zip, vpk or pkg, it's just a game folder with a bunch of files, any idea how to make the emulator run ir from there?
i tried zipping it into an archive and booting it but eh, no luck with that.
![image](https://user-images.githubusercontent.com/97356540/183233744-2c3a4d80-7fb9-4750-9cbb-2bc1d7225275.png)
edit: never mind i zipped it the wrong way that's why the arch wasn't being read

**Comment by Zangetsu38** [comment]
Is possible, no need zip, drag and drop this folder with id of game on emulator
