### ISSUE TITLE
Unable to run Vita3K on Ubuntu 22.04 with Nouveau driver

### ISSUE THREAD

**Issue by maikeru99** [Vita3K/Vita3K#2029]
After trying to run Vita3K’s [ec8bbf8](https://github.com/Vita3K/Vita3K/commit/ec8bbf84b81c02d04201cee6a758e6eb469ff4b0) commit an error window appears saying: “Could not create OpenGL context! Does your GPU at least support OpenGL 4.1?”

After running: 

    • glxinfo | grep 'version'

Outputs the following: OpenGL version string: 4.3 (Compatibility Profile) Mesa 22.1.7 - kisak-mesa PPA

Notes:

    • A vita3k.log is not created while running the emulator.
    • My graphic card is a Nvidia GT 640

**Comment by hobyst** [comment]
The Nvidia GeForce GT 640 only supports up to OpenGL 4.2 and Vita3K requires OpenGL 4.4 which means it cannot run Vita3K. It doesn't even support Vulkan which will also be implemented for the emulator in the future.

**Comment by Macdu** [comment]
I think the issue here is that the prompt says "Could not create OpenGL context! Does your GPU at least support OpenGL 4.1?", it should be changed to "Could not create OpenGL context! Does your GPU at least support OpenGL 4.4?"

**Comment by hobyst** [comment]
Yeah that's an error but as far as I know that message doesn't come from Vita3K but from some other software component, likely the OpenGL library itself, and I don't know if the message in that dialog can actually be changed.

**Comment by mrcmunir** [comment]
@maikeru99 You can export
export MESA_GL_VERSION_OVERRIDE=4.4
export MESA_GLSL_VERSION_OVERRIDE=440
And run Vita3k?  In some cases if force the context will work 
I'm using similar workarround in others emulator and can helped. 

If not you will needed  with recent propietary drivers can up to opengl 4.6 https://developer.nvidia.com/opengl-driver
Install this driver https://www.nvidia.com/Download/driverResults.aspx/191244/com instead Mesa3d drivers and will work.
Anyway that GPU got stuck in the 470 branch of the drivers by nvidia only fix bugs/security pathes now.

**Comment by maikeru99** [comment]
Now Vita3K runs without the error window and I can even load some homebrew such as "nKaruga"

![psvita](https://user-images.githubusercontent.com/108751523/186483463-16d9d0e5-78a6-4b96-b75d-6ebd37d108c3.png)

I attach the vita3k.log file:

[vita3k.log](https://github.com/Vita3K/Vita3K/files/9418182/vita3k.log)
