### ISSUE TITLE
fuuraiki 3 background image is lost only have text

### ISSUE THREAD

**Issue by cloudslsw** [Vita3K/Vita3K#2032]
![屏幕截图 2022-08-24 170255](https://user-images.githubusercontent.com/11231847/186378601-ad63ecad-20bb-4c93-a1c7-984012dff8ea.png)
![屏幕截图 2022-08-24 170619](https://user-images.githubusercontent.com/11231847/186378604-d42df63d-64b8-4acc-92aa-bea3824ab80d.png)

the compatibility result shows playable but not working on my end
use the build 0.1.5 2796, only moved system folder other setting is default, my system spec is i5 9400/1050ti/16GB

**Comment by scribam** [comment]
@cloudslsw do you have the same issue with the Vulkan renderer?

**Comment by cloudslsw** [comment]
> @cloudslsw do you have the same issue with the Vulkan renderer?

its been fixed long ago
