### ISSUE TITLE
Any method to support mod like repatch in psv ? 

### ISSUE THREAD

**Issue by YuriSizuku** [Vita3K/Vita3K#2041]
Is there any way to replace files like [repatch](https://github.com/SonicMastr/rePatch-reLoaded) to support game mod ?

**Comment by Croden1999** [comment]
u can overwrite the repatch file into ux0/app/[TITIE_ID].

**Comment by YuriSizuku** [comment]
> u can overwrite the repatch files into `ux0/app/[TITIE_ID]`, if readdcont files, u should overwrite files into `ux0/addcont/[TITLE_ID]`. (not all are valid)

Thank you for your reply.   Although overwriteing file works. If I want to keep both file without rename, is there any way to redirect files to other place ?

**Comment by Croden1999** [comment]
> > u can overwrite the repatch files into `ux0/app/[TITIE_ID]`, if readdcont files, u should overwrite files into `ux0/addcont/[TITLE_ID]`. (not all are valid)
> 
> Thank you for your reply. Although overwriteing file works. If I want to keep both file without rename, is there any way to redirect files to other place ?

none, because vita3k running decryption game.
