### ISSUE TITLE
The ability to re-set the keyboard controls doesn't work too well

### ISSUE THREAD

**Issue by LOuroboros** [Vita3K/Vita3K#2044]
Sup.

Now that Vita3K got a Vulkan renderer merged, I wanted to give things another test in case anything changed in regards to emulating Digimon World: Next 0rder compared to a few weeks back when I tested the emulator for the first time.

Back then I also noticed this, but it's getting annoying enough that I figured I should bring it up in an Issue ticket properly.

So, the emulator won't let me re-bind certain PS Vita buttons. That's the gist of it. I press my NumPad's 8 key to bind it to the emulated PSVita's "Right Stick Up" button, and it just doesn't really work. The emulator doesn't seem to accept that for some reason.

I recorded a quick video after deleting the controls config within the emulator's config.yml file to better show off what I mean.

I can modify the Left Stick keys just fine, but when I reach the Right Stick keys... I'm just not able to bind whatever key I want, though the same happens for the L3 Button which I was trying to set to the "T" key and the emulator was re-setting to the "F" key all on its own.

https://user-images.githubusercontent.com/4485172/187086188-0abb3c4b-a0d8-464c-b3fa-ff6608709dac.mp4

The funniest thing is that the emulator does let me assign the same keyboard key to 2 different PSVita buttons, as I can assign the 5 number to both the PSVita's Select button and its L3 button too, so I'm not sure I understand that "key is reserved!" warning I got in the command prompt.

![Vita3K_20220828_141412017](https://user-images.githubusercontent.com/4485172/187086395-d891f53e-6ad3-4944-8709-d6f3dc6cd267.png)

Maybe having the ability to clear all the set keys would be nice to have, so the user can just change every single button binding to their liking without all this hassle?

**Comment by scribam** [comment]
The issue has been fixed by #2100
