### ISSUE TITLE
[Linux] No longer building under clang-14

### ISSUE THREAD

**Issue by Shoegzer** [Vita3K/Vita3K#2046]
Project no longer builds, using updated clang-14.  

Details: 

* OS: Mint 21 (Ubuntu 22.04 base) / kernel 5.15.
* Commit tested: 67c1eb4c4799540fcdbe9d9c3835537ec66f86e3
* Last good commit tested: da6127cda1682303d75c2905c142618090bc7e63
* Build log: [build.log](https://github.com/Vita3K/Vita3K/files/9441017/build.log)

**Comment by hobyst** [comment]
From the latest `building.md`:
> Note: The CMake preset `linux-ninja-clang` makes use of the LLD linker, which will need to be installed in your system along with Clang.
You will be able compile Vita3K by just running:
```bash
sudo apt install lld
```
Since Ubuntu 22.04 `clang-tools` package defaults to Clang 14, `lld` package will also install LLD 14. After installing LLD everything should work like it did before.

**Comment by Shoegzer** [comment]
Thanks @hobyst. I revewed `readme.md` before submitting this report but missed that line. It's building fine now, I'll close.
