### ISSUE TITLE
cmakearm64 linux cmake Unsupported architecture

### ISSUE THREAD

**Issue by fengxue-jrql** [Vita3K/Vita3K#2084]

**Comment by fengxue-jrql** [comment]
when I run cmake --preset linux-ninja-clang,cmake tell me
-- Target architecture: arm64
CMake Error at external/dynarmic/src/dynarmic/CMakeLists.txt:369 (message):
  Unsupported architecture

**Comment by Zangetsu38** [comment]
arm is not supposrted that all

**Comment by fengxue-jrql** [comment]
what shoud I do on arm64 linux

**Comment by Zangetsu38** [comment]
nothing, is juste not supported that all

**Comment by fengxue-jrql** [comment]
vita3k support arm64 linux?

**Comment by Zangetsu38** [comment]
NO i said

**Comment by hobyst** [comment]
As of today, Vita3K only supports x86_64 / amd64 PCs. ARM CPUs aren't supported.
