### ISSUE TITLE
Size problem of surface sync

### ISSUE THREAD

**Issue by sans-2233** [Vita3K/Vita3K#2116]
The size of surface sync is 4 times smaller than the original size. Please adjust it. Thank you!
![a](https://user-images.githubusercontent.com/64002778/194004952-4aacf5b8-ebe8-4421-97b0-9b174fe2855b.jpg)

**Comment by Macdu** [comment]
That not how surface sync works. The graphical issues are related to the opengl renderer having many bugs.
