### ISSUE TITLE
error when trying to install zip files with unsupported characters in title

### ISSUE THREAD

**Issue by JimPancakes** [Vita3K/Vita3K#2120]
Used pkg2zip to convert a game and got a file named Soul Sacrifice™ Delta [PCSA00152] [USA].zip
Tried to install it in Vita3k but it kept saying that the file is unsupported. Wasted a bunch of time trying to figure out what the problem was until I took a peek at the Vita3k console thingy which referred to my file as Sacrifice DeltaΓäó [PCSA00152] [USA].zip
Well that's odd I said and then deleted the ™ from the file's title which fixed the problem. 

Sorry if this a known issue. If not please consider taking a look into it as it kinda comes as a natural occurrence since this is how pkg2zip names some games.

**Comment by Macdu** [comment]
Hello, thank you for reporting this issue, I'll have a look at it.

**Comment by Macdu** [comment]
Are you using Linux or Windows as your OS?

**Comment by JimPancakes** [comment]
> Are you using Linux or Windows as your OS?

I'm using Windows 10 64bit.
Also the ® symbol has the same issue.

**Comment by CookiePLMonster** [comment]
The issue is quite clearly related to some UTF-8 string being misinterpreted as ANSI, or vice versa. The fact it shows as `Sacrifice DeltaΓäó` suggests the former, aka reading UTF-8 and treating it as ANSI.
