### ISSUE TITLE
Problem with libssl version

### ISSUE THREAD

**Issue by pupilo-py** [Vita3K/Vita3K#2180]
I'm using (K)Ubuntu 22.10 and because the libssl version is different from the one required by Vita3K the emulator doesn't run.

![image](https://user-images.githubusercontent.com/58078395/199956597-8f42b693-8c8e-47fb-a2be-77a1bcf53d50.png)

I know there are already requests for a flatpak version, but I believe that a version in a universal packaging is actually needed.

**Comment by degradka** [comment]
+1 I have the same problem

**Comment by Fancy2209** [comment]
> I'm using (K)Ubuntu 22.10 and because the libssl version is different from the one required by Vita3K the emulator doesn't run.
> 
> ![image](https://user-images.githubusercontent.com/58078395/199956597-8f42b693-8c8e-47fb-a2be-77a1bcf53d50.png)
> 
> I know there are already requests for a flatpak version, but I believe that a version in a universal packaging is actually needed.

I believe you could grab the so from the ssl1 Deb (opening it from the archive manager) and putting it into the libraries folder?

**Comment by zandercodes** [comment]
Same issue on Steam Deck

**Comment by pupilo-py** [comment]
The problem was fixed by adding libssl in the required version in the Vita3k folder in the latest builds, but I still believe in the need for a package in flatpak format.
