### ISSUE TITLE
(gui/settings.cpp) Wrong height for Settings/Theme & Background/Theme

### ISSUE THREAD

**Issue by Calistex** [Vita3K/Vita3K#2186]
The height of the Theme selectable is wrongly calculated. Is there a reason why it is dynamically set? Otherwise it could just be fixed to `ImVec2(0.f, 80.f * SCALE.y)` like the other two selectables.
https://github.com/Vita3K/Vita3K/blob/692549a25f15851f43f6bea929fce53c7046a3fb/vita3k/gui/src/settings.cpp#L312
![image](https://user-images.githubusercontent.com/11682775/200652372-cf2a23f1-6101-4f5c-8042-21a3326c32c5.png)

**Comment by Zangetsu38** [comment]
Nothing is wrong here

**Comment by Calistex** [comment]
@Zangetsu38  Isn't it supposed to look like this?
![image](https://user-images.githubusercontent.com/11682775/200685046-0ca490fd-dc71-4633-99a9-9c49cdcbea55.png)

**Comment by Zangetsu38** [comment]
Yes is like that is normal

**Comment by Zangetsu38** [comment]
after check, value is already set in consty 80, you have bad look

**Comment by Zangetsu38** [comment]
ok you have right, have nissue, but is strange, is not here before, who have broken this 🤔

**Comment by Calistex** [comment]
![image](https://github.com/Vita3K/Vita3K/assets/11682775/2e5f27f2-a58b-4dd6-9f85-8d564743a71e)
@Zangetsu38  Looks like it's been fixed

**Comment by Zangetsu38** [comment]
ah yes, i have fixded it olkd time, forget close issue
