### ISSUE TITLE
Debugger

### ISSUE THREAD

**Issue by iadlast** [Vita3K/Vita3K#22]
I realize this project is still at a very early stage, but I thought that it couldn't hurt to ask for this: it would be a good idea to add at some point a debugger capable of using breakpoints, similar to the ones found in PPSSPP or PCSX2. After all, an emulator with a debugger is a tremendous asset to have for fan translation and romhacking projects to catch and fix bugs or do modifications in the code to add proper support of non-Japanese text.

**Comment by pent0** [comment]
@sunho We have kernel objects showers and GDB support now. Is it ok to close down this issue?

**Comment by sunho** [comment]
Yes. Although it's not as powerful as what PPSSPP got, we definitely have a working debugger.
