### ISSUE TITLE
An image error occurred while running PCSG00910

### ISSUE THREAD

**Issue by liyi202098** [Vita3K/Vita3K#2268]
PCSG00910【DIABOLIK LOVERS LOST EDEN 】
PCSG00826【DIABOLIK LOVERS LUNATIC PARADE】

In vita3k 2848, there was a graphical error, the characters disappeared, the characters turned blue, the background disappeared sometimes, but the same game PCSG00530 and PCSG00472, can work normally

When tested in version 2968, the results were the same
![bandicam 2023-01-06 19-05-09-569](https://user-images.githubusercontent.com/115157643/211181873-ac654274-fce7-4c73-9d65-885e84fc7ad8.jpg)

**Comment by liyi202098** [comment]
![bandicam 2023-01-08 13-35-55-907](https://user-images.githubusercontent.com/115157643/211182095-bf8dd793-3594-47f0-80d3-d2475dceb76e.jpg)
![bandicam 2023-01-08 13-36-01-913](https://user-images.githubusercontent.com/115157643/211182101-99e712da-fdef-4c56-83bd-4a904b883fb1.jpg)

**Comment by hiroshiyuri** [comment]
This is a game specific issue, please post it in the compatibility repository here:

[Diabolik Lovers: Lunatic Parade [PCSG00826]](https://github.com/Vita3K/compatibility/issues/660)
[Diabolik Lovers: Lost Eden [PCSG00910]](https://github.com/Vita3K/compatibility/issues/659)
