### ISSUE TITLE
Vita3K Build Instuctions Are Not User Friendly

### ISSUE THREAD

**Issue by Kumoashi** [Vita3K/Vita3K#23]
Even for some one who has compiled this kind of source code before, I still found myself needing to search for some kind of guide. Even with that, I had to do some guessing, since not everything matched what I found.
It also didn't help that, even with the latest version of CMake installed, your gen.bat file only made the build-windows directory, but never ran CMake to create the Vita3K.sln file. I had to bring up CMake myself and tell it how to build the Vita3K.sln file, and I'm not sure if I got everything set correctly.

I think that you should explain the process a bit better, using step by step instructions in the future, so that as more people become aware of this project, they will be able to compile a build of it themselves, and give you meaningful feed back about it, instead of endless complaints about where to get Vita3K and how to compile it.

Here is an example of what I'm referring to:
**https://github.com/citra-emu/citra/wiki/Building-For-Windows**
These are the Windows build instructions for the emulator Citra. While not perfect, they are a lot easier to follow and they also provide links to all the required software, as well as, how to set it all up.

I hope all of this can be of some help to you and your project. I look forward to what comes of this in the future, and I think it's about time that the PS Vita got the attention that it deserves.
Thank you for taking the time to read this, and thank you for this new up coming emulator.

**Comment by Ghabry** [comment]
The Citra build instructions are a total exception. I never saw such detailed build instructions before.

In my opinion the instructions about building vita3k are almost enough.
I would only suggest adding a note that you have to run ``git submodule update --init" first and that you need Visual Studio 2017 installed.

**Comment by cybertronicgames** [comment]
@Kumoashi 
I used Git to clone the submodules using this link here "https://github.com/Vita3K/Vita3K.git",
ran the gen.bat file "I have CMake installed to path", ran the Vita3K.sln file, selected Release, Emulator & build in Visual Studios.

I've done this before & had no problems.

![screenshot 143 2](https://user-images.githubusercontent.com/14711758/35601368-3d8dbda8-05f8-11e8-9d15-9e9416fa2aa5.jpg)

This is Windows instructions.

**Comment by Kumoashi** [comment]
Ok, so how do I clone the submodules, and what do you mean when you say "I have CMake installed to path"? Every time I run the gen.bat, I get an empty folder.

I have tried to use CMake GUI to compile the Vita3K.sln myself, but I don't know what exactly I need to do to make a working file. What I end up seeing is this.

![image](https://user-images.githubusercontent.com/24490104/35776210-64e43654-0966-11e8-93c3-6bc872f36061.png)

I still get the Vita3K.sln file, but every time I try to compile the emulator, I get a folder called ZERO_CHECK instead. I'm sure that if I could get the CMake step to work right, the rest would work out, but so far that has not been the case.

**Comment by cybertronicgames** [comment]
@Kumoashi Are you using Windows or MacOS? I'm using Windows.

I used Git GUI "http://gitforwindows.org" to clone the submodules at this address "https://github.com/Vita3K/Vita3K.git", installed "added to path when installed" CMake v3.10.01 at https://cmake.org/download/ , installed Visual Studios 2017 Community at  https://www.visualstudio.com/downloads/ "Made sure to select C++ support in the installer".

1. Open Git GUI.exe, select "clone existing repository", paste "https://github.com/Vita3K/Vita3K.git" in source location, add the location of target directory "C:/Users/Owner/Vita" & check marked "recursively clone submodules" & clicked the "clone" option. Waited until it's finished.

![screenshot 161](https://user-images.githubusercontent.com/14711758/35779427-61ff9e34-0992-11e8-98bc-edd76a89666f.jpg)


2. Opened the location of target directory "C:/Users/Owner/Vita" & Ran "gen.bat" file. Waited until that was finished.

![screenshot 159](https://user-images.githubusercontent.com/14711758/35779430-6a69b1ea-0992-11e8-8784-8b79f1a72985.jpg)

3. Opened "C:\Users\Owner\Vita\build-windows" location & ran "Vita3K.sln"

![screenshot 162](https://user-images.githubusercontent.com/14711758/35779455-e317c456-0992-11e8-9c19-2b5560c12d1d.jpg)

4.When all the files loaded, Visual Studios says ready at the bottom. I set it to "release",

![screenshot 163](https://user-images.githubusercontent.com/14711758/35779489-7cf965f2-0993-11e8-9da0-3bd629128c66.jpg)

then right clicked "emulator" & "set as startup project" then selected build.

![screenshot 164](https://user-images.githubusercontent.com/14711758/35779531-02e9d7be-0994-11e8-9645-a1e7125eddd0.jpg)

Waited until it was finished & had no errors.

**Comment by Kumoashi** [comment]
This worked. Thank you.
My problem was not having CMake installed with system path and not knowing about downloading the submodules.
These instructions are very clear and easy to follow. I think this should be put on the main page, so that it can be a help to others as well.

**Comment by cybertronicgames** [comment]
Homebrews links http://vitadb.rinnegatamante.it/#/

http://rinnegatamante.it/site/psv_hbs.php

**Comment by Kumoashi** [comment]
Thanks for the links.

**Comment by VelocityRa** [comment]
Users can get the builds from Appveyer/Travis now.
Devs will know how to build, it's pretty standard stuff. Same for Linux users for which there aren't Travis builds yet.
