### ISSUE TITLE
Super Idol 

### ISSUE THREAD

**Issue by MugenGitHub2693** [Vita3K/Vita3K#2302]
Super Idol的笑容
都没你的甜
八月正午的阳光
都没你耀眼
热爱 105 °C的你
滴滴清纯的蒸馏水
你不知道你有多可爱
跌倒后会傻笑着再站起来
你从来都不轻言失败
对梦想的执着一直不曾更改
很安心 当你对我说
不怕有我在
放着让我来
勇敢追自己的梦想
那坚定的模样
Super Idol的笑容
都没你的甜
八月正午的阳光
都没你耀眼
热爱 105 °C的你
滴滴清纯的蒸馏水
在这独一无二
属于我的时代
不怕失败来一场
痛快的热爱
热爱 105°C的你
滴滴清纯的蒸馏水
在这独一无二
属于我的时代
莫忘了初心常在
痛快去热爱
热爱 105°C的你
滴滴清纯的蒸馏水
喝一口又活力全开
再次回到最佳状态
喝一口哟
你不知道你有多可爱
跌倒后会傻笑着再站起来
你从来都不轻言失败
对梦想的执着一直不曾更改
很安心 当你对我说
不怕有我在
放着让我来
勇敢追自己的梦想
那坚定的模样
Super Idol的笑容
都没你的甜
八月正午的阳光
都没你耀眼
热爱 105°C的你
滴滴清纯的蒸馏水
在这独一无二
属于我的时代
不怕失败来一场
痛快的热爱
热爱 105°C的你
滴滴清纯的蒸馏水
在这独一无二
属于我的时代
莫忘了初心常在
痛快去热爱
热爱 105°C的你
滴滴清纯的蒸馏水
喝一口又活力全开
再次回到最佳状态
喝一口又活力全开

**Comment by Croden1999** [comment]
请不要发这些无意义的东西，Issue是提交问题的，而不是让你在这乱发内容的，如果不想破坏交流环境，请停止你的无意义行为。
please stop it.

**Comment by Aleixz** [comment]
请立刻停止你在GitHub上拉屎的行为谢谢
