### ISSUE TITLE
7'scarlet [PCSE01168]，The game cannot display text.

### ISSUE THREAD

**Issue by mojing33** [Vita3K/Vita3K#2305]
The text can't be displayed after starting the game.
![Screenshot_2023-02-12-20-59-49-986_org vita3k emulator](https://user-images.githubusercontent.com/125195461/218313397-36a595df-2a07-447a-8208-5d8864ea54a6.jpg)
![Screenshot_2023-02-12-20-58-33-858_org vita3k emulator](https://user-images.githubusercontent.com/125195461/218313409-5e868541-7622-4ed0-ba5c-50508a63f978.jpg)

**Comment by Zangetsu38** [comment]
if you see diference of vita3kj for winhdows, open issue in github on vita3k android, no here
https://github.com/Vita3K/Vita3K-Android/issues
