### ISSUE TITLE
Driver selection shows as a number instead of the name

### ISSUE THREAD

**Issue by timunkun** [Vita3K/Vita3K#2307]
I don't know why but my driver selection displayed as a number instead of the name. I saw some people displayed it as the name of the driver 

![Screenshot_20230212-204141882](https://user-images.githubusercontent.com/106679989/218315809-2b1a5161-b7f3-4aeb-aef5-de78807647e4.png)

**Comment by Zangetsu38** [comment]
no post here but here
https://github.com/Vita3K/Vita3K-Android/issues
