### ISSUE TITLE
Vita3k android problem 

### ISSUE THREAD

**Issue by Makotoyuke** [Vita3K/Vita3K#2308]
Device: Realme c2
Os: Android 9
Soc: Mediatek Helio P22
Problem: when I open vita3k it immediately crashes Idk if it's a gpu problem since it's a powervr gpu & not mali or adreno or maybe due to the gpu not supporting vulkan idk

**Comment by Zangetsu38** [comment]
no post here but here
https://github.com/Vita3K/Vita3K-Android/issues
