### ISSUE TITLE
What rom file do i dwnld? Maidump or nonpdrm

### ISSUE THREAD

**Issue by 9thwardRondo** [Vita3K/Vita3K#2312]
I installed madden the 1st time no problem it loaded but didn't play then I seen that it's only capable of playing pkg. Nonpdrm files not maidump so download the nonpdrm file now when I go to install it it says content not compatible plz help what file am I suppose to download for the rom

**Comment by Herothegeek** [comment]
Nonpdrm

**Comment by NabsiYa** [comment]
do not pirate.
