### ISSUE TITLE
vita3k android unable to archive problem

### ISSUE THREAD

**Issue by sans-2233** [Vita3K/Vita3K#2313]
Although you can see the saved data, it will become a new archive after entering the game.
![Screenshot_20230213_191314_org vita3k emulator](https://user-images.githubusercontent.com/64002778/218449381-2b2d79e5-4a83-4d50-ad86-06cbbd63a71b.jpg)

![Screenshot_20230213_191159_org vita3k emulator](https://user-images.githubusercontent.com/64002778/218449161-57201a8c-ebe1-4a5f-b63b-f27143225cf8.jpg)

**Comment by CoffeeBrewer64** [comment]
what do you mean by a new archive? a .zip?

**Comment by Croden1999** [comment]
> what do you mean by a new archive? a .zip?

he should be said new saved data

**Comment by Zangetsu38** [comment]
using android repo for issue of android
