### ISSUE TITLE
ITALIAN LANGUAGE BUG

### ISSUE THREAD

**Issue by Alfierenebro** [Vita3K/Vita3K#2314]
When I select the Italian language and try to install a game the emulator  will either crash and I have to clean everything mb of data to make it work again or the game with errors and it will crash every time I try to open it. But when I select the English language the game install without any problems or crash. I tested it only on sly cooper thieves in time.

**Comment by Alfierenebro** [comment]
I'm talking about vita3k for android

**Comment by CoffeeBrewer64** [comment]
a. could you please test it on another game?
b. is this the vita3k home screen crashing or the game crashing?
c. could you please also test it on vita3k windows, mac or Linux?

thx!
