### ISSUE TITLE
Lego Batman 3 Not Installing | Makes VITA3K not boot anymore

### ISSUE THREAD

**Issue by Sean23189** [Vita3K/Vita3K#2323]
Let's get some basic information out the way:
DEVICE: Samsung Tab S8 Ultra
OS: Android 13
CPU: sm8450
GPU: Adreno 730
Vita3k Version: Android Release 2

I have dumped Lego Batman 3 from the cartridge that I own using **FAGDec**, the steps I took doing this were as following:
- Goto gro0:app/
- Open decrypted "PCSE00442/"   (using Vitashell just like the guide on the website suggests)
- Copy ALL files to ux0:vpks/PCSE00442/          (vpks is a folder i use to dump games the name vpks doesnt have to do with anything)
- Open FAGDec
- Scroll down and press X on Lego Batman 3
- Select Decrypt all 
- Press O
- Press START
- Select [START]START DECRYPT (SELF)
- After it says done I just exit and close FAGDec
- Open Vitashell again
- Navigate to ux0:FAGDec/app/PCSE00442
- Copy ALL files into ux0:vpks/PCSE00442        (no override prompt as the quide on the Vita3k website suggested which already made me think something was wrong)
- use ftp to copy the PCSE00442 folder with all the combined files onto my tablet
- Compress the files into .zip 
- Select the zip from the menu in Vita3k
- Receive an Error (attached video for reference)
- Can't open Vita3k anymore (removing the game folder from Vita3k fixes it)

And now I'm here, the steps to fix this that I tried were:
- Before removing the game folder I tried force closing + clear cache but nothing changed
- Unzip the game folder again and put it into ux0:app from Vita3k (as an unzipped folder not just directly the files of course)
- Put the game folder into gro0:/app inside the Vita3k files

Now my questions are:
- Do I need to take special steps as it is a cartridge game?
- Could there possibly be an error in the transfering process between all the folders and to my tablet?
- And of course how do I fix this

While waiting for a reply I will try a different cartridge game and update the issue accordingly.
Thanks for any help in advance.

https://user-images.githubusercontent.com/66129659/218594665-a2124207-7f36-4243-9a88-37377abf67ed.mp4

**Comment by IllusionMan1212** [comment]
Android related issues should be reported in this repo https://github.com/vita3k/vita3k-android
