### ISSUE TITLE
STREET FIGHTER X TEKKEN BUG

### ISSUE THREAD

**Issue by kongkingbeatanime** [Vita3K/Vita3K#2326]
When I play street fighter x Tekken the text is glitched badly, please help, I've tried different websites to download the game, but it's still glitched, please fix it
![Screenshot_20230213-141527](https://user-images.githubusercontent.com/125224166/218634833-5a0c9691-3158-4c1e-965e-44544b709496.jpg)

**Comment by IllusionMan1212** [comment]
Wrong repo. Go to https://github.com/vita3k/vita3k-android
