### ISSUE TITLE
Can't uninstall the app ond Android - package installer crashes

### ISSUE THREAD

**Issue by Paoleddu** [Vita3K/Vita3K#2329]
As for the title, I cannot uninstall the app on Android.
Phone is an S22 running on Android 13.
Uninstalling other apps works just fine.
I've also cleanded the storage for the package installer, but to no avail.
Video attached.

[Video](https://imgur.com/a/BfHacGG)

**Comment by abasgames** [comment]
Please submit any issue related to android version of vita3k here https://github.com/Vita3K/Vita3K-Android/

**Comment by Paoleddu** [comment]
Ok

**Comment by bookmist** [comment]
for android specific issues, report them here https://github.com/Vita3K/Vita3K-Android/issues/new, for game specific issues open one in https://github.com/Vita3K/compatibility/issues/new or update the report
