### ISSUE TITLE
Cursh in Huawei phone all time

### ISSUE THREAD

**Issue by AKJIN** [Vita3K/Vita3K#2333]
#App cursh always in playing time in Huawei mobile on honor 9xpro 6gb ram 256 rom, Processer kirin 810  
GPU mali G52 Android 9

**Comment by bookmist** [comment]
for android specific issues, report them here https://github.com/Vita3K/Vita3K-Android/issues/new, for game specific issues open one in https://github.com/Vita3K/compatibility/issues/new or update the report
