### ISSUE TITLE
Blackscreen when opening the app

### ISSUE THREAD

**Issue by Retrohunterid** [Vita3K/Vita3K#2336]
blackscreen when opening vita3k on android 7.1 arm64, snap 450 vulkan 1.0. please fix it in latest build. 
![Screenshot_2023-02-15-06-25-38-55](https://user-images.githubusercontent.com/125420951/218908776-88e0bad4-f79a-4037-80a7-4bc790643652.png)

**Comment by bookmist** [comment]
for android specific issues, report them here https://github.com/Vita3K/Vita3K-Android/issues/new, for game specific issues open one in https://github.com/Vita3K/compatibility/issues/new or update the report
