### ISSUE TITLE
Softbrick in android

### ISSUE THREAD

**Issue by AngelFresko** [Vita3K/Vita3K#2337]
when I press the install pkg button and I put a vpk file when I put the zrif and the keyboard opens in the Android version this causes a softbrick on the phone forcing you to restart it

Sorry for the bad translation, I don't know much English

**Comment by Zangetsu38** [comment]
> when I press the install pkg button and I put a vpk file when I put the zrif and the keyboard opens in the Android version this causes a softbrick on the phone forcing you to restart it
> 
> Sorry for the bad translation, I don't know much English

againb, vitamin dump is not compatible on emulator
