### ISSUE TITLE
SpongeBob HeroPants

### ISSUE THREAD

**Issue by VladVoltman99** [Vita3K/Vita3K#2338]
the game crashes when the gameplay is already
![Screenshot_20230215-084147_One UI Home](https://user-images.githubusercontent.com/125199104/218952283-491af047-b2b2-432c-a61e-7d89b820682e.jpg)

**Comment by bookmist** [comment]
for android specific issues, report them here https://github.com/Vita3K/Vita3K-Android/issues/new, for game specific issues open one in https://github.com/Vita3K/compatibility/issues/new or update the report
