### ISSUE TITLE
Issues to install Vita 3k firmware on Android 

### ISSUE THREAD

**Issue by Rinoka84** [Vita3K/Vita3K#2343]
Greetings, I wish to tell you I couldn't install firmware file and font package on Android 11 (Poco F3). After I select these files (.PUP) on file manager nothing happens and don''t appear a screen indicating the update is running. I think it's a blocking or censoring within Android 11(MIUI 12.0.2). How could I do to play this emulator on Poco F3?

**Comment by bookmist** [comment]
for android specific issues, report them here https://github.com/Vita3K/Vita3K-Android/issues/new, for game specific issues open one in https://github.com/Vita3K/compatibility/issues/new or update the report
