### ISSUE TITLE
Project diva f 

### ISSUE THREAD

**Issue by kasane1ted** [Vita3K/Vita3K#2351]
touch screen It doesn't work in gameplay but ingame it works 

![Screenshot_2023-02-15-22-22-08-06_74fe318baca9186e0035f53f6dd1d3fc](https://user-images.githubusercontent.com/73513503/219566394-b0ec1b44-6218-49ed-8931-565a8adf7998.jpg)

**Comment by Zangetsu38** [comment]
Android issue, using repo if it for this
