### ISSUE TITLE
(Mobile) Kirin Processors are not supported

### ISSUE THREAD

**Issue by Emylian-bit** [Vita3K/Vita3K#2358]
Games do not boot at all but the app itself works. I tried running compatible games but none of them are bootable. The app instantly crashes after tapping "Play".

**Comment by bookmist** [comment]
for android specific issues, report them here https://github.com/Vita3K/Vita3K-Android/issues/new, for game specific issues open one in https://github.com/Vita3K/compatibility/issues/new or update the report
