### ISSUE TITLE
Constant crash on some games!

### ISSUE THREAD

**Issue by YusukeHunter** [Vita3K/Vita3K#2374]
mortal kombat 9 for example, after two fight the emulator stop work, need reopen again.

Smartphones:
Poco X3 PRO/ Galaxy S20 FE

Nice Port of Vita3k, thx.

**Comment by CoffeeBrewer64** [comment]
Please put Vita3k Android issues in the dedicated repo, and not on the main repo.

**Comment by AGirlBetty** [comment]
Mortal Kombat 9

Smartphone: Samsung A72 R15 turnip (driving suit)


The emulator closes after 3 battles. I need to restart the emulator.

**Comment by bookmist** [comment]
for android specific issues, report them here https://github.com/Vita3K/Vita3K-Android/issues/new, for game specific issues open one in https://github.com/Vita3K/compatibility/issues/new or update the report
