### ISSUE TITLE
MK 9 Not work.

### ISSUE THREAD

**Issue by AGirlBetty** [Vita3K/Vita3K#2376]
Mortal Kombat 9

Smartphone: Samsung A72 R15 turnip (driver)

The emulator closes after 3 battles. I need to restart the emulator.

**Comment by Tenkoouu** [comment]
> Mortal Kombat 9
> 
> Smartphone: Samsung A72 R15 turnip (driver)
> 
> The emulator closes after 3 battles. I need to restart the emulator.

Please Put this in the vita3k android issues repository, and not in the main repository

**Comment by bookmist** [comment]
for android specific issues, report them here https://github.com/Vita3K/Vita3K-Android/issues/new, for game specific issues open one in https://github.com/Vita3K/compatibility/issues/new or update the report
