### ISSUE TITLE
I have an issue opening any game

### ISSUE THREAD

**Issue by Hamed7783** [Vita3K/Vita3K#2377]
I can't play any game due to my Android 10

**Comment by CoffeeBrewer64** [comment]
Use adb, root your phone, flash Android 11 and install Vita3K.

**Comment by Hamed7783** [comment]
> Use adb, root your phone, flash Android 11 and install Vita3K.

is there a way to update without root

**Comment by CoffeeBrewer64** [comment]
no, you have to root

**Comment by bookmist** [comment]
for android specific issues, report them here https://github.com/Vita3K/Vita3K-Android/issues/new, for game specific issues open one in https://github.com/Vita3K/compatibility/issues/new or update the report
