### ISSUE TITLE
Extremely big icons with latest update in macOS

### ISSUE THREAD

**Issue by ArbestRi** [Vita3K/Vita3K#2391]
<img width="1072" alt="Screenshot 2023-03-02 at 6 26 23 AM" src="https://user-images.githubusercontent.com/86171223/222456317-74ff228a-f1ca-4e75-b25e-0cbc6ddadfeb.png">
This didn't happen in the earlier builds.

**Comment by Zangetsu38** [comment]
You can disable grid mode ? And look result

**Comment by ArbestRi** [comment]
<img width="1072" alt="Screenshot 2023-03-02 at 5 59 16 PM" src="https://user-images.githubusercontent.com/86171223/222623169-3bd77729-4335-4c3c-bb65-9bf6080b297c.png">
Text is massive

**Comment by Zangetsu38** [comment]
yes, with other dev i try actually found and fix this, but relate last build, lastr build have no touched texte size here, is probleme on mac only

**Comment by Zangetsu38** [comment]
ok you can test this build ?
https://github.com/Vita3K/Vita3K/suites/11320814981/artifacts/581348072

**Comment by ArbestRi** [comment]
This might be an issue with DPI as the new Macs have a Retina screen with a high DPI

**Comment by Zangetsu38** [comment]
> This might be an issue with DPI as the new Macs have a Retina screen with a high DPI

i have pass full days with try fix it ^^

**Comment by Zangetsu38** [comment]
i hope is fxed, test this build here
https://github.com/Vita3K/Vita3K/actions/runs/4326731046/jobs/7554502618

**Comment by ArbestRi** [comment]
Tried that build, and the compatibility message blocks the whole screen.
<img width="768" alt="Screenshot 2023-03-03 at 1 39 16 PM" src="https://user-images.githubusercontent.com/86171223/222834392-8035aec0-cc69-4b41-9c91-01984503c7a4.png">

**Comment by Zangetsu38** [comment]
What, i no understund here...

**Comment by Zangetsu38** [comment]
ok, sorry for delay, is normally full fixed with this build, fix also old sutpid issue in app loading backgroud
https://github.com/Vita3K/Vita3K/actions/runs/4331463155

**Comment by ArbestRi** [comment]
It got fixed 
<img width="1072" alt="Screenshot 2023-03-04 at 7 51 19 AM" src="https://user-images.githubusercontent.com/86171223/222915794-38ad6817-c863-4e39-aeb5-e42a24f4bd21.png">

**Comment by Zangetsu38** [comment]
Good is set fixed i waiting approve of Linux user but so is fixed

**Comment by ArbestRi** [comment]
On next launch, this happens. Bringing back Vita3K for macOS has now become a mistake 
<img width="1552" alt="Screenshot 2023-03-06 at 1 56 28 PM" src="https://user-images.githubusercontent.com/86171223/223244129-9e82020b-f26c-4001-be54-1fe0dd62ef7c.png">

**Comment by Zangetsu38** [comment]
using master
