### ISSUE TITLE
Latest build on Steam Deck has no/corrupted text

### ISSUE THREAD

**Issue by ds8k** [Vita3K/Vita3K#2400]
Running the latest build (3041) has issues rendering fonts on the Steam Deck. Looks to be related to #2396 as the commit before it runs fine.

![steamuserimages-a akamaihd](https://user-images.githubusercontent.com/4458812/223045437-fc850e5d-9d3d-4a83-af86-979a74ba5026.jpg)

**Comment by Zangetsu38** [comment]
if you can check this pr for look if fix your issue
https://github.com/Vita3K/Vita3K/pull/2401

**Comment by Zangetsu38** [comment]
i try some things on pr, you can test build when finished, want already see if this is good solution

**Comment by Zangetsu38** [comment]
@ds8k test again build, and show me result

**Comment by Zangetsu38** [comment]
should be fixed in master now.
