### ISSUE TITLE
"Welcome Park" has regressed on vulkan, before is normal ingame

### ISSUE THREAD

**Issue by Croden1999** [Vita3K/Vita3K#2404]
has crash on vulkan, in the previous version is normal https://github.com/Vita3K/compatibility/issues/516
![image](https://user-images.githubusercontent.com/61804715/223335060-e61da7a1-2106-48ec-b37a-f495356542d0.png)

dynarmic & vulkan
![223389679-2ebd0d96-2071-4c17-8685-024d16a40dfd](https://user-images.githubusercontent.com/61804715/223425580-6ddff3aa-ab7a-4248-9fd6-36b269cf7e8d.png)

**Comment by bookmist** [comment]
Please check if there is still this bug on latest commit https://github.com/Vita3K/Vita3K/commit/215073063a6b85bf43653f195804d64cbf31cdc8 . I hope I fixed it now.

**Comment by Croden1999** [comment]
> Please check if there is still this bug on latest commit [2150730](https://github.com/Vita3K/Vita3K/commit/215073063a6b85bf43653f195804d64cbf31cdc8) . I hope I fixed it now.

Mr. bookmist, is not your log pr issue, need waiting for Mr. Macdu fix it.
![image](https://user-images.githubusercontent.com/61804715/224529092-e60012ae-5258-498d-98cc-8bf8b25cf2b8.png)

**Comment by Croden1999** [comment]
is fixed
