### ISSUE TITLE
cant use keyboard or ps3 controller or mouse in the menu 

### ISSUE THREAD

**Issue by gare1987** [Vita3K/Vita3K#2408]
Hi, i decided to try emulator to play Uncharted Golden Abyss, finished setup everything, entered the main menu but i cant select any option in menu, i was trying to go to Options but could not, controller is not functioning or other what i wrote, any suggestions why is that ? Also graphical issues in the game.

**Comment by Gerold55** [comment]
You need to use the mouse to swipe the screen to select the options. If not it isn't gonna work...

**Comment by gare1987** [comment]
> You need to use the mouse to swipe the screen to select the options. If not it isn't gonna work...

Tnx, somehow i managed to enter the game, but it had graphical artifacts, after that it somehow started working correctly by itself, but with no auto center camera and inability to use mouse for combat, shooting is basically impossible, such a shame but i deleted everything.  Topic can be deleted, because it does not help anything anyone...
