### ISSUE TITLE
vita3k game save functions consistently crashing on Android

### ISSUE THREAD

**Issue by DooxMachine** [Vita3K/Vita3K#2412]
I've recently downloaded vita3k and followed through most of what the guides say (minus the driver customization parts), downloaded the firmware and the games on my own.

My phone is a LG Q92. The overall gameplay (I'm playing Steins;Gate 0) was fine and smooth, nothing too out of place until i started going into ANY of the save menus. Save or Load, if I choose any of them my phone crashes the moment the screen loads. I've no idea how to deal with this issue by myself, and it doesn't seem to me that anyone else has encountered this problem. Please help.

**Comment by Croden1999** [comment]
you should push your issue to https://github.com/Vita3K/Vita3K-Android/issues
