### ISSUE TITLE
apple vita3k not automatically updating

### ISSUE THREAD

**Issue by WKaiZ** [Vita3K/Vita3K#2436]
everytime when it shows me that there is an update, I click the update, and wait for a while (maybe half an hour), however, it seems it does not automatically update and open the application file itself as every time when I manually open it, it still shows that there is a new update available for me to download

**Comment by Zangetsu38** [comment]
no can help or mac, need mac dev here :/

**Comment by mrcmunir** [comment]
This problem happen under Windows 11 too you needed for some reason run with admin access

**Comment by mrcmunir** [comment]
> 

![image](https://user-images.githubusercontent.com/1274014/227169406-4359d303-6680-41cc-8bca-76646a4078eb.png)
It's stuck without admin for som reason copy temp Vita3k into system32 folder.
