### ISSUE TITLE
Vita 3k CTD on latest build 

### ISSUE THREAD

**Issue by GraveyardPete** [Vita3K/Vita3K#2454]
doesn't say anything it just crashes

[19:04:19.490] |I| [config::init_config]: backend-renderer: Vulkan
[19:04:19.500] |I| [config::init_config]: log-level: 0
[19:04:19.670] |I| [SDL_main]: Vita3K v0.1.6 3080-ebedf66e
[19:04:19.671] |I| [SDL_main]: Number of logical CPU cores: 4
[19:04:19.671] |I| [SDL_main]: Available ram memory: 8014 MiB
[19:04:21.832] |I| [renderer::vulkan::VKState::create]: Vulkan device: Intel(R) UHD Graphics 605
[19:04:21.835] |I| [renderer::vulkan::VKState::create]: Driver version: 101.2115
[19:04:21.837] |I| [renderer::vulkan::VKState::create]: Memory mapping is enabled
[19:04:23.703] |I| [renderer::vulkan::ScreenRenderer::setup]: Present mode: Fifo
[19:04:25.262] |W| [compat::load_compat_app_db]: App with title ID PCSE01101 has an issue but no status label. Please check GitHub issue 1391 and request a status label to be added.
[19:04:25.263] |W| [compat::load_compat_app_db]: App with title ID PCSG00580 has an issue but no status label. Please check GitHub issue 1378 and request a status label to be added.
[19:04:27.410] |I| [compat::update_compat_app_db]: Applications compatibility database is outdated, attempting to download latest updated at: 03-28-2023 06:36:37
[19:04:29.358] |W| [compat::load_compat_app_db]: App with title ID PCSG00580 has an issue but no status label. Please check GitHub issue 1378 and request a status label to be added.
[19:04:35.820] |I| [gui::download_update::<lambda_1>::operator ()]: Attempting to download and extract the latest Vita3K version 3082 in progress...

**Comment by Croden1999** [comment]
ahh, maybe used vita3k update? is normally

**Comment by Zangetsu38** [comment]
What is problèm? Is fixed normaly

**Comment by GraveyardPete** [comment]
![image](https://user-images.githubusercontent.com/111437308/228251153-ff26d4d1-5c87-4290-a1f2-78197685dd43.png)
i open it shows that and crashes

here's a from a clean download same build
![image](https://user-images.githubusercontent.com/111437308/228251763-4da1954c-5831-4e8d-b38c-f3f342451f9b.png)

it just disappears after showing cmd

**Comment by Croden1999** [comment]
> ![image](https://user-images.githubusercontent.com/111437308/228251153-ff26d4d1-5c87-4290-a1f2-78197685dd43.png) i open it shows that and crashes
> 
> here's a from a clean download same build ![image](https://user-images.githubusercontent.com/111437308/228251763-4da1954c-5831-4e8d-b38c-f3f342451f9b.png)
> 
> it just disappears after showing cmd
> 
> was working fine before i updated

could u change pref-path? in config.yml file, e.g. path c:\vita3k

**Comment by GraveyardPete** [comment]
> could u change the pref-path in config.yml file? e.g. C:\Vita3K

I tried it still same issue

**Comment by Croden1999** [comment]
> > could u change the pref-path in config.yml file? e.g. C:\Vita3K
> 
> I tried it still same issue

and ur emu path

**Comment by GraveyardPete** [comment]
> > > could u change the pref-path in config.yml file? e.g. C:\Vita3K
> > 
> > 
> > I tried it still same issue
> 
> and ur emu path

still the same unfortunately

**Comment by Zangetsu38** [comment]
Try run vita3k from cmd, for log keep here

**Comment by GraveyardPete** [comment]
> Try run vita3k from cmd, for log keep here

![image](https://user-images.githubusercontent.com/111437308/228312305-e408f3d6-de84-476b-b97c-4afe63f808c5.png)
do you mean like this? i try it like that or normally it doesn't generate a log file even on the new clean one

**Comment by Zangetsu38** [comment]
No using start

**Comment by Zangetsu38** [comment]
Just write vita3k and run

**Comment by GraveyardPete** [comment]
> Just write vita3k and run
![image](https://user-images.githubusercontent.com/111437308/228391657-c7d5c542-c499-48a3-a1fb-0650dab0f73f.png)

It's not doing anything, I found an old build from a shady site and the commands worked fine

**Comment by Zangetsu38** [comment]
Sorry but here is strange, i have never see this 🤔

**Comment by Zangetsu38** [comment]
Found me what build causing thisnin first, found last build succès boot for you

**Comment by Zangetsu38** [comment]
> doesn't say anything it just crashes
> 
> [19:04:19.490] |I| [config::init_config]: backend-renderer: Vulkan [19:04:19.500] |I| [config::init_config]: log-level: 0 [19:04:19.670] |I| [SDL_main]: Vita3K v0.1.6 3080-ebedf66e [19:04:19.671] |I| [SDL_main]: Number of logical CPU cores: 4 [19:04:19.671] |I| [SDL_main]: Available ram memory: 8014 MiB [19:04:21.832] |I| [renderer::vulkan::VKState::create]: Vulkan device: Intel(R) UHD Graphics 605 [19:04:21.835] |I| [renderer::vulkan::VKState::create]: Driver version: 101.2115 [19:04:21.837] |I| [renderer::vulkan::VKState::create]: Memory mapping is enabled [19:04:23.703] |I| [renderer::vulkan::ScreenRenderer::setup]: Present mode: Fifo [19:04:25.262] |W| [compat::load_compat_app_db]: App with title ID PCSE01101 has an issue but no status label. Please check GitHub issue 1391 and request a status label to be added. [19:04:25.263] |W| [compat::load_compat_app_db]: App with title ID PCSG00580 has an issue but no status label. Please check GitHub issue 1378 and request a status label to be added. [19:04:27.410] |I| [compat::update_compat_app_db]: Applications compatibility database is outdated, attempting to download latest updated at: 03-28-2023 06:36:37 [19:04:29.358] |W| [compat::load_compat_app_db]: App with title ID PCSG00580 has an issue but no status label. Please check GitHub issue 1378 and request a status label to be added. [19:04:35.820] |I| [gui::download_update::<lambda_1>::operator ()]: Attempting to download and extract the latest Vita3K version 3082 in progress...

And i no understund, tour first message you have log ?

**Comment by GraveyardPete** [comment]
> > doesn't say anything it just crashes
> > [19:04:19.490] |I| [config::init_config]: backend-renderer: Vulkan [19:04:19.500] |I| [config::init_config]: log-level: 0 [19:04:19.670] |I| [SDL_main]: Vita3K v0.1.6 3080-ebedf66e [19:04:19.671] |I| [SDL_main]: Number of logical CPU cores: 4 [19:04:19.671] |I| [SDL_main]: Available ram memory: 8014 MiB [19:04:21.832] |I| [renderer::vulkan::VKState::create]: Vulkan device: Intel(R) UHD Graphics 605 [19:04:21.835] |I| [renderer::vulkan::VKState::create]: Driver version: 101.2115 [19:04:21.837] |I| [renderer::vulkan::VKState::create]: Memory mapping is enabled [19:04:23.703] |I| [renderer::vulkan::ScreenRenderer::setup]: Present mode: Fifo [19:04:25.262] |W| [compat::load_compat_app_db]: App with title ID PCSE01101 has an issue but no status label. Please check GitHub issue 1391 and request a status label to be added. [19:04:25.263] |W| [compat::load_compat_app_db]: App with title ID PCSG00580 has an issue but no status label. Please check GitHub issue 1378 and request a status label to be added. [19:04:27.410] |I| [compat::update_compat_app_db]: Applications compatibility database is outdated, attempting to download latest updated at: 03-28-2023 06:36:37 [19:04:29.358] |W| [compat::load_compat_app_db]: App with title ID PCSG00580 has an issue but no status label. Please check GitHub issue 1378 and request a status label to be added. [19:04:35.820] |I| [gui::download_update::<lambda_1>::operator ()]: Attempting to download and extract the latest Vita3K version 3082 in progress...
> 
> And i no understund, your first message you have log ?

seems like the log file was from build 3080 or 3081 ( it was working before) maybe I'm not sure i deleted the log file and it wont generate a new one on the latest build , the old build i found is build 3038

**Comment by Zangetsu38** [comment]
I no understund 🤔

**Comment by GraveyardPete** [comment]
> I no understund 🤔

I'm not sure if the previous working build for me was 3080(based on the time of the commits) I used the update bat on 3080(when it was working) after the update to 3082 it wont boot anymore and a new log file won't generate

**Comment by Zangetsu38** [comment]
> > I no understund 🤔
> 
> I'm not sure if the previous working build for me was 3080(based on the time of the commits) I used the update bat on 3080(when it was working) after the update to 3082 it wont boot anymore and a new log file won't generate

User have report same on macos but i have no tested last build att all

**Comment by nn9dev** [comment]
Please download the latest build and try the following instructions. This will hopefully help us pinpoint the crash.

You can capture a full log by dragging and dropping the exe onto a cmd window and then adding `>Vita3K-crashtest.txt` to the end, like so: ![image](https://user-images.githubusercontent.com/39563889/228406330-11563067-ac5e-4a0b-94fc-9ee1babab947.png)

(Please excuse where it says uncharted-log.txt and replace it with what I said earlier. I'm using an old screenshot since I'm on my phone.)

Then, get to the point where it hangs/crashes, close it, and send the log. it will be wherever your working directory is, so the place at the beginning of the prompt. (It's the directory before the `>` at the very left, so in my case you can see it's at `D:\`, and that's where my log would be) 

Afterwards, upload that file. I believe for txt files GitHub should just be drag and drop. That will hopefully help us pinpoint what's going wrong.

**Comment by GraveyardPete** [comment]
![image](https://user-images.githubusercontent.com/111437308/228412763-b075bdd4-033d-4f22-91cb-c317e5464172.png)
It doesn't do anything and a log file doesn't show up i checked tasked manager and it doesn't even seem to be launching when I execute the command, I also changed the directory and same thing happens

**Comment by Zangetsu38** [comment]
i have tester last build, 0 probleme here

**Comment by nn9dev** [comment]
@GraveyardPete 
That's certainly odd. I don't recall any PR's recently that changed the way the app launches. There's only one odd bunch I have, and that's that somehow AVX broke something on Windows (which, it really shouldn't unless for some reason you're using an ARM CPU and have neglected to mention it). If this one doesn't work, check the GitHub Actions page for this repo and download builds until you can pinpoint where things broke. The build I refer to is below.

https://github.com/Vita3K/Vita3K/actions/runs/4532663384

**Comment by GraveyardPete** [comment]
> @GraveyardPete That's certainly odd. I don't recall any PR's recently that changed the way the app launches. There's only one odd hunch I have, and that's that somehow AVX broke something on Windows (which, it really shouldn't unless for some reason you're using an ARM CPU and have neglected to mention it). If this one doesn't work, check the GitHub Actions page for this repo and download builds until you can pinpoint where things broke. The build I refer to is below.
> 
> https://github.com/Vita3K/Vita3K/actions/runs/4532663384

This version works correctly here's the log file 
[vita3k.log](https://github.com/Vita3K/Vita3K/files/11099306/vita3k.log)

**Comment by GamingDuckingalt** [comment]
I believe that according to the FAQ on the Vita3K, the minimum requirement of the CPU is an AVX-compatible CPU. Sorry buddy, either you stick the old bulid without the change or just buy a new computer which had a AVX-compatible CPU.

**Comment by nn9dev** [comment]
@GraveyardPete This begs the question then – what's your CPU? AVX is a pretty standard thing nowadays.

**Comment by GraveyardPete** [comment]
It's a Pentium N5000 I checked intel's site and yeah it doesn't seem to support avx this thing was released in 2017 so I just came to a conclusion instead of checking.
