### ISSUE TITLE
Mac version crashing, cannot open after downloading

### ISSUE THREAD

**Issue by WKaiZ** [Vita3K/Vita3K#2455]
here is a preview of the error message
<img width="863" alt="Screenshot 2023-03-28 at 6 42 12 AM" src="https://user-images.githubusercontent.com/122955624/228257252-66210550-f46c-4c3d-b236-867925caa7ef.png">

**Comment by shinra-electric** [comment]
Looks like it was #2452 that broke it.

**Comment by nn9dev** [comment]
@shinra-electric are you on an m1/m2? i have to wonder if this is due to x86 shenanigans.

**Comment by shinra-electric** [comment]
Yep

**Comment by nn9dev** [comment]
That's fairly conclusive then. The MacOS version that's currently built is not a universal binary or whatever they're called, just x86_64. So either it's a Rosetta thing, in which case we'd have to disable AVX on MacOS, we'd have to make it a universal binary (not sure how rapidly this would get done), or someone changes the workflow to build an aarch64 binary as well. 

I imagine the short term solution (and the one they'll likely end up choosing) is option one, but if you're handy with Macs, I would urge you to try your hand at solution 2 or 3 and open a PR.

**Comment by Macdu** [comment]
Indeed, my bad. I didn't know Rosetta did not support the AVX instruction set, I will revert this change for Mac in the next build.

**Comment by shinra-electric** [comment]
The revert fixed it. The new releases work fine. 👍🏼

**Comment by udance4ever** [comment]
@Macdu would you mind adding a tag to the commit that represents the last known working build on macOS? I’d like to give a hand building it from source.

and if there’s another reason why the macOS CI build is broken, please feel free to fill me in.

**Comment by Macdu** [comment]
> @Macdu would you mind adding a tag to the commit that represents the last known working build on macOS? I’d like to give a hand building it from source.
> 
> and if there’s another reason why the macOS CI build is broken, please feel free to fill me in.
> 
> (and for the record, AVX support **is** possible in macOS - a few of us had [Xenia running in the Sequoia beta](https://appleinsider.com/inside/macos-sequoia/tips/how-to-run-xbox-360-games-on-macos-sequoia) but Xenia broke for me in the GA release (but clearly [Crossover has access to it](https://www.codeweavers.com/support/forums/general/?t=40;msg=309453))
> 
> (I am successful getting Vita3K built in Asahi Linux (Fedora 40) - still testing it out, separate discussion but thought I’d mention this is how I’m moving forward on Apple Silicon at the moment)

I mean, there is a reason this issue is marked as completed. Enabling AVX for the Vita3K build was reverted after many people complained (AVX is still being used if the CPU supports it by the JIT and the hasher). And as far as I'm aware, the MacOS CI works fine and the build runs fine too (I have no feedback concerning Asahi Linux, but that's another issue).
