### ISSUE TITLE
vita3k clashing during the game start

### ISSUE THREAD

**Issue by lucasmz1** [Vita3K/Vita3K#2456]
PC configuation: i5 2400
gtx 1060
ssd 240 gb kingston

16 gb of ram

os: majaro Linux

[vita3k.log](https://github.com/Vita3K/Vita3K/files/11101464/vita3k.log)

**Comment by ArbestRi** [comment]
Ancient CPU, try again with a better CPU.

**Comment by CoffeeBrewer64** [comment]
it has nothing to do with the CPU, it's capable of using vita3k.
