### ISSUE TITLE
[Feature Request] Ability to preview translated shaders as pseudo HLSL

### ISSUE THREAD

**Issue by Fallenleader** [Vita3K/Vita3K#2474]
With the current automatic conversion in place, it should be possible in theory to generate a sort of shader debugging solution to step through the shader assembly and get an understanding of what the developers did.

As the Vita supports GLES2 spec, it is definitely possible to craft some interesting solutions, many of which are indeed a thing on Vita. Being able to step through this would definitely aid in trying to debug current problems in the emulation, as well as picking up tricks that would either be guarded secrets in industry or niche and creative usage of shaders that are potentially a one off type of solution.

**Comment by TheSnowfield** [comment]
https://github.com/Rinnegatamante/yoyoloader_vita/blob/6cd48a9734e3877a3df21ec4f6507e9f140cb71c/loader/glsl2cg.c
this stuff might you're looking for, first I admit it has a really bad smell) :laugh:

**Comment by Macdu** [comment]
Hello, you are describing exactly what Renderdoc (https://renderdoc.org/) is doing. I used it a lot when debugging rendering issues and it allows anyone to see the textures and geometry associated with each draw, to see the decompiled GLSL (or HLSL, you just have to configure it) shaders being executed.
You can modify any shader and see directly the result and even with Vulkan debug step by step a shader.

An external tool does this far better that what could be implemented in Vita3K.

As a side note, Renderdoc is not the only tool to do this (but it is GPU agnostic and open source), for exemple you can also use Nvidia Nsight if you have a Nvidia GPU. 

Also Vita3K generated shaders are a bit.. verbose to say the least.
