### ISSUE TITLE
Vita3k updater tails with paths that contain spaces

### ISSUE THREAD

**Issue by kotenok2000** [Vita3K/Vita3K#2476]
It fails with
 [02:10:59.894] |I| [gui::download_update::<lambda_1>::operator ()]: Attempting to download and extract the latest Vita3K version 3092 in progress...
'E:/games/playstation' is not recognized as an internal or external command,
operable program or batch file.
File path is "E:\games\playstation vita"

**Comment by Zangetsu38** [comment]
Is on what os ?

**Comment by kotenok2000** [comment]
Windows 11 22h2

**Comment by Zangetsu38** [comment]
OK, i look later

**Comment by kotenok2000** [comment]
It happens when i initiate update from 3091 to 3092

**Comment by Zangetsu38** [comment]
No relate this version, i have changed code for exécut script, but i have forget one thinks

**Comment by Zangetsu38** [comment]
is normally fixed in last master
