### ISSUE TITLE
Rear touch screen?

### ISSUE THREAD

**Issue by OspreyWarrior** [Vita3K/Vita3K#2480]
Some games require use of the rear touch screen. Is there a way to use this on the emulator? If so, how?

If so, is there also a way to use both the front and back touch screen simultaneously? Some games require it.

How about 2-finger gestures? Are those possible?

I would have asked on the discord, but every link I can find says that the invite is invalid, so you might need to put up new links.

**Comment by Zangetsu38** [comment]
discord link is valid

**Comment by nn9dev** [comment]
Left click for front touch, right click for rear touch. You can use them in tandem, but obviously only as the mouse pointer will allow. Currently, there's no 2-finger gestures as far as I'm aware.

The Discord links on both the site and the GitHub are valid.
