### ISSUE TITLE
Crash when playing any game

### ISSUE THREAD

**Issue by PLAYERZIN** [Vita3K/Vita3K#2495]
I was trying to play Undertale through this app, when I finished doing things, like configuring the firmware and such, when I went to enter the game, only the text "undertale" appeared and it crashed out of nowhere

**Comment by Zangetsu38** [comment]
is on android .?

**Comment by PLAYERZIN** [comment]
> 
yes

**Comment by Zangetsu38** [comment]
So is android issue,;; is probably relate memory mapping, try disable it
