### ISSUE TITLE
Yellow screen on ridge racer

### ISSUE THREAD

**Issue by RACING12** [Vita3K/Vita3K#2512]
![vita3k](https://user-images.githubusercontent.com/95551348/233719498-38f683d6-3406-4b66-811b-47284f194d6f.png)
hi, im having troubles with ridge racer and the e3 interactive demo, the game sounds works but a yellow screen appears, the graphic render i use is vulkan

**Comment by GamingDucking** [comment]
i am pretty sure that the Vulkan render is working now since it is stubbed for now.

**Comment by Zangetsu38** [comment]
> i am pretty sure that the Vulkan render is working now since it is stubbed for now.

yes, i have stubed it, normally shound be fine
