### ISSUE TITLE
Vita3K quit unexpectedly

### ISSUE THREAD

**Issue by yousirkname** [Vita3K/Vita3K#2553]
Trying to launch Vita3K for the first time, but it keeps giving me the message that it quit unexpectedly. The log file gives me this at the end:
|C| [operator()]: Unhandled C++ exception. vk::Device::createImageView: ErrorFeatureNotPresent
My computer may just be unsupported so here's the system info:
OS: MacOS 12.6.5
CPU: Intel(R) Core(TM) i5-5257U CPU @ 2.70GHz
GPU: Intel Iris Graphics 6100 1536 MB
Memory: 8 GB 1867 MHz DDR3
Using build 3135

I'm new to this so sorry and let me know if there isn't enough info

**Comment by nn9dev** [comment]
Unfortunately, Intel Iris Graphics 6100 does not support Vulkan, which is required by Vita3K on MacOS. 

https://www.intel.com/content/www/us/en/support/articles/000005524/graphics.html

**Comment by Macdu** [comment]
> Unfortunately, Intel Iris Graphics 6100 does not support Vulkan, which is required by Vita3K on MacOS. 
> 
> https://www.intel.com/content/www/us/en/support/articles/000005524/graphics.html

No GPU on MacOS supports Vulkan anyway. MoltenVK is used to translate Vulkan calls to Metal, so that's not the issue. 
But that's kinda hard to say which feature is missing given only this error.

**Comment by nn9dev** [comment]
absolutely no idea why I didn't simply use my noggin for two seconds my bad

**Comment by yousirkname** [comment]
> No GPU on MacOS supports Vulkan anyway. MoltenVK is used to translate Vulkan calls to Metal, so that's not the issue. But that's kinda hard to say which feature is missing given only this error.

That's the only error it gives me in the log file, but opening the executable in Terminal shows me this:

[mvk-error] VK_ERROR_FEATURE_NOT_PRESENT: The value of vkCreateImageView(VkImageViewCreateInfo::components) (VK_COMPONENT_SWIZZLE_ONE, VK_COMPONENT_SWIZZLE_ONE, VK_COMPONENT_SWIZZLE_ONE, VK_COMPONENT_SWIZZLE_R), when applied to a VkImageView, requires full component swizzling to be enabled both at the time when the VkImageView is created and at the time any pipeline that uses that VkImageView is compiled. Full component swizzling can be enabled via the MVKConfiguration::fullImageViewSwizzle config parameter or MVK_CONFIG_FULL_IMAGE_VIEW_SWIZZLE environment variable.
|C| [operator()]: Unhandled C++ exception. vk::Device::createImageView: ErrorFeatureNotPresent
libc++abi: terminating with uncaught exception of type vk::FeatureNotPresentError: vk::Device::createImageView: ErrorFeatureNotPresent

**Comment by Macdu** [comment]
Thank you for this much better error message, I should be able to fix that.

**Comment by Macdu** [comment]
Thank you for this much better error message, I should be able to fix that.

**Comment by Macdu** [comment]
Can you test the build from #2555 and tell me if it solves the issue?

**Comment by yousirkname** [comment]
Sorry, but how do I access the installation dmg from the build you uploaded? Is there a different way to download the build?

**Comment by yousirkname** [comment]
It gave me the same errors as before sadly

**Comment by Macdu** [comment]
Can you run the new build I made (still in #2555) and send me the log you get please?

**Comment by yousirkname** [comment]
[vita3k.log](https://github.com/Vita3K/Vita3K/files/11412867/vita3k.log)
I'm guessing you meant the log file but let me know if you want what I get from Terminal too

**Comment by Macdu** [comment]
Thank you for the log, I updated the pull request. Could you test the new build? I'm hopeful it should now fix this issue.

**Comment by yousirkname** [comment]
Unless I'm on the wrong page, it looks like the dmg artifact failed to be created

Annotations
1 error
[build (macos-latest, Release)](https://github.com/Macdu/Vita3K/actions/runs/4914114342/jobs/8775053285#step:15:29)
Process completed with exit code 64.

**Comment by Macdu** [comment]
That's weird that this build did not succeed, but I was thinking about this build: https://github.com/Vita3K/Vita3K/actions/runs/4914114822?pr=2555 (the same but ran on Vita3K CI)

**Comment by yousirkname** [comment]
It opened! Thanks for the help

**Comment by Macdu** [comment]
You're welcome, thanks for testing.

**Comment by shinra-electric** [comment]
Looks like this issue can be closed...?

**Comment by ku16610** [comment]
Latest Build fails with same problem.

On m4 mini Mac


➜  MacOS ./Vita3K
[10:35:32.110] |I| [init_config]: backend-renderer: Vulkan
[10:35:32.110] |I| [init_config]: log-level: trace
[10:35:32.592] |I| [main]: Vita3K v0.2.0 3808-f787cf09
[10:35:32.592] |I| [main]: OS: 24.6.0
[10:35:32.593] |I| [main]: CPU: Apple M4 | 10 Threads | 2400000 GHz
[10:35:32.593] |I| [main]: Available ram memory: 16384 MiB
[10:35:32.593] |I| [init]: Base path: "/Applications/Vita3K.app/Contents/Resources/"
[10:35:32.593] |I| [init]: User pref path: "/Volumes/HomeZ/Users/BLAH/Library/Application Support/Vita3K/Vita3K/fs"
[mvk-error] VK_ERROR_EXTENSION_NOT_PRESENT: Vulkan extension VK_KHR_portability_enumeration is not supported.
[mvk-info] MoltenVK version 1.2.11, supporting Vulkan version 1.2.296.
	The following 110 Vulkan extensions are supported:
	VK_KHR_16bit_storage v1
	VK_KHR_8bit_storage v1
	VK_KHR_bind_memory2 v1
	VK_KHR_buffer_device_address v1
	VK_KHR_calibrated_timestamps v1
	VK_KHR_copy_commands2 v1
	VK_KHR_create_renderpass2 v1
	VK_KHR_dedicated_allocation v3
	VK_KHR_deferred_host_operations v4
	VK_KHR_depth_stencil_resolve v1
	VK_KHR_descriptor_update_template v1
	VK_KHR_device_group v4
	VK_KHR_device_group_creation v1
	VK_KHR_driver_properties v1
	VK_KHR_dynamic_rendering v1
	VK_KHR_external_fence v1
	VK_KHR_external_fence_capabilities v1
	VK_KHR_external_memory v1
	VK_KHR_external_memory_capabilities v1
	VK_KHR_external_semaphore v1
	VK_KHR_external_semaphore_capabilities v1
	VK_KHR_fragment_shader_barycentric v1
	VK_KHR_format_feature_flags2 v2
	VK_KHR_get_memory_requirements2 v1
	VK_KHR_get_physical_device_properties2 v2
	VK_KHR_get_surface_capabilities2 v1
	VK_KHR_imageless_framebuffer v1
	VK_KHR_image_format_list v1
	VK_KHR_incremental_present v2
	VK_KHR_maintenance1 v2
	VK_KHR_maintenance2 v1
	VK_KHR_maintenance3 v1
	VK_KHR_map_memory2 v1
	VK_KHR_multiview v1
	VK_KHR_portability_subset v1
	VK_KHR_push_descriptor v2
	VK_KHR_relaxed_block_layout v1
	VK_KHR_sampler_mirror_clamp_to_edge v3
	VK_KHR_sampler_ycbcr_conversion v14
	VK_KHR_separate_depth_stencil_layouts v1
	VK_KHR_shader_draw_parameters v1
	VK_KHR_shader_float_controls v4
	VK_KHR_shader_float16_int8 v1
	VK_KHR_shader_integer_dot_product v1
	VK_KHR_shader_non_semantic_info v1
	VK_KHR_shader_subgroup_extended_types v1
	VK_KHR_spirv_1_4 v1
	VK_KHR_storage_buffer_storage_class v1
	VK_KHR_surface v25
	VK_KHR_swapchain v70
	VK_KHR_swapchain_mutable_format v1
	VK_KHR_synchronization2 v1
	VK_KHR_timeline_semaphore v2
	VK_KHR_uniform_buffer_standard_layout v1
	VK_KHR_variable_pointers v1
	VK_KHR_vertex_attribute_divisor v1
	VK_EXT_4444_formats v1
	VK_EXT_buffer_device_address v2
	VK_EXT_calibrated_timestamps v2
	VK_EXT_debug_marker v4
	VK_EXT_debug_report v10
	VK_EXT_debug_utils v2
	VK_EXT_descriptor_indexing v2
	VK_EXT_extended_dynamic_state v1
	VK_EXT_extended_dynamic_state2 v1
	VK_EXT_extended_dynamic_state3 v2
	VK_EXT_external_memory_host v1
	VK_EXT_fragment_shader_interlock v1
	VK_EXT_hdr_metadata v3
	VK_EXT_headless_surface v1
	VK_EXT_host_image_copy v1
	VK_EXT_host_query_reset v1
	VK_EXT_image_robustness v1
	VK_EXT_inline_uniform_block v1
	VK_EXT_layer_settings v2
	VK_EXT_memory_budget v1
	VK_EXT_metal_objects v2
	VK_EXT_metal_surface v1
	VK_EXT_pipeline_creation_cache_control v3
	VK_EXT_pipeline_creation_feedback v1
	VK_EXT_post_depth_coverage v1
	VK_EXT_private_data v1
	VK_EXT_robustness2 v1
	VK_EXT_sample_locations v1
	VK_EXT_scalar_block_layout v1
	VK_EXT_separate_stencil_usage v1
	VK_EXT_shader_atomic_float v1
	VK_EXT_shader_demote_to_helper_invocation v1
	VK_EXT_shader_stencil_export v1
	VK_EXT_shader_subgroup_ballot v1
	VK_EXT_shader_subgroup_vote v1
	VK_EXT_shader_viewport_index_layer v1
	VK_EXT_subgroup_size_control v2
	VK_EXT_surface_maintenance1 v1
	VK_EXT_swapchain_colorspace v5
	VK_EXT_swapchain_maintenance1 v1
	VK_EXT_texel_buffer_alignment v1
	VK_EXT_texture_compression_astc_hdr v1
	VK_EXT_vertex_attribute_divisor v3
	VK_AMD_gpu_shader_half_float v2
	VK_AMD_negative_viewport_height v1
	VK_AMD_shader_image_load_store_lod v1
	VK_AMD_shader_trinary_minmax v1
	VK_IMG_format_pvrtc v1
	VK_INTEL_shader_integer_functions2 v1
	VK_GOOGLE_display_timing v1
	VK_MVK_macos_surface v3
	VK_MVK_moltenvk v37
	VK_NV_fragment_shader_barycentric v1
	VK_NV_glsl_shader v1
[mvk-info] GPU device:
	model: Apple M4
	type: Integrated
	vendorID: 0x106b
	deviceID: 0xf060209
	pipelineCacheUUID: 1A2A131C-0F06-0209-0000-000100000000
	GPU memory available: 10922 MB
	GPU memory used: 0 MB
	Metal Shading Language 3.1
	supports the following GPU Features:
		GPU Family Metal 3
		GPU Family Apple 9
		GPU Family Mac 2
		Read-Write Texture Tier 2
[mvk-info] Created VkInstance for Vulkan version 1.0.0, as requested by app, with the following 6 Vulkan extensions enabled:
	VK_KHR_device_group_creation v1
	VK_KHR_external_memory_capabilities v1
	VK_KHR_get_physical_device_properties2 v2
	VK_KHR_surface v25
	VK_EXT_layer_settings v2
	VK_EXT_metal_surface v1
[mvk-info] Destroyed VkPhysicalDevice for GPU Apple M4 with 0 MB of GPU memory still allocated.
[mvk-info] Destroying VkInstance for Vulkan version 1.0.0 with 6 Vulkan extensions enabled.
[10:35:32.789] |C| [operator()]: Unhandled C++ exception. vk::createInstance: ErrorExtensionNotPresent
libc++abi: terminating due to uncaught exception of type vk::ExtensionNotPresentError: vk::createInstance: ErrorExtensionNotPresent
[1]    86073 abort      ./Vita3K
