### ISSUE TITLE
Only vertical touch movement is recognized, but not horizontal

### ISSUE THREAD

**Issue by rsn8887** [Vita3K/Vita3K#257]
Tested with Rocksndiamonds v1.1, using Vita3k MacOS nightly from May 17th 2018:
Expected behavior: 
On a real Vita, the mouse pointer can be dragged in all directions with the finger. 
Observed behavior:
On Vita3K the mouse pointer can only be dragged up and down, not left and right. I did this by left-click dragging in the Vita3k window.

**Comment by Rinnegatamante** [comment]
Noticed this too with vitaWolfen launcher. I thought on first it was caused by some mem corruption of vitaGL support but seems it's not.

**Comment by Rinnegatamante** [comment]
@rsn8887 Is this still a bug?

**Comment by rsn8887** [comment]
I don’t know I can’t run latest Vita3k on my MacBook anymore because Vita3k now requires a too high OpenGL version. OpenGL is deprecated and outdated on MacOS.

**Comment by Rinnegatamante** [comment]
vitaWolfen doesn't have this issue anymore so i guess we can consider this solved.

**Comment by petmac** [comment]
> I don’t know I can’t run latest Vita3k on my MacBook anymore because Vita3k now requires a too high OpenGL version. OpenGL is deprecated and outdated on MacOS.

@rsn8887 Have you tried Xcode 9.4.1? I think it’s newer MacOS SDKs that break OpenGL support.
