### ISSUE TITLE
Vita Crash after new update 

### ISSUE THREAD

**Issue by Solreavir** [Vita3K/Vita3K#2588]
so updated to latest version  but when I click on the opened app it fails to go to the home screen and then app closes. Dialogue box says "Exception EXCEPTION ACCESS VIOLATION 0x00005" Also Dialouge box says "Read Address Violation at 0xffffffffffffff"

**Comment by Zangetsu38** [comment]
i have no understund att, all, you have probleme in what moment ?

**Comment by Zangetsu38** [comment]
> the app will open with the clock screen but as soon as I tap the app to open that's when I get the crash and the Error message in the dialouge box.

ok, thx, i have understund why, you using custom image ?

**Comment by Solreavir** [comment]
Yeah. If that's the problem how to resolve ?

**Comment by Zangetsu38** [comment]
is already solved, i open pr.

**Comment by Zangetsu38** [comment]
Is should now fixed on master, can confirm ?
