### ISSUE TITLE
Unhandled C++ exception Error on Vulkan on latests releases

### ISSUE THREAD

**Issue by arcadesfan** [Vita3K/Vita3K#2604]
When I start Vita3k with Vulkan backend, the emulator hangs with the following error:

Unhandled C++ exception. vkPhysicalDevicecreateDevice ErrorFeatureNotPresent

This error started to appear on latest nightly releases, it didn´t appear in previous releases. I think it started in 0.1.8.3171 or so.

When I switch to OpenGL instead, the problem dissapears and the emulator works fine again.

My specs are Pentium E5700 ( dual core ) - NVidia GT640 GPU with 1 GB Vram - Memory: 8 GB Ram

Is there something I am missing to install, or is it a hardware related error ?

Log file:

[vita3k.log](https://github.com/Vita3K/Vita3K/files/11559086/vita3k.log)

**Comment by Macdu** [comment]
This issue was fixed 30 minutes ago, according to the log you are not using the latest version

**Comment by arcadesfan** [comment]
Thanks for your prompt response. 
I notice now that the error disappears after you set a game with a "custom configuration" to Vulkan, as the emulator starts with OpenGL by default.
