### ISSUE TITLE
the problem with new build

### ISSUE THREAD

**Issue by kirillsuxoi** [Vita3K/Vita3K#261]
when I try to start a new build, an error comes out  help me please thank you
[vita3k.log](https://github.com/Vita3K/Vita3K/files/2027784/vita3k.log)

![default](https://user-images.githubusercontent.com/39531012/40378793-3155fcbe-5dfd-11e8-9b50-375b03ffc79a.png)

**Comment by GusAndrianos** [comment]
Just to confirm, those are Windows 7, right?

**Comment by VelocityRa** [comment]
Also, can you share your specs? GPU, CPU?

**Comment by kirillsuxoi** [comment]
GusAndrianos  yes this is win7

**Comment by kirillsuxoi** [comment]
VelocityRa, CPU DualCore Intel Pentium E2200, 2200 MHz (11 x 200) GPU nVIDIA GeForce 9400 GT 512 mb

**Comment by mailwl** [comment]
looks like 9400 supports only 3.3 opengl, minimum required 4.1

**Comment by kirillsuxoi** [comment]
mailwl thank you
