### ISSUE TITLE
PSM Support ? 

### ISSUE THREAD

**Issue by SilicaAndPina** [Vita3K/Vita3K#262]
Wonder if theres any plans to have PSM games be emulated (obv it cant right now. but in the future ? )

**Comment by VelocityRa** [comment]
Yes, PSM games are Vita games, and we're emulating the Vita, thus they will hopefully be playable at some point.
You can ask questions like that on our Discord, not the issue tracker :)

**Comment by SilicaAndPina** [comment]
PSM games are not vita games!

thats like saying because the PSVita can run PSP games, you expect to get PSP games to run under vita3k.

**Comment by VelocityRa** [comment]
Yeah I suppose.

Still it'd be a lot weirder for a Vita emulator to not play PSM games, than PSP games ¯\_(ツ)_/¯

**Comment by SilicaAndPina** [comment]
i guess if you fully emulated the runtime, then it would work..
but thats acturally quite difficult as the runtime doesnt have a bubble i think its like a background process ?, and it runs whatever psm game you wanna run ?

**Comment by VelocityRa** [comment]
I'm not very familiar with PSM games, but I doubt we'll have to HLE the runtime. We could probably LLE it.
That's not to say it won't be extra work for PSM games though, iirc there are OS modules only those use.
