### ISSUE TITLE
UPDATE BUG in my PC

### ISSUE THREAD

**Issue by butzer0** [Vita3K/Vita3K#2638]
I open vita 3k it got update
After finish downloading it closed and won't restart
After i reopen same thing happen 

My current version 3152 had trouble to update to version 3203

![16863341503043192227876397725132](https://github.com/Vita3K/Vita3K/assets/136115691/f6bf169e-1ef1-4f7a-8c33-51d77591158e)
![16863341988928545215154937534419](https://github.com/Vita3K/Vita3K/assets/136115691/592f5a24-3b80-4f5b-b346-d723da4e1da1)

**Comment by Zangetsu38** [comment]
download and install manualy last build
just extract archive and replace all.

**Comment by butzer0** [comment]
Thanks
