### ISSUE TITLE
Segmentation fault on Linux

### ISSUE THREAD

**Issue by Sunderland93** [Vita3K/Vita3K#264]
`Starting program: /home/sunderland93/vita3k-0.1.0~git20180528/build/bin/Vita3K 
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
[05:40:36.489] |I| [main]:  Vita3K v0.1 Development version
[New Thread 0x7ffff7fb2700 (LWP 5682)]

Thread 1 "Vita3K" received signal SIGSEGV, Segmentation fault.
DisplayState::set_dims (border_height=34, border_width=16, image_height=544, image_width=960, 
    this=0x7fffffffda78)
    at /home/sunderland93/vita3k-0.1.0~git20180528/src/emulator/host/include/host/state.h:68
68	        window_size = image_size + border_size;`

Ubuntu 18.04, GCC 7.3, Intel HD Graphics (OpenGL 2.1)

**Comment by VelocityRa** [comment]
It's [here](https://github.com/Vita3K/Vita3K/blob/master/src/emulator/host/include/host/state.h#L68) so maybe this is because of @petmac's

https://github.com/Vita3K/Vita3K/commit/de9a746c193e7c0d4b5d1be3a956d7a27a91a3b8#diff-6595b96822058ce2f49688219b402748R49

**Comment by mrcmunir** [comment]
@VelocityRa  But now Required Opengl 4.1 Right? And @Sunderland93 Report this IGPU only support Opengl 2.1

**Comment by VelocityRa** [comment]
Hm that's true, even though the error seems unrelated.

@Sunderland93 Can you submit a log (`vita3k.log`)?

**Comment by petmac** [comment]
> It's here so maybe this is because of @petmac's
> de9a746#diff-6595b96822058ce2f49688219b402748R49

Not because of, but I think that should fix it. @Sunderland93 is the bug still happening?

**Comment by VelocityRa** [comment]
Two months without a reply, closing this, can reopen if necessary.
