### ISSUE TITLE
Vita3k Quit After First Setup, Error [Unhandled C++ exception. invalid stoi argument]

### ISSUE THREAD

**Issue by reyzafany** [Vita3K/Vita3K#2650]
Trying to launch Vita3K for the first time, but it keeps giving me the message that it quit unexpectedly. The log file gives me this at the end:
|C| [logging::init::<lambda_2>::operator ()]: Unhandled C++ exception. invalid stoi argument

Here's the system info:
OS: WIN 11 Pro 64bit Build 22621
CPU: AMD Ryzen 7 3800XT 8 Core Processor (16-CPUs) ~3.9GHz
GPU: AMD Radeon (TM) R9 Fury X
Memory: 32GB DDR4 3200MHz
Vita3k build:  v0.1.8 3208-8d345f00

[vita3k.log](https://github.com/Vita3K/Vita3K/files/11753086/vita3k.log)

**Comment by Zangetsu38** [comment]
is should fixed in last master
