### ISSUE TITLE
[PCSG00494] Super Robot Taisen Z3 Tengoku - Can't quicksave

### ISSUE THREAD

**Issue by kaliolio** [Vita3K/Vita3K#2693]
After updating to build 3237 I can't quicksave anymore, though normal saving still works.
Log says access violation but it has permission to write.
[vita3k.log](https://github.com/Vita3K/Vita3K/files/11889198/vita3k.log)

**Comment by Zangetsu38** [comment]
manual save works ?

**Comment by kaliolio** [comment]
> manual save works ?

It's a tactical game, so there are two kind of saves. One you can do inbetween stages and one you can do in the middle of a turn. For some reason the emulator always crashed whenever I do the latter after the update.

The update log says something about save files so I figured it might be related to that.

**Comment by Zangetsu38** [comment]
@kaliolio is yoçàu can confirm all is fine now with this pr ?
https://github.com/Vita3K/Vita3K/pull/2694

**Comment by kaliolio** [comment]
@Zangetsu38 Yep, it works fine now
