### ISSUE TITLE
Persona Dancing titles - Retry doesn't restart dance/chart

### ISSUE THREAD

**Issue by ActualMandM** [Vita3K/Vita3K#2705]
Affected Titles:
- https://github.com/Vita3K/compatibility/issues/175
- https://github.com/Vita3K/compatibility/issues/316
- https://github.com/Vita3K/compatibility/issues/317

Hitting Retry in the pause menu won't restart the dance/chart. Depending on how far you are into the song, this will instantly fail you.

https://github.com/Vita3K/Vita3K/assets/15317421/81680dbf-f217-4346-adb6-5b83b7766685

This also makes it possible to fail perfect play.

https://github.com/Vita3K/Vita3K/assets/15317421/e38724ee-726b-451f-8ac6-332e79de51ae

**Comment by poudink** [comment]
I've had the same issue in P3D and would like to add a likely related problem were charts occasionally start slightly out of sync. This seems to be random and can happen when starting a chart or pressing retry after completing a chart. Notes will usually start appearing a couple of seconds too early, before the circles/targets/button indicator thingamajigs appear at the screen edges and will continue to appear out of sync with the song unless you give up and restart.

**Comment by G1fan** [comment]
This appears to have been fixed sometime in the last couple of months. I previously experienced the same behaviour of songs not restarting but now they are working as expected for me.

**Comment by ActualMandM** [comment]
Can confirm it has been fixed. Closing.

https://github.com/Vita3K/Vita3K/assets/15317421/5f1b56a9-f226-4271-81e3-855e1ae41d22
