### ISSUE TITLE
Per game settings not working

### ISSUE THREAD

**Issue by CorpseSlayer** [Vita3K/Vita3K#2710]
I have try to make per game config for some of the games but this option seems not to be working at all
when you select to either use Vulkan or OpenGL it overall changes the main settings it does not makes a config
file for each game so this option needs a fix.

Windows 11
9700K Intel I7
Nvidia 2060 RTX

Vita3k Version: 
Vita3k v. 0.1.8 3250-6342c205
![image_2023-07-03_230347422](https://github.com/Vita3K/Vita3K/assets/126618918/16df8634-e2cc-4986-a93b-cc377ddc234f)

**Comment by Zangetsu38** [comment]
it works, but some option no have custom, and using genaral
