### ISSUE TITLE
[SUGGESTION] Option to disable compatibility update notice on startup

### ISSUE THREAD

**Issue by ryukizoa** [Vita3K/Vita3K#2712]
The compatibility update notice is really annoying, especially if you open Vita3K without Internet connection you'll get an error notice instead.
Could we have an option in settings (under emulator maybe?) to choose to disable it, or a "Do not show again" tickbox which some apps have.

**Comment by 64ghost** [comment]
In  file **config.yml** change option

display-info-message: false
show-welcome: false

**Comment by Croden1999** [comment]
U can find this option on settings dialog of main menubar, and uncheck it. `Configuration` -> `Settings` -> `GUI` -> `Display Info Message`

**Comment by Zangetsu38** [comment]
> The compatibility update notice is really annoying, especially if you open Vita3K without Internet connection you'll get an error notice instead. Could we have an option in settings (under emulator maybe?) to choose to disable it, or a "Do not show again" tickbox which some apps have.

Option already exist
