### ISSUE TITLE
Feature Request: Gyro support

### ISSUE THREAD

**Issue by Krules02** [Vita3K/Vita3K#2715]
The dual shock 4, dual sense, switch pro, steam controller, steam deck, and phones all have gyro. It would be nice if we could use those for games that utilize gyro. I think sdl has gyro support? Or maybe dsu server like what I've seen some other emulators use?

**Comment by Zangetsu38** [comment]
curent pr already exist for this
#2628

**Comment by Krules02** [comment]
Oh ok, I did search gyro and I didn't find anything.. I'll close this then.
