### ISSUE TITLE
Iconoclast

### ISSUE THREAD

**Issue by ShalokShalom** [Vita3K/Vita3K#2730]
Hi there 👋🏻

Lovely people, your awesome emulator crashes, as soon as I select 'new game' on the homescreen. 

I am using the most current git build at the time, along with fully up to date firmware from Sony. 

How can I dumb logs for you?

**Comment by im-tem** [comment]
Log is created in the same folder as the Vita3K executable under the name`vita3k.log`

Report the issue in the https://github.com/Vita3K/compatibility/ repo, see how it's done for other games

**Comment by ShalokShalom** [comment]
Thanks
