### ISSUE TITLE
Vulkan rendering ErrorInvalidOpaqueCaptureAddress

### ISSUE THREAD

**Issue by jan21952** [Vita3K/Vita3K#2748]
I use old v0.1.5.2786 is OK,but use after v0.1.6.3000 is error.

Error:
[22:01:09.442] |C| [logging::init::<lambda_2>::operator ()]: Unhandled C++ exception. vk::Device::allocateMemory: ErrorInvalidOpaqueCaptureAddress

how i to do ?

**Comment by Kagewani123** [comment]
Have you ever found a fix?

**Comment by jan21952** [comment]
no fix , now,ver 3608 , vulkan rendering still not working.
some game only use vulkan rendering ,i still use ver 3028.

    在 2024年5月22日 星期三 上午10:40:58 [GMT+8]， ***@***.***> 寫道：  
 
 


Have you ever found a fix?

**Comment by scribam** [comment]
Check https://github.com/Vita3K/Vita3K/issues/3300#issuecomment-2144017432 about the `vk::Device::allocateMemory: ErrorInvalidOpaqueCaptureAddress` error
