### ISSUE TITLE
Deprecated errors & externals

### ISSUE THREAD

**Issue by johnny-mac** [Vita3K/Vita3K#275]
Hello, I am curious how I can build vita3k with the system's yaml-cpp, capstone, and a few other things, is this possible? If so, what cmake flags do I use to disable the yaml-cpp, capstone, etc that come in the externals folder? Preferably I'd like to get it to build against the system's stuff - or at least some of it.

I am getting a lot of deprecated errors during the build that I figured you might want to see, I am running Artix Linux (Arch OpenRC) and Void Linux MUSL... This output is from Artix, if I run into the same problems on Void MUSL I will let you know.

Build output:
https://pastebin.com/WmyYQGfr

**Comment by petmac** [comment]
Personally, I don't know.

I would like to get to the point where we're handling Linux dependencies the right way, but I don't have the expertise or time to do it myself.

**Comment by bentokun** [comment]
Generally, the project is written in C++ 14, but recently we make a change to C++ 17, result in other dependencies (external) emits warning (not errors), of deprecated function. Visual Studio also emits these things, not only GCC. So you have to live with it, sorry, as long as it build fine.

**Comment by johnny-mac** [comment]
What's the command to start Vita3K? I don't see any icon for it after compiling it from source, make install works but it appears there is nothing in the /usr/bin or /bin named vita or Vita or Vita3K / vita3k / etc.
Should I just copy over the Vita3K file in the bin folder perhaps?

**Comment by wfscans** [comment]
Vita3k <game>

**Comment by VelocityRa** [comment]
Yeah, just supply the path to the game as the first and only argument.

**Comment by johnny-mac** [comment]
"Vita3k game" does not launch it, nor does Vita3k. Doing make install doesn't seem to install it to the system, it installs it to a 'bin' folder & then I have to copy the Vita3K executable into /usr/bin/

**Comment by VelocityRa** [comment]
There's is no installation. You just run it as `./whatever/vita3k path/to/game.vpk`, from the source directory.
idk what `whatever` is, it's linux-specific.

Anyway this is turning into support, come into Discord to ask such things, not the GitHub issue tracker.

**Comment by VelocityRa** [comment]
Installing isn't supported on Windows, so not sure why it should be on Linux.

Pull requests welcome, of course, but I don't consider this to be an issue that should be here.
