### ISSUE TITLE
Game error。

### ISSUE THREAD

**Issue by tzyayq** [Vita3K/Vita3K#2751]
Legend of Heroes:Trails in the Sky 3rd(SORA NO KISEKI the 3rd)Chapter 6 Game error。

**Comment by artuuuuuuuz** [comment]
Same here.
when trying to enter the pillar it just crashes and has this error.
![image](https://github.com/Vita3K/Vita3K/assets/141550173/f5b3a7ff-d369-42d8-ab01-c9133dbfd00f)

**Comment by johnwhite5116** [comment]
https://github.com/Vita3K/compatibility/issues/1048#issuecomment-1698321411

Still same issue.

I've finished FC and SC without any major issue.

It's a shame that I can't finish whole Trails in the Sky series on Vita3K.

**Comment by Zangetsu38** [comment]
Using compat report
