### ISSUE TITLE
SDL_AudioStream

### ISSUE THREAD

**Issue by johnny-mac** [Vita3K/Vita3K#276]
Hi again, I've got some funny errors going on when trying to compile vita3k on Devuan i686. 

Does this emulator support 32-bit?

Here is the build errors:
https://pastebin.com/cbXSSQyW

**Comment by petmac** [comment]
The SDL error is because v2.0.7 or later is required, you probably have an earlier version.

32-bit is not supported, because the emulator reserves 4 gigs of address space, which is greater than your available physical memory limit.

**Comment by johnny-mac** [comment]
But doesn't PAE enable 4+ GB of RAM? 

I am getting the same errors with Devuan 64-bit too, so I guess its the SDL packages doing this.

**Comment by petmac** [comment]
Maybe it's worth someone trying 32-bit, I've never tried it, just assumed it wouldn't work.

I'm going to close this anyway, thanks for reporting.
