### ISSUE TITLE
Is there any way to install a standard Vita launcher?

### ISSUE THREAD

**Issue by creeper-0910** [Vita3K/Vita3K#2766]
I like the official Vita launcher and would like to install it, is that possible?

**Comment by Zangetsu38** [comment]
no sur understund your ask ?

**Comment by creeper-0910** [comment]
Sorry, I couldn't think of a good analogy.
Here it is.
![image](https://github.com/Vita3K/Vita3K/assets/56744841/a7382f72-d67a-4ca0-a597-b0368eaf6b95)

**Comment by ArbestRiAgain** [comment]
> Sorry, I couldn't think of a good analogy. This is what I wanted to say.↓ ![image](https://user-images.githubusercontent.com/56744841/255300097-a7382f72-d67a-4ca0-a597-b0368eaf6b95.png)

While Vita3K can partially run the native Vita shell, it doesn't go to the LiveArea yet

**Comment by Zangetsu38** [comment]
> > Sorry, I couldn't think of a good analogy. This is what I wanted to say.↓ ![image](https://user-images.githubusercontent.com/56744841/255300097-a7382f72-d67a-4ca0-a597-b0368eaf6b95.png)
> 
> While Vita3K can partially run the native Vita shell, it doesn't go to the LiveArea yet

that is not live area, is home,
