### ISSUE TITLE
need help

### ISSUE THREAD

**Issue by suhoparoff2017** [Vita3K/Vita3K#28]
anyone can explain
in more detail about how to build Vita3K on windows I do everything on the manual and  I get only an empty folder build-windows
thank you in advance

**Comment by mailwl** [comment]
provide cmake log

**Comment by Kumoashi** [comment]
I get the same problem. From what I can tell, the gen.bat file never runs CMake, so the build-windows folder remains empty. I have tried to run the CMake step manually, but I still couldn't get a build of Vita3K to compile.

**Comment by Ghabry** [comment]
I had to change "cmake" to an absolute path "c:\Program Files\CMake\bin\cmake.exe" because cmake wasn't in my PATH for some reason. Otherwise the script worked fine.

**Comment by cybertronicgames** [comment]
@suhoparoff2017 
I used Git to clone the submodules using this link here "https://github.com/Vita3K/Vita3K.git",
ran the gen.bat file "I have CMake installed to path", ran the Vita3K.sln file, selected Release, Emulator & build in Visual Studios.

I've done this before & had no problems.

![screenshot 143 2](https://user-images.githubusercontent.com/14711758/35601368-3d8dbda8-05f8-11e8-9d15-9e9416fa2aa5.jpg)

**Comment by cybertronicgames** [comment]
I used Git GUI "http://gitforwindows.org" to clone the submodules at this address "https://github.com/Vita3K/Vita3K.git", installed CMake when installed" CMake v3.10.01 at https://cmake.org/download/ , installed Visual Studios 2017 Community at  https://www.visualstudio.com/downloads/ "Made sure to select C++ support in the installer".

1. Open Git GUI.exe, select "clone existing repository", paste "https://github.com/Vita3K/Vita3K.git" in source location, add the location of target directory "C:/Users/Owner/Vita" & check marked "recursively clone submodules" & clicked the "clone" option. Waited until it's finished.

![screenshot 161](https://user-images.githubusercontent.com/14711758/35779427-61ff9e34-0992-11e8-98bc-edd76a89666f.jpg)


2. Opened the location of target directory "C:/Users/Owner/Vita" & Ran "gen.bat" file. Waited until that was finished.

![screenshot 159](https://user-images.githubusercontent.com/14711758/35779430-6a69b1ea-0992-11e8-8784-8b79f1a72985.jpg)

3. Opened "C:\Users\Owner\Vita\build-windows" location & ran "Vita3K.sln"

![screenshot 162](https://user-images.githubusercontent.com/14711758/35779455-e317c456-0992-11e8-9c19-2b5560c12d1d.jpg)

4.When all the files loaded, Visual Studios says ready at the bottom. I set it to "release",

![screenshot 163](https://user-images.githubusercontent.com/14711758/35779489-7cf965f2-0993-11e8-9da0-3bd629128c66.jpg)

then right clicked "emulator" & "set as startup project" then selected build.

![screenshot 164](https://user-images.githubusercontent.com/14711758/35779531-02e9d7be-0994-11e8-9645-a1e7125eddd0.jpg)

Waited until it was finished & had no errors.
I really don't know how to do it on MacOS.

**Comment by VelocityRa** [comment]
@suhoparoff2017 Why was this reopened?
@petmac I think the instructions above should go to the Wiki and the README should reference them as a more detailed guide. This should prevent future issues like this one.

**Comment by cybertronicgames** [comment]
No need, they can get builds from appveyor & stop building them themselves. Unless, they're devs. & they already know how to build.

**Comment by cybertronicgames** [comment]
@VelocityRa I quit building it myself & just use appveyors builds now. Since, I'm not coding the emulator.

**Comment by Kumoashi** [comment]
The Citra team had a problem in the past where their automated builds where failing. This forced people to either wait for the problem to be fixed, which ended up taking a month or more, or compile the latest code themselves.
I was one of the people who opted to compile the latest code instead of waiting. At the time, I had never done that before, so it took some time for me to learn how to do it right.
Since you never know what problems you may run into, it might be a good idea to make this option more user friendly, just in case someone ever needs it, or wants it, for some reason in the future.

**Comment by Lashana00** [comment]
I did everything like in the tutorial, but still got the same issue with "Host initialisation".

**Comment by VelocityRa** [comment]
@Lashana00 Hi, GitHub isn't for support. Come to our Discord server and people will help you there.
