### ISSUE TITLE
Firmware problem in vita3k android 

### ISSUE THREAD

**Issue by Kmracer7** [Vita3K/Vita3K#2820]
phone - redmi note 8 pro
problem - when i install firmware the firmware installation dialogue box does not show help i cant install firmware

**Comment by Croden1999** [comment]
for android version issues should report here https://github.com/Vita3K/Vita3K-Android/issues/new

**Comment by Genildopaladino** [comment]
Redmi note 8 pro não instala firmware PSV nem PSP , alguém me ajuda,!!! Desde sobre pós app mesmo apagando arquivos das pastas ele não instala correto.
