### ISSUE TITLE
Vita3k 2645 Cannot create OpenGL context

### ISSUE THREAD

**Issue by perahai** [Vita3K/Vita3K#2835]
<img width="924" alt="Screenshot 2023-08-01 at 08 12 00" src="https://github.com/Vita3K/Vita3K/assets/141001968/3ec22fea-f422-45ff-a10c-c1ad3c6a2085">
Running 2645 version on Mac OS, but my mac does not support open gl, so the initialization failed to load.

**Comment by Macdu** [comment]
Don't ask for help when using a one year old build.
