### ISSUE TITLE
Dungeon Travelers 2 PCSE00693

### ISSUE THREAD

**Issue by TheSargoner** [Vita3K/Vita3K#2837]
Game crashes randomly, whether in menus at base or 10 minutes into adventuring.

Vita3k Android, Release 7
Samsung Galaxy S21 Ultra 5g

[vita3k.log](https://github.com/Vita3K/Vita3K/files/12243484/vita3k.log)

**Comment by TheSargoner** [comment]
Could you explain why this was closed?

**Comment by Zangetsu38** [comment]
> @Zangetsu38 Could you explain why this was closed?

Is Android issue, wrong place
