### ISSUE TITLE
[feature request] create savestate every few minutes to recover from crash

### ISSUE THREAD

**Issue by rrrcabral** [Vita3K/Vita3K#2880]
I was playing "Muramasa Rebirth" which was having some crashes, which made me lose the progress of the last few minutes played,
so I got the idea:

the emulator could silently save a savestate every few minutes, so that in the event of a crash... you could resume the game from a moment closer to the crash, without having to rely on distant checkpoints in the game itself.

**Comment by scribam** [comment]
This is an experimental emulator so crashes can happen. Be careful while playing and save often😉
