### ISSUE TITLE
The Legend of Heroes: Trails in the Sky the 3rd Evolution Crashes

### ISSUE THREAD

**Issue by johnwhite5116** [Vita3K/Vita3K#2885]
The Legend of Heroes: Trails in the Sky the 3rd Evolution [PCSH10083]
(The Legend of Heroes: Sora No Kiseki the 3rd Evolution)

I've played the game about 25 hours without any issue.
At certain point, the emulator keeps crashing so I couldn't go further.
I tried to change some settings and configurations but it didn't work.

![console](https://github.com/Vita3K/Vita3K/assets/75278127/54c6368f-aeee-470f-a684-b99a5121ec8b)

[vita3k.log](https://github.com/Vita3K/Vita3K/files/12469617/vita3k.log)

**Comment by Zangetsu38** [comment]
using compat state for that, open issue or using already exist
