### ISSUE TITLE
GXM-related regression from #285

### ISSUE THREAD

**Issue by VelocityRa** [Vita3K/Vita3K#289]
Before #285:

![](https://images-ext-1.discordapp.net/external/fMAne0zfUJ8TVoE-rvJqx98fQMgN11Q_ITwsku1ifOo/%3Fwidth%3D1006%26height%3D627/https/media.discordapp.net/attachments/418026683015233546/443683899864907786/unknown.png)

After #285:

![](https://cdn.discordapp.com/attachments/442344583293304833/473185053317398538/unknown.png)

The misalignment is clearly visible above.

---

Thanks to @IllusionMan1212 for reporting and finding the offending PR.

**Comment by petmac** [comment]
Thanks!

**Comment by petmac** [comment]
@IllusionMan1212 is this fixed now?

**Comment by IllusionMan1212** [comment]
@petmac yes it is, issue should be closed.
