### ISSUE TITLE
Since 290051f I can no longer navigate the UI with my controller

### ISSUE THREAD

**Issue by windwakr** [Vita3K/Vita3K#2897]
Since 290051f my Xbox One controller no longer works to navigate the UI. If I press a direction on the dpad it will light up the current selection but won't move. This affects the built-in UI only(game selection, save selection). In game everything is fine.

I'm on Windows.

**Comment by Zangetsu38** [comment]
hmm yes, i see same, i looking it

**Comment by Zangetsu38** [comment]
after quick look, directionel button get is wrong value, is broken

**Comment by Zangetsu38** [comment]
@windwakr you can testing this pr ?
https://github.com/Vita3K/Vita3K/pull/2898

**Comment by windwakr** [comment]
Yeah, that seems to fix it.

**Comment by Zangetsu38** [comment]
Ah thx i have forget close it
