### ISSUE TITLE
[Regression] macOS: PR #2940 broke FFX

### ISSUE THREAD

**Issue by shinra-electric** [Vita3K/Vita3K#2943]
Broken build: 1a912280 (#2940)
Last working build: 810c3aea 

1a912280: 
<img width="1072" alt="Screenshot 2023-09-26 at 10 18 04" src="https://github.com/Vita3K/Vita3K/assets/50119606/65b83598-19bc-454c-bbb4-a7902fe9d084">
<img width="1072" alt="Screenshot 2023-09-26 at 10 18 40" src="https://github.com/Vita3K/Vita3K/assets/50119606/bebd6f6d-ce8f-4123-8306-4bc159871afd">

810c3aea: 

<img width="1072" alt="Screenshot 2023-09-26 at 10 24 56" src="https://github.com/Vita3K/Vita3K/assets/50119606/9794140d-07e9-4821-9629-195894c431ff">
<img width="1072" alt="Screenshot 2023-09-26 at 10 25 17" src="https://github.com/Vita3K/Vita3K/assets/50119606/b768a194-dac2-4fe6-a8ba-82a99e3dc6c3">

**Comment by KhoraLee** [comment]
It is working on latest with GPU Render accuracy high
<img width="960" alt="image" src="https://github.com/Vita3K/Vita3K/assets/18005062/20e0b2f5-30bb-4cea-81d7-d6122323ec9f">

**Comment by shinra-electric** [comment]
Yes, you're right. It does work when changing GPU rendering accuracy to high. 

Should this count as a regression then? Because it worked with standard accuracy previously. 

Or can the issue be closed?

**Comment by nn9dev** [comment]
Before https://github.com/Vita3K/Vita3K/commit/1a9122803d04ef1ff373a1351acc81e522e1c895 there was no render accuracy option, and as stated by the developer of that commit, the default before was high accuracy. This issue can likely be closed, but I'll wait for someone else to chime in.

![image](https://github.com/Vita3K/Vita3K/assets/39563889/48e82851-5cad-4d94-979c-f53a8d85cdfe)

**Comment by Macdu** [comment]
Actually, the fact that it doesn't render properly on Mac with the renderer accuracy set to standard is probably a bug, I'm looking at it.
