### ISSUE TITLE
Не работают сохранения в играх.

### ISSUE THREAD

**Issue by Serafim129** [Vita3K/Vita3K#2948]
Доброго времени суток.
Устройство Mi 12t, пробовал игры Untharted Golden Abbis и Ninja gaiden 2 .Не работают сохранения в играх. Сами игры работают отлично. И в случае с Untharted Golden Abbis также не работает запуск с контрольной точки.

**Comment by Zangetsu38** [comment]
Oki 👌

**Comment by nn9dev** [comment]
I do not know the status of Ninja Gaiden, but for Uncharted, it is a known issue that saving and save files do not work.

**Comment by Serafim129** [comment]
Да. В игре сохранение как бы происходит в самом начале игры. И файл сохранялки создаётся. При входе в меню загрузка игры. Файл отображается. Только вместо даты и время сохранения стоят нули.
Нажимаешь загрузить. Пишет загрузка завершена и всё дальше ничего. При возврате в главное меню. Должно появится продолжить с последней контрольной точки, но этого нет. Есть только возможность продолжить с пролога. Или с начала первой главы. Если уже прошёл её. Даже если ты уже играешь во второй главе. Да и после перезагрузки эмулятора уже нет возможности продолжить с главы. Как-то так. Спасибо.

**Comment by Zangetsu38** [comment]
Speak onky in english
