### ISSUE TITLE
Save and load data menu doesn't refresh

### ISSUE THREAD

**Issue by TheCoolerMS3** [Vita3K/Vita3K#2953]
Hi, I'm on Linux Mint 21.3 playing the "ubuntu-latest" i found on the website. The game I am playing is "Hatsune Miku: Project Diva X". The save and load menu freezes when I click anything, I can make it refresh by pressing F11 to toggle fullscreen, and have to do this multiple times to start the game.

**Comment by TheCoolerMS3** [comment]
Update: It seems this does not happen if you change your graphics to Vulkan.

**Comment by Zangetsu38** [comment]
issue already exist, relate ogl with vsycnc enable
