### ISSUE TITLE
Prise en charge des processeurs Kirin. 

### ISSUE THREAD

**Issue by Damedane9** [Vita3K/Vita3K#2958]
Dear developers, please add the Kirin processor to the emulator support. Already damn version 8. You gave false hope that it would be launched, you deceived people. Don't you have enough intelligence to do that? Say so. Damn deceivers.

**Comment by Macdu** [comment]
Hello, you look like the kind of guy who would put the cereals after the milk.

**Comment by Zangetsu38** [comment]
> Hello, you look like the kind of guy who would put the cereals after the milk.

Tu m'a tué 😭🗿
