### ISSUE TITLE
Regression: [macOS] Crash on launch after #3058

### ISSUE THREAD

**Issue by shinra-electric** [Vita3K/Vita3K#3085]
I just used the auto updater to get the latest version, and it crashes on launch. 

~~I believe that it was #3084 that caused this.~~

**Comment by Macdu** [comment]
You mention a pull request that is not even merged and that definitely can't cause the emulator to crash on launch.

**Comment by shinra-electric** [comment]
Sorry, I just copied/pasted the most recent PR (which is why I said probably). It may have been #3058. 
In any case, the macOS build is still crashing at launch.
