### ISSUE TITLE
build broken with boost lib

### ISSUE THREAD

**Issue by Zangetsu38** [Vita3K/Vita3K#3092]
After this coimmit https://github.com/Vita3K/Vita3K/commit/f4202ef9b5ec7a3bb52e5dfd22350fc4ca13f961, change cmake script of for custom boost, i get suddenly compile broken, with no works anymore

>4>libboost_filesystem-vc143-mt-gd-x64-1_82.lib(path_traits.obj) : error LNK2038: discordance détectée pour '_ITERATOR_DEBUG_LEVEL' : la valeur '2' ne correspond pas à la valeur '0' in main.obj
4>libboost_filesystem-vc143-mt-gd-x64-1_82.lib(path_traits.obj) : error LNK2038: discordance détectée pour 'RuntimeLibrary' : la valeur 'MDd_DynamicDebug' ne correspond pas à la valeur 'MD_DynamicRelease' in main.obj
4>libboost_filesystem-vc143-mt-gd-x64-1_82.lib(path.obj) : error LNK2038: discordance détectée pour '_ITERATOR_DEBUG_LEVEL' : la valeur '2' ne correspond pas à la valeur '0' in main.obj
4>libboost_filesystem-vc143-mt-gd-x64-1_82.lib(path.obj) : error LNK2038: discordance détectée pour 'RuntimeLibrary' : la valeur 'MDd_DynamicDebug' ne correspond pas à la valeur 'MD_DynamicRelease' in main.obj
4>libboost_filesystem-vc143-mt-gd-x64-1_82.lib(operations.obj) : error LNK2038: discordance détectée pour '_ITERATOR_DEBUG_LEVEL' : la valeur '2' ne correspond pas à la valeur '0' in main.obj
4>libboost_filesystem-vc143-mt-gd-x64-1_82.lib(operations.obj) : error LNK2038: discordance détectée pour 'RuntimeLibrary' : la valeur 'MDd_DynamicDebug' ne correspond pas à la valeur 'MD_DynamicRelease' in main.obj
4>libboost_filesystem-vc143-mt-gd-x64-1_82.lib(directory.obj) : error LNK2038: discordance détectée pour '_ITERATOR_DEBUG_LEVEL' : la valeur '2' ne correspond pas à la valeur '0' in main.obj
4>libboost_filesystem-vc143-mt-gd-x64-1_82.lib(directory.obj) : error LNK2038: discordance détectée pour 'RuntimeLibrary' : la valeur 'MDd_DynamicDebug' ne correspond pas à la valeur 'MD_DynamicRelease' in main.obj
4>libboost_filesystem-vc143-mt-gd-x64-1_82.lib(codecvt_error_category.obj) : error LNK2038: discordance détectée pour '_ITERATOR_DEBUG_LEVEL' : la valeur '2' ne correspond pas à la valeur '0' in main.obj
4>libboost_filesystem-vc143-mt-gd-x64-1_82.lib(codecvt_error_category.obj) : error LNK2038: discordance détectée pour 'RuntimeLibrary' : la valeur 'MDd_DynamicDebug' ne correspond pas à la valeur 'MD_DynamicRelease' in main.obj
4>libboost_filesystem-vc143-mt-gd-x64-1_82.lib(windows_file_codecvt.obj) : error LNK2038: discordance détectée pour '_ITERATOR_DEBUG_LEVEL' : la valeur '2' ne correspond pas à la valeur '0' in main.obj
4>libboost_filesystem-vc143-mt-gd-x64-1_82.lib(windows_file_codecvt.obj) : error LNK2038: discordance détectée pour 'RuntimeLibrary' : la valeur 'MDd_DynamicDebug' ne correspond pas à la valeur 'MD_DynamicRelease' in main.obj
4>libboost_filesystem-vc143-mt-gd-x64-1_82.lib(exception.obj) : error LNK2038: discordance détectée pour '_ITERATOR_DEBUG_LEVEL' : la valeur '2' ne correspond pas à la valeur '0' in main.obj
4>libboost_filesystem-vc143-mt-gd-x64-1_82.lib(exception.obj) : error LNK2038: discordance détectée pour 'RuntimeLibrary' : la valeur 'MDd_DynamicDebug' ne correspond pas à la valeur 'MD_DynamicRelease' in main.obj
4>   Création de la bibliothèque H:/Git/Vita3K/regmgr/build/lib/RelWithDebInfo/Vita3K.lib et de l'objet H:/Git/Vita3K/regmgr/build/lib/RelWithDebInfo/Vita3K.exp
4>LINK : warning LNK4098: conflit entre la bibliothèque par défaut 'MSVCRTD' et les autres bibliothèques ; utilisez /NODEFAULTLIB:library
4>LINK : warning LNK4098: conflit entre la bibliothèque par défaut 'LIBCMTD' et les autres bibliothèques ; utilisez /NODEFAULTLIB:library
4>LINK : warning LNK4098: conflit entre la bibliothèque par défaut 'libcmt.lib' et les autres bibliothèques ; utilisez /NODEFAULTLIB:library
4>libboost_filesystem-vc143-mt-gd-x64-1_82.lib(codecvt_error_category.obj) : error LNK2001: symbole externe non résolu __imp__invalid_parameter
4>libboost_filesystem-vc143-mt-gd-x64-1_82.lib(exception.obj) : error LNK2001: symbole externe non résolu __imp__invalid_parameter
4>libboost_filesystem-vc143-mt-gd-x64-1_82.lib(path_traits.obj) : error LNK2001: symbole externe non résolu __imp__invalid_parameter
4>libboost_filesystem-vc143-mt-gd-x64-1_82.lib(path.obj) : error LNK2001: symbole externe non résolu __imp__invalid_parameter
4>libboost_filesystem-vc143-mt-gd-x64-1_82.lib(operations.obj) : error LNK2001: symbole externe non résolu __imp__invalid_parameter
4>libboost_filesystem-vc143-mt-gd-x64-1_82.lib(directory.obj) : error LNK2001: symbole externe non résolu __imp__invalid_parameter
4>libboost_filesystem-vc143-mt-gd-x64-1_82.lib(codecvt_error_category.obj) : error LNK2001: symbole externe non résolu __imp__calloc_dbg
4>libboost_filesystem-vc143-mt-gd-x64-1_82.lib(windows_file_codecvt.obj) : error LNK2001: symbole externe non résolu __imp__calloc_dbg
4>libboost_filesystem-vc143-mt-gd-x64-1_82.lib(exception.obj) : error LNK2001: symbole externe non résolu __imp__calloc_dbg
4>libboost_filesystem-vc143-mt-gd-x64-1_82.lib(path_traits.obj) : error LNK2001: symbole externe non résolu __imp__calloc_dbg
4>libboost_filesystem-vc143-mt-gd-x64-1_82.lib(path.obj) : error LNK2001: symbole externe non résolu __imp__calloc_dbg
4>libboost_filesystem-vc143-mt-gd-x64-1_82.lib(operations.obj) : error LNK2001: symbole externe non résolu __imp__calloc_dbg
4>libboost_filesystem-vc143-mt-gd-x64-1_82.lib(directory.obj) : error LNK2001: symbole externe non résolu __imp__calloc_dbg
4>libboost_filesystem-vc143-mt-gd-x64-1_82.lib(codecvt_error_category.obj) : error LNK2001: symbole externe non résolu __imp__CrtDbgReport
4>libboost_filesystem-vc143-mt-gd-x64-1_82.lib(exception.obj) : error LNK2001: symbole externe non résolu __imp__CrtDbgReport
4>libboost_filesystem-vc143-mt-gd-x64-1_82.lib(path_traits.obj) : error LNK2001: symbole externe non résolu __imp__CrtDbgReport
4>libboost_filesystem-vc143-mt-gd-x64-1_82.lib(path.obj) : error LNK2001: symbole externe non résolu __imp__CrtDbgReport
4>libboost_filesystem-vc143-mt-gd-x64-1_82.lib(operations.obj) : error LNK2001: symbole externe non résolu __imp__CrtDbgReport
4>libboost_filesystem-vc143-mt-gd-x64-1_82.lib(directory.obj) : error LNK2001: symbole externe non résolu __imp__CrtDbgReport
4>H:\Git\Vita3K\regmgr\build\bin\RelWithDebInfo\Vita3K.exe : fatal error LNK1120: 3 externes non résolus
4>Génération du projet "vita3k.vcxproj" terminée -- ÉCHEC.

Probleme relate so all:
libboost_filesystem-vc143-mt-gd-x64-1_82.lib 
il have try clean all and clone again, have changed nothiong
hey @redpolline

**Comment by redpolline** [comment]
4>libboost_filesystem-vc143-mt-gd-x64-1_82.lib(path_traits.obj) : error LNK2038: discordance détectée pour '_ITERATOR_DEBUG_LEVEL' : la valeur '2' ne correspond pas à la valeur '0' in main.obj
4>libboost_filesystem-vc143-mt-gd-x64-1_82.lib(path_traits.obj) : error LNK2038: discordance détectée pour 'RuntimeLibrary' : la valeur 'MDd_DynamicDebug' ne correspond pas à la valeur 'MD_DynamicRelease' in main.obj

These seem to indicate that they've got a mixed Debug and Release build going on. (I.e. Debug libs used in a Release build or Release libs in a Debug build.) Unless they've explicitly set that up themselves, they've got a corrupted build directory that needs to be purged out and rebuilt from scratch.

4>H:\Git\Vita3K\regmgr\build\bin\RelWithDebInfo\Vita3K.exe : fatal error LNK1120: 3 externes non résolus
4>Génération du projet "vita3k.vcxproj" terminée -- ÉCHEC.

This implies that they are using the bundled Boost in external, and that despite finding the headers for it, the static library wasn't built for some reason.

The current CMakeLists.txt should have thrown a FATAL_ERROR long before it attempted to build Vita3K's main binary in this case. (As the find_boost() call after building the static boost library should have failed due to it being marked as REQUIRED.)

That means they've got a broken CMakeCache.txt (which contains an invalid Boost config) and possibly some invalid .sln / vcxproj files somewhere.

There has been changes to CMakeLists.txt recently, did they have CMake regenerate their Visual Studio solution?

>il have try clean all and clone again, have changed nothiong

Clean All in Visual Studio won't fix the CMakeCache nor the Visual Studio Solution files. For that you need to rerun CMake's generators.

In your case however, I'd recommend deleting the build directory entirely and starting over fresh. You've seem to have some other issues going on here as well.

**Comment by Zangetsu38** [comment]
so problem..., I just explained that I had cloned the project again from 0...
I cloned the project from 0, and compiled, the cache was completely empty, so no connection with it...
so there is a real problem with the cmake script since your commit

**Comment by Zangetsu38** [comment]
i have try compile release only, i get exactly same error
and problem is not in my side
like i have explain, i have totaly deleted folder for clone it again...

>82>libboost_filesystem-vc143-mt-gd-x64-1_82.lib(exception.obj) : error LNK2001: symbole externe non résolu __imp__invalid_parameter
82>libboost_filesystem-vc143-mt-gd-x64-1_82.lib(codecvt_error_category.obj) : error LNK2001: symbole externe non résolu __imp__invalid_parameter
82>libboost_filesystem-vc143-mt-gd-x64-1_82.lib(path.obj) : error LNK2001: symbole externe non résolu __imp__invalid_parameter
82>libboost_filesystem-vc143-mt-gd-x64-1_82.lib(operations.obj) : error LNK2001: symbole externe non résolu __imp__invalid_parameter
82>libboost_filesystem-vc143-mt-gd-x64-1_82.lib(path_traits.obj) : error LNK2001: symbole externe non résolu __imp__invalid_parameter
82>libboost_filesystem-vc143-mt-gd-x64-1_82.lib(directory.obj) : error LNK2001: symbole externe non résolu __imp__invalid_parameter
82>libboost_filesystem-vc143-mt-gd-x64-1_82.lib(windows_file_codecvt.obj) : error LNK2001: symbole externe non résolu __imp__calloc_dbg
82>libboost_filesystem-vc143-mt-gd-x64-1_82.lib(exception.obj) : error LNK2001: symbole externe non résolu __imp__calloc_dbg
82>libboost_filesystem-vc143-mt-gd-x64-1_82.lib(codecvt_error_category.obj) : error LNK2001: symbole externe non résolu __imp__calloc_dbg
82>libboost_filesystem-vc143-mt-gd-x64-1_82.lib(path.obj) : error LNK2001: symbole externe non résolu __imp__calloc_dbg
82>libboost_filesystem-vc143-mt-gd-x64-1_82.lib(operations.obj) : error LNK2001: symbole externe non résolu __imp__calloc_dbg
82>libboost_filesystem-vc143-mt-gd-x64-1_82.lib(path_traits.obj) : error LNK2001: symbole externe non résolu __imp__calloc_dbg
82>libboost_filesystem-vc143-mt-gd-x64-1_82.lib(directory.obj) : error LNK2001: symbole externe non résolu __imp__calloc_dbg
82>libboost_filesystem-vc143-mt-gd-x64-1_82.lib(exception.obj) : error LNK2001: symbole externe non résolu __imp__CrtDbgReport
82>libboost_filesystem-vc143-mt-gd-x64-1_82.lib(codecvt_error_category.obj) : error LNK2001: symbole externe non résolu __imp__CrtDbgReport
82>libboost_filesystem-vc143-mt-gd-x64-1_82.lib(path.obj) : error LNK2001: symbole externe non résolu __imp__CrtDbgReport
82>libboost_filesystem-vc143-mt-gd-x64-1_82.lib(operations.obj) : error LNK2001: symbole externe non résolu __imp__CrtDbgReport
82>libboost_filesystem-vc143-mt-gd-x64-1_82.lib(path_traits.obj) : error LNK2001: symbole externe non résolu __imp__CrtDbgReport
82>libboost_filesystem-vc143-mt-gd-x64-1_82.lib(directory.obj) : error LNK2001: symbole externe non résolu __imp__CrtDbgReport
82>H:\Git\Vita3K\regmgr\build\bin\Release\Vita3K.exe : fatal error LNK1120: 3 externes non résolus
82>Génération du projet "vita3k.vcxproj" terminée -- ÉCHEC.

@redpolline  your commit here https://github.com/Vita3K/Vita3K/commit/f4202ef9b5ec7a3bb52e5dfd22350fc4ca13f961 have just broken compile, that all, now need found how fixing it...

**Comment by bookmist** [comment]
I have the same problem. bundled boost cannot be found.

**Comment by Zangetsu38** [comment]
> I have the same problem. bundled boost cannot be found.

MERCI... i have hop one other should get same problem...

**Comment by redpolline** [comment]
What versions of Windows / Visual Studio / CMake are you guys using?

Also it would help to see someone's build directory. (Zip file or something would be nice.) As I'm having trouble reproducing the issue on my end.

**Comment by Zangetsu38** [comment]
just all with the last version

but just script changed have caused this error, now like i said, need found why

**Comment by redpolline** [comment]
Last version of what? I need to know what versions of Windows / Visual Studio / CMake you are using so I can try to replicate this bug.

You can find the Windows version by hitting the Windows Key + R on the desktop and typing "winver" into the dialog box that pops up.

You can find the version of Visual Studio by opening the about dialog from the help menu.

You can find the version of CMake in the apps list in the Settings app - OR - Programs and Features in the Control Panel -OR- in the CMakeCache.txt in the build directory.

(And again a zip file of that build directory would be useful.)

**Comment by Zangetsu38** [comment]
last version for all i said, i am full updated for all, i no can said more here
for zip file is dead lol
it is big size

**Comment by Zangetsu38** [comment]
hmm, that is very strange...
i have run winget just before here, i have get some update of git and some other
and here, i get just compile fixed ? 
and before compile it have regenerated project

**Comment by Zangetsu38** [comment]
@bookmist if you can maybe try it in powershell in admin
winget upgrade --all --include-unknown
maybe can fix issue like me

**Comment by Zangetsu38** [comment]
one thinks just strange, new i have lot warning in cmake

>-- Selecting Windows SDK version 10.0.22621.0 to target Windows 10.0.25997.
-- The C compiler identification is MSVC 19.38.33130.0
-- The CXX compiler identification is MSVC 19.38.33130.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: C:/Program Files/Microsoft Visual Studio/2022/Community/VC/Tools/MSVC/14.38.33130/bin/Hostx64/x64/cl.exe - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: C:/Program Files/Microsoft Visual Studio/2022/Community/VC/Tools/MSVC/14.38.33130/bin/Hostx64/x64/cl.exe - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
Enabling CAPSTONE_ARM_SUPPORT
-- Version: 10.1.0
-- Build type: Release
-- Build spdlog: 1.12.0
-- Build type: Release
CMake Deprecation Warning at external/libfat16/CMakeLists.txt:2 (cmake_minimum_required):
  Compatibility with CMake < 3.5 will be removed from a future version of
  CMake.

  Update the VERSION argument <min> value or use a ...<max> suffix to tell
  CMake that the project does not need compatibility with older versions.


-- Could NOT find Doxygen (missing: DOXYGEN_EXECUTABLE)
-- The ASM compiler identification is MSVC
-- Found assembler: C:/Program Files/Microsoft Visual Studio/2022/Community/VC/Tools/MSVC/14.38.33130/bin/Hostx64/x64/cl.exe
-- Target architecture: x86_64
-- Found Boost: H:/Git/Vita3K/home/build/external/boost/lib/cmake/Boost-1.82.0/BoostConfig.cmake (found suitable version "1.82.0", minimum required is "1.57")
CMake Deprecation Warning at external/dynarmic/externals/robin-map/CMakeLists.txt:1 (cmake_minimum_required):
  Compatibility with CMake < 3.5 will be removed from a future version of
  CMake.

  Update the VERSION argument <min> value or use a ...<max> suffix to tell
  CMake that the project does not need compatibility with older versions.


CMake Deprecation Warning at external/dynarmic/externals/xbyak/CMakeLists.txt:1 (cmake_minimum_required):
  Compatibility with CMake < 3.5 will be removed from a future version of
  CMake.

  Update the VERSION argument <min> value or use a ...<max> suffix to tell
  CMake that the project does not need compatibility with older versions.


CMake Deprecation Warning at external/unicorn/CMakeLists.txt:4 (cmake_minimum_required):
  Compatibility with CMake < 3.5 will be removed from a future version of
  CMake.

  Update the VERSION argument <min> value or use a ...<max> suffix to tell
  CMake that the project does not need compatibility with older versions.


-- The ASM_MASM compiler identification is MSVC
-- Found assembler: C:/Program Files/Microsoft Visual Studio/2022/Community/VC/Tools/MSVC/14.38.33130/bin/Hostx64/x64/ml64.exe
CMake Deprecation Warning at external/yaml-cpp/CMakeLists.txt:2 (cmake_minimum_required):
  Compatibility with CMake < 3.5 will be removed from a future version of
  CMake.

  Update the VERSION argument <min> value or use a ...<max> suffix to tell
  CMake that the project does not need compatibility with older versions.


CMake Deprecation Warning at external/SPIRV-Cross/CMakeLists.txt:22 (cmake_minimum_required):
  Compatibility with CMake < 3.5 will be removed from a future version of
  CMake.

  Update the VERSION argument <min> value or use a ...<max> suffix to tell
  CMake that the project does not need compatibility with older versions.


-- SPIRV-Cross: Finding Git version for SPIRV-Cross.
-- Found Git: C:/Program Files/Git/cmd/git.exe (found version "2.43.0.windows.1")
-- SPIRV-Cross: Git hash: bccaa94d
CMake Deprecation Warning at external/pugixml/CMakeLists.txt:1 (cmake_minimum_required):
  Compatibility with CMake < 3.5 will be removed from a future version of
  CMake.

  Update the VERSION argument <min> value or use a ...<max> suffix to tell
  CMake that the project does not need compatibility with older versions.


-- Could NOT find ZLIB (missing: ZLIB_LIBRARY ZLIB_INCLUDE_DIR) (Required is at least version "1.2.11")
psvpfsparser
OpenSSL include dir: H:/Git/Vita3K/home/build/external/openssl/openssl-3/x64/include
OpenSSL libraries: H:/Git/Vita3K/home/build/external/openssl/openssl-3/x64/lib/libssl.lib;H:/Git/Vita3K/home/build/external/openssl/openssl-3/x64/lib/libcrypto.lib
System curl not found, compiling curl from source
-- curl version=[8.1.2-DEV]
-- Could NOT find Perl (missing: PERL_EXECUTABLE)
-- Could NOT find ZLIB (missing: ZLIB_LIBRARY ZLIB_INCLUDE_DIR)
-- Could NOT find LibPSL (missing: LIBPSL_LIBRARY LIBPSL_INCLUDE_DIR)
-- Could NOT find LibSSH2 (missing: LIBSSH2_LIBRARY LIBSSH2_INCLUDE_DIR)
-- Performing Curl Test HAVE_WIN32_WINNT
-- Performing Curl Test HAVE_WIN32_WINNT - Success
-- Found _WIN32_WINNT=0x0A00
-- Enabled features: SSL IPv6 unixsockets AsynchDNS Largefile SSPI alt-svc HSTS SPNEGO Kerberos NTLM HTTPS-proxy threadsafe
-- Enabled protocols: HTTP HTTPS
-- Enabled SSL backends: Schannel
CMake Deprecation Warning at external/xxHash/cmake_unofficial/CMakeLists.txt:8 (cmake_minimum_required):
  Compatibility with CMake < 3.5 will be removed from a future version of
  CMake.

  Update the VERSION argument <min> value or use a ...<max> suffix to tell
  CMake that the project does not need compatibility with older versions.


-- Architecture: AMD64
-- Enable xxHash dispatch mode
CMake Deprecation Warning at external/nativefiledialog-extended/CMakeLists.txt:1 (cmake_minimum_required):
  Compatibility with CMake < 3.5 will be removed from a future version of
  CMake.

  Update the VERSION argument <min> value or use a ...<max> suffix to tell
  CMake that the project does not need compatibility with older versions.


nfd Platform: PLATFORM_WIN32
nfd Compiler: COMPILER_MSVC

**Comment by Zangetsu38** [comment]
i have just see here, new warning on cmake for boost
![image](https://github.com/Vita3K/Vita3K/assets/5261759/8a5e4724-774b-4c4e-900a-1fb34f2d9812)

**Comment by Zangetsu38** [comment]
ok... error is keep here, i no understund...
i have succes compile, and now i no can compile anymorz again, same before boost error with lib...

**Comment by Alriightyman** [comment]
For me, on Windows, the boost lib it was referencing was what the issue was. I needed to change the lib.  So, for these:
`libboost_NAME-vcVSVERSION-mt-gd-x64-1_82.lib`, I needed to change it to look at `libboost_NAME-vcVSVERSION-mt-x64-1_82.lib`.  Notice the `-gd` part is what I took out, which I believe is a debug lib version.  Hope this helps someone.

**Comment by redpolline** [comment]
>For me, on Windows, the boost lib it was referencing was what the issue was. I needed to change the lib. So, for these:
>libboost_NAME-vcVSVERSION-mt-gd-x64-1_82.lib, I needed to change it to look at >libboost_NAME-vcVSVERSION-mt-x64-1_82.lib. Notice the -gd part is what I took out, which I believe is a debug lib version. Hope this helps someone.

As I said before, this is the result of an old source / build directory being used. Fixing Issue #3069 required changes to be made to CMakeLists.txt that require a re-run of cmake for the compiler to be able to find and use the correct libraries. Visual Studio doesn't always re-run cmake when changes are made to CMakeLists.txt, and sometimes cmake will re-use old data from it's cache, (even if it's no longer correct with the given changes.), even if cmake is re-run manually by the user.

The only thing that will fix this situation is either completely dumping the build directory (and possibly source code directory depending on how the user ran cmake initially) and building from scratch. (This is effectively what the CI does and is the reason the build worked there.) -OR- manually fixing the paths in VS. (But as others have already alluded to in this issue, these manual changes in VS *WILL* be lost when the Visual Studio solution / project files get regenerated *IF* cmake's cache isn't fixed as well.)

It should be noted that re-running CMake from scratch is a good idea whenever changes to CMakeLists.txt are made. Otherwise issues like this one and issues like mysteriously disabled features / components, incorrect defaults / header files, etc. can happen.

@Zangetsu38: That CMake warning looks all kinds of suspicious. The boost library in externals is not under the "trophy" directory. ("trophy" doesn't even exist in the root of the source directory.) Which means either you had one there at some point in the past, -OR- your CMakeCache.txt was corrupted at some point. Either way, you should dump that source directory completely. It's obviously been through a lot overtime and you might have other issues elsewhere in it.

**Comment by Zangetsu38** [comment]
@redpolline what ? 😐
Trophy folder is just my branch name, i no understund what you said here
And no compare with CI, it using vcpkg for boost, is totaly diferent build

**Comment by koukdw** [comment]
I get the same problem, with clean install just after cloning. Using windows-vs2022 preset with RelWithDebInfo configuration.

**Comment by Zangetsu38** [comment]
Finnaly fixed 10 month after by pr #3358
