### ISSUE TITLE
 emulator crashes when it tries to load

### ISSUE THREAD

**Issue by mad10max** [Vita3K/Vita3K#3109]
[vita3k.log](https://github.com/Vita3K/Vita3K/files/13567526/vita3k.log)

https://github.com/Vita3K/Vita3K/assets/153015095/dbd084f7-7a55-48d8-989d-f2595b9d0126

my cpu is i5 4570 and 8Gg ddr3

**Comment by jrdneo** [comment]
looks like "Croden1999" had a similar issue it may be down to outdated graphics drivers, have you tried updating?

**Comment by Croden1999** [comment]
> looks like "Croden1999" had a similar issue it may be down to outdated graphics drivers, have you tried updating?

no, he just need install the app/game again

**Comment by mad10max** [comment]
> looks like "Croden1999" had a similar issue it may be down to outdated graphics drivers, have you tried updating?

Yes I had update to the last version but not change

https://github.com/Vita3K/Vita3K/assets/153015095/9281e415-db5a-4ca9-81f4-c53e5f51f7fe

[vita3k.log](https://github.com/Vita3K/Vita3K/files/13865377/vita3k.log)

**Comment by Croden1999** [comment]
> > looks like "Croden1999" had a similar issue it may be down to outdated graphics drivers, have you tried updating?
> 
> Yes I had update to the last version but not change
> 
>  2024-01-08.23-09-24.mp4 
> [vita3k.log](https://github.com/Vita3K/Vita3K/files/13865377/vita3k.log)

your GPU is outdated, OpenGL 4.4 at least.
