### ISSUE TITLE
Ys: VIII - Dana of Lacrimosa can't be played for Snapdragon 8 gen 2 devices

### ISSUE THREAD

**Issue by blairthered** [Vita3K/Vita3K#3125]
I've been trying to get **Ys: VIII** to play in Vita3k but everytime it starts, the app crash. A lot of ppl in the Vita3k community was able to play it because they have **_Snapdragon 855_** below CPUs or **Mediatek** users but for _**Snapdragon 8 gen 2**_ above it's unplayable. I tried different drivers that is compatible for Adreno 7xx other than my _**System driver**_(_because it didn't work in the first place_).I don't know if the devs actually cared for the newer CPUs in **Snapdragon** because the only game that can be played with SD 8 gen 2 is _Toukiden: Age of Demons_, that's all.

https://github.com/Vita3K/Vita3K/assets/153729447/2cc81e1d-bb55-4dab-a1d1-aebad4fea8fb

**Comment by Croden1999** [comment]
Android specific issues go to https://github.com/Vita3K/Vita3K-Android/issues/new
