### ISSUE TITLE
Vulkan Backend visual bugs

### ISSUE THREAD

**Issue by ghost** [Vita3K/Vita3K#3152]
Title is what I mean, these are Vulkan exclusive bugs and not much of a problem with OpenGL. For most games I've played on the newer versions I have issues with the graphics when using Vulkan.
Including 
- Assets not loading.
- Random pixels on the screen.

![image](https://github.com/Vita3K/Vita3K/assets/149040258/4eee2c4e-3617-43e1-aeee-e30e45b3a4b2)

**Comment by scribam** [comment]
Looks like this issue was brought to us by a ghost! 👻 Since they’ve vanished into the ether, I’m closing this one
