### ISSUE TITLE
Nothing happens after clicking on “Install Firmware” or “Install .pkg”

### ISSUE THREAD

**Issue by GrimPixel** [Vita3K/Vita3K#3158]
This happens on Manjaro Linux MATE desktop.

**Comment by Christ896** [comment]
I solved this by downloading xdg-desktop-portal, make sure to get a backend like xdg-desktop-kde or xdg-desktop-gtk.

**Comment by GrimPixel** [comment]
I tried gtk and kde, the problem is still there.
https://wiki.archlinux.org/title/XDG_Desktop_Portal#List_of_backends_and_interfaces

**Comment by scribam** [comment]
xdg-desktop-portal with a compatible backend is indeed required
