### ISSUE TITLE
Ayn odin 1 pro controller issue

### ISSUE THREAD

**Issue by HoshiIsSleepy** [Vita3K/Vita3K#3161]
Dpad up stops working upon loading vita3k android build on android 10, this issue wasn't present on the version 1.7 build of vita3k. Needs to be fixed so that ayn odin lite and pros users can keep using vita3k.

**Comment by Seiryz** [comment]
Yeah, same here. Apparently v7 doesn't have the problem, but I've yet to try it myself. Just grabbed the apk. Thought my device was busted for a minute there.

**Comment by FrogProjectOfficial** [comment]
Having the same issue. On v11, booting the app actually makes the d-pad "up" completely unusable on the device, across all apps. Only a hard reboot fixes it.

**Comment by Zangetsu38** [comment]
Wrong repo

**Comment by scribam** [comment]
@HoshiIsSleepy this is an issue for https://github.com/Vita3K/Vita3K-Android, please open a new one there
