### ISSUE TITLE
crash randomly in 3min or less

### ISSUE THREAD

**Issue by Tempaccnt** [Vita3K/Vita3K#3181]
My phone is Xiaomi Redmi k70 pro
running HyperOS with Snapdragon 8 gen 3.

the app crash randomly, sometimes in the main menu, or after starting a game a playing for a few seconds.

here is the log file for the crash:
Redmi/manet/manet:14/UKQ1.230804.001/V816.0.9.0.UNMCNXM:user/release-keys

      #00 pc 00000000000e812c  /apex/com.android.runtime/lib64/bionic/libc.so (tgkill+12) (BuildId: 1e3ca19bcae05c01b019c85f3f422e56)
      #01 pc 0000000000db9e0c  /data/app/~~DqMfV52wZPu6TMfVv4r24w==/org.vita3k.emulator-I1GEpO2d0Xr1cH1tCYoosA==/lib/arm64/libVita3K.so (BuildId: 3cbfa28fd300ea32056094cf9b2ba4bf475a1f9a)
      #02 pc 00000000000024d0  /apex/com.android.art/lib64/libsigchain.so (art::SignalChain::Handler(int, siginfo*, void*)+1072) (BuildId: 0eb1ce8eec78535f631bcc5607023e38)
      #03 pc 0000000000000860  [vdso]
      #04 pc 0000000000d42ae4  /data/app/~~DqMfV52wZPu6TMfVv4r24w==/org.vita3k.emulator-I1GEpO2d0Xr1cH1tCYoosA==/lib/arm64/libVita3K.so (BuildId: 3cbfa28fd300ea32056094cf9b2ba4bf475a1f9a)
      #05 pc 0000000000d44fc0  /data/app/~~DqMfV52wZPu6TMfVv4r24w==/org.vita3k.emulator-I1GEpO2d0Xr1cH1tCYoosA==/lib/arm64/libVita3K.so (BuildId: 3cbfa28fd300ea32056094cf9b2ba4bf475a1f9a)
      #06 pc 0000000000d17454  /data/app/~~DqMfV52wZPu6TMfVv4r24w==/org.vita3k.emulator-I1GEpO2d0Xr1cH1tCYoosA==/lib/arm64/libVita3K.so (BuildId: 3cbfa28fd300ea32056094cf9b2ba4bf475a1f9a)
      #07 pc 00000000008a7458  /data/app/~~DqMfV52wZPu6TMfVv4r24w==/org.vita3k.emulator-I1GEpO2d0Xr1cH1tCYoosA==/lib/arm64/libVita3K.so (BuildId: 3cbfa28fd300ea32056094cf9b2ba4bf475a1f9a)
      #08 pc 00000000007656fc  /data/app/~~DqMfV52wZPu6TMfVv4r24w==/org.vita3k.emulator-I1GEpO2d0Xr1cH1tCYoosA==/lib/arm64/libVita3K.so (Java_org_libsdl_app_SDLActivity_nativeRunMain+448) (BuildId: 3cbfa28fd300ea32056094cf9b2ba4bf475a1f9a)
      #09 pc 000000000000dd0c  /data/app/~~DqMfV52wZPu6TMfVv4r24w==/org.vita3k.emulator-I1GEpO2d0Xr1cH1tCYoosA==/oat/arm64/base.odex (art_jni_trampoline+156)
      #10 pc 0000000000209418  /apex/com.android.art/lib64/libart.so (nterp_helper+152) (BuildId: 18967fdcbeb3edaa8475d2b7afce1444)
      #11 pc 00000000000d32a8  /data/app/~~DqMfV52wZPu6TMfVv4r24w==/org.vita3k.emulator-I1GEpO2d0Xr1cH1tCYoosA==/oat/arm64/base.vdex (org.libsdl.app.SDLMain.run+180)
      #12 pc 0000000000162538  /system/framework/arm64/boot.oat (java.lang.Thread.run+72) (BuildId: 0bb5ac2738a2ccbcd010e82a0904e718497b6553)
      #13 pc 00000000002109a4  /apex/com.android.art/lib64/libart.so (art_quick_invoke_stub+612) (BuildId: 18967fdcbeb3edaa8475d2b7afce1444)
      #14 pc 00000000002545f0  /apex/com.android.art/lib64/libart.so (art::ArtMethod::Invoke(art::Thread*, unsigned int*, unsigned int, art::JValue*, char const*)+176) (BuildId: 18967fdcbeb3edaa8475d2b7afce1444)
      #15 pc 0000000000687f24  /apex/com.android.art/lib64/libart.so (art::Thread::CreateCallback(void*)+1408) (BuildId: 18967fdcbeb3edaa8475d2b7afce1444)
      #16 pc 00000000000fd134  /apex/com.android.runtime/lib64/bionic/libc.so (__pthread_start(void*)+208) (BuildId: 1e3ca19bcae05c01b019c85f3f422e56)
      #17 pc 0000000000096ae4  /apex/com.android.runtime/lib64/bionic/libc.so (__start_thread+68) (BuildId: 1e3ca19bcae05c01b019c85f3f422e56)

**Comment by Tempaccnt** [comment]
well, I did multiple things including updating vita3k to the latest update, and using vulkan with a custom driver for Adreno 7xx.

it crashed twice, then started working and haven't crashed since then

**Comment by scribam** [comment]
@Tempaccnt this is an issue for https://github.com/Vita3K/Vita3K-Android, please open a new one there
