### ISSUE TITLE
[Feature Request]: 

### ISSUE THREAD

**Issue by Bingku03** [Vita3K/Vita3K#3218]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What feature are you suggesting?

Mali G68MC4 and other mali gpu are still invincible character in One piece BB and in Jstar.. Injustice also have Force close problem..

### Why would this feature be useful?

There are many mali user people are still waiting for it.

### Platform (if relevant)

None

**Comment by Zangetsu38** [comment]
wrong place for this

**Comment by scribam** [comment]
@Bingku03 this is an issue related to https://github.com/Vita3K/Vita3K-Android, create a new one there
