### ISSUE TITLE
[Feature Request]: Real device battery status 

### ISSUE THREAD

**Issue by mavethee** [Vita3K/Vita3K#3224]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What feature are you suggesting?

![CleanShot 2024-02-23 at 13 07 55@2x](https://github.com/Vita3K/Vita3K/assets/47083527/7357d1d9-d0cd-49f3-ad96-5676bbffb611)
Track battery status in case of devices that have one.

### Why would this feature be useful?

This could be useful if UI will become more scaling friendly.

### Platform (if relevant)

None

**Comment by Zangetsu38** [comment]
i have already search for this, is possible, but only for android/laptop

**Comment by mavethee** [comment]
> i have already search for this, is possible, but only for android/laptop

Well, yeah in mind it's a feature towards devices having batteries ;)

**Comment by mavethee** [comment]
Closed as completed o7 Thanks Zangetsu once again
