### ISSUE TITLE
Config file support

### ISSUE THREAD

**Issue by VelocityRa** [Vita3K/Vita3K#325]
We have a config system using [Boost.ProgramOptions](https://www.boost.org/doc/libs/1_58_0/doc/html/program_options.html) which is used for command-line options (see [this file](https://github.com/Vita3K/Vita3K/blob/master/src/emulator/host/src/config.cpp) and the header).

It can [handle](https://www.boost.org/doc/libs/1_58_0/doc/html/program_options/overview.html#idp337767072) reading of config files (.ini, not sure if other types are supported), but we need a way to serialize those options to a file (the ones with the "config_desc" options description, in config.cpp). We could use Boost.Config for this.

**Comment by wfscans** [comment]
https://github.com/Vita3K/Vita3K/pull/396

**Comment by pent0** [comment]
Done.
