### ISSUE TITLE
[BUG]: [macOS] log file grows to over 100GB with Shader Logging turned on

### ISSUE THREAD

**Issue by shinra-electric** [Vita3K/Vita3K#3250]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

v0.2.0 3584

### Description of Issue

I was trying out FFX for a few hours, until I got an OS message saying I was running out of disk space. 

It turns out that it was the `vita3k.log` file that was growing as I was playing. It had grown to over 106GB. (The log file contained in the application bundle, not in Application Support).

In settings, these logs are activated:
- Shader Logging
- Uniform Logging
- Validation Layer

If I disable Shader Logging, the issue doesn't occur.

### Expected Behavior

The log file shouldn't get that large...

### Reproduction Steps

Since FFX has only recently become playable, I don't know if this is new behaviour or an older bug. 

I first noticed the issue when entering Kilika Temple. 

If I close Vita3k, delete the log, and load my save in the temple, the log file grows to several hundred MB in a few seconds. 

### Log File

I can't post a full log file as they are too large, but here is a snippet: 

[Example.txt](https://github.com/Vita3K/Vita3K/files/14628966/Example.txt)

### System Configuration

CPU: M1 Pro
GPU/Driver: M1 Pro
RAM: 16GB
OS: Sonoma 14.4

**Comment by shinra-electric** [comment]
Here is a save file, just in case it's related to that specific location in the game:
[PCSG00219.zip](https://github.com/Vita3K/Vita3K/files/14628982/PCSG00219.zip)

**Comment by Macdu** [comment]
Disable the "Uniform logging" option in Settings->Debug->Unform logging (it is disabled by default).

**Comment by shinra-electric** [comment]
> Disable the "Uniform logging" option in Settings->Debug->Unform logging (it is disabled by default).

Disabling Shader Logging stopped it. I've turned off Uniform logging as well as per your advice. 
But just so you are aware, I didn't turn these on.
