### ISSUE TITLE
[Feature Request]: Emulation Station Support For Linux!

### ISSUE THREAD

**Issue by Treyway995** [Vita3K/Vita3K#3258]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What feature are you suggesting?

Hello,

A BIG! Recommendation From me as well as other people who play their roms on linux or steam deck is adding support of functionality of your roms on vita 3k to be playable on emulation station. It is the ultimate all in one platform for all of your emulators & roms especially for those people with massive libraries that just prefer to play their library on each emulator from the platform itself instead of having to launch each emulator just to play their roms. In its current state ps vita tab does show on ES but the games do not launch at all so maybe… it’s a bug🤔 

Thanks.

### Why would this feature be useful?

Users on steam deck or linux in general prefer to just have one platform where they can launch all of their roms especially if they have huge libraries of games

### Other emulators or software with a similar feature

Duckstation
PCSX2
Dolphin
Cemu
Flycast
Retroarch
PPSSPP

### Platform (if relevant)

Linux

**Comment by popsUlfr** [comment]
https://emudeck.github.io/emulators/steamos/vita3k/#how-to-configure-vita3k-to-work-with-es-de-and-pegasus

It works, I'm launching Vita games from Emulation Station on my Steam Deck. There just seems to be an issue where Vita3K doesn't want to close in game mode without forcefully killing.

**Comment by Treyway995** [comment]
Thanks,🙏 managed to get this up and running now.

**Comment by scribam** [comment]
This issue has been resolved
