### ISSUE TITLE
[Feature Request]: touchscreen recentering analog sticks (android)

### ISSUE THREAD

**Issue by dnbx** [Vita3K/Vita3K#3266]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What feature are you suggesting?

Android vita3k touchscreen analog sticks are fixed only. Many games and emulators allow the option for "recentering", where the initial touch is considered the center from where to move the analog stick

### Why would this feature be useful?

Much better control, (subjectively) more intuitive, as it more closely simulates how a physical analog stick is used; for example on a controller, you can physically push down from the top of the "nub" without forward input 

### Other emulators or software with a similar feature

Dolphin, CoD, PPSSPP, (yu whzu shall not be named) etc etc.. can add if needed but likely most have seen this feature in game apps. 

### Platform (if relevant)

None

**Comment by Croden1999** [comment]
You should push to https://github.com/Vita3K/Vita3K-Android/issues, not master repo
