### ISSUE TITLE
[BUG]: Only play eng voice in NINJA GAIDEN Σ PLUS [PCSG00033].

### ISSUE THREAD

**Issue by Croden1999** [Vita3K/Vita3K#3268]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

v0.2.0 3593-bdf38385

### Description of Issue

This bug is audio distribution issue on Vita3K, here is only play eng voice, jpn voice is not played, but this game include jpn voice audio and video files.

### Expected Behavior

play the story and listen.

### Reproduction Steps

play this game and playing the story.

### Log File

[vita3k.log](https://github.com/Vita3K/Vita3K/files/14863071/vita3k.log)

### System Configuration

CPU: Intel Core i7-7700HQ
GPU/Driver: NVIDIA GeForce GTX 1050
RAM: 16 GB
OS: Windows 10

**Comment by nishinji** [comment]
Set system lang to Japanese

**Comment by Croden1999** [comment]
> Set system lang to Japanese

yes, is useful

**Comment by nishinji** [comment]
It may be convenient to separate the console region and language settings, although Zang may not like it

**Comment by Croden1999** [comment]
> It may be convenient to separate the console region and language settings, although Zang may not like it

i agree with you
