### ISSUE TITLE
[BUG]:Games crashing after logo at phone with Hyper OS but works perfectly without (android) is:open

### ISSUE THREAD

**Issue by ScriptUtka** [Vita3K/Vita3K#3271]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

v.0.2.0-11

### Description of Issue

I use Vita3k more than 2 month and everything was good,but after Hyper OS update game start crashing every time 

https://github.com/Vita3K/Vita3K/assets/166740186/e1e3126c-1318-469b-91e4-2b7d1d770057

### Expected Behavior

It doesn't work at all 

### Reproduction Steps

Just open the game 

### Log File

[PCSE00023 - [Mortal Kombat].log](https://github.com/Vita3K/Vita3K/files/14948900/PCSE00023.-.Mortal.Kombat.log)

### System Configuration

CPU:Helio G99-Ultra
GPU/Driver:Mali-G57 MC2
RAM:8+8 RAM expansion 
OS: Hyper OS

**Comment by Croden1999** [comment]
You should push to https://github.com/Vita3K/Vita3K-Android/issues, not master repo
