### ISSUE TITLE
[BUG]: character not visible mediatek helio99 

### ISSUE THREAD

**Issue by Iksanmajijiwkwk** [Vita3K/Vita3K#3303]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

v0,11

### Description of Issue

Bug character mediatek helio99 

### Expected Behavior

Bug character mediatek helio99 

### Reproduction Steps

Bug character 

### Log File

Bug character not visible

### System Configuration

CPU:500 MHz - 2,20 GHz
GPU/Driver:mali-G57 MC2
RAM:8
OS:8

**Comment by REplay36** [comment]
I have same issue on mediatek G99

**Comment by scribam** [comment]
@Iksanmajijiwkwk this is an issue for https://github.com/Vita3K/Vita3K-Android, please open a new one there
