### ISSUE TITLE
[Feature Request]: Full Screen

### ISSUE THREAD

**Issue by tasle1001** [Vita3K/Vita3K#3306]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What feature are you suggesting?

Can we add full screen function just like pcsx2?

### Why would this feature be useful?

When i maximize the window, the bar at top is very showy.

### Other emulators or software with a similar feature

pcsx2
duckstation
![Gensou Suikoden III_SLPM-65074_20240605154714](https://github.com/Vita3K/Vita3K/assets/131510427/86556d31-8485-4cfd-ad75-bcb6350b4f8b)

### Platform (if relevant)

Windows

**Comment by Macdu** [comment]
Press F11
