### ISSUE TITLE
[Feature Request]: Stop game button

### ISSUE THREAD

**Issue by tasle1001** [Vita3K/Vita3K#3307]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What feature are you suggesting?

Can we add stop game feature?

### Why would this feature be useful?

When we want to change game to play, we can close the emulator only. It is very troublesome.

### Other emulators or software with a similar feature

pcsx2
![image](https://github.com/Vita3K/Vita3K/assets/131510427/e6154d1d-796b-4928-8fc8-5f5bd02f989a)

### Platform (if relevant)

None

**Comment by Zangetsu38** [comment]
Is possible exit game, with using P (PS) and click on esc or press cirlcle
