### ISSUE TITLE
[BUG]: Final Fantasy X: White characters [PCSG00219]

### ISSUE THREAD

**Issue by shinra-electric** [Vita3K/Vita3K#3315]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

1.2.0-3611

### Description of Issue

At one point in an in-game cutscene, the characters will have a blur effect applied to them. 
In Vita3K the characters will be displayed as completely white instead. 

<img width="1072" alt="Screenshot 2024-06-11 at 10 42 21" src="https://github.com/Vita3K/Vita3K/assets/50119606/ae75a20a-108e-4425-9a17-7968ec76025b">
<img width="1072" alt="Screenshot 2024-06-11 at 10 42 23" src="https://github.com/Vita3K/Vita3K/assets/50119606/d58ccaea-70b9-4fa2-94e1-fb109ddcdef2">
<img width="1072" alt="Screenshot 2024-06-11 at 10 42 26" src="https://github.com/Vita3K/Vita3K/assets/50119606/f2af8b60-60a7-491e-9ab0-2ee8b06b947b">

### Expected Behavior

[here](https://youtu.be/TVO8thyz1oU?si=m3uvNRz99foP6nW1) is a video showing what it should look like (starting from around  11:38).  (Story Spoilers in the video)

### Reproduction Steps

Here is a save file from a few minutes before the cutscene. Just proceed to the right to trigger it. 
[PCSG00219.zip](https://github.com/user-attachments/files/15785107/PCSG00219.zip).
The section where the issue occurs after following the story for about 5 minutes, when the main character learns the Horrifying Truth™

(I have the Japanese version of the game, I presume the same will occur on other regions but I don't know)

### Log File

Logging didn't seem to work, even though I had the Archive Log option selected at debug level. 
If required I can try again later.

### System Configuration

CPU: M1 Pro
GPU/Driver: M1 Pro
RAM: 16GB
OS: macOS 14 Sonoma

**Comment by Macdu** [comment]
Hello, thank you for the save (which is indeed really spoiler heavy for anyone who hasn't played FFX). I unfortunately wasn't able to replicate this bug on Windows, I tried with both my Nvidia GPU and AMD iGPU.

![image](https://github.com/Vita3K/Vita3K/assets/5671744/46c65585-3c33-46c5-ad8c-016db91fd6c2)

**Comment by Macdu** [comment]
Also this should go in the game issue of the compatibility repository https://github.com/Vita3K/compatibility/issues/2380 instead of here.
