### ISSUE TITLE
[BUG]: [PCSE01011] CollarXMalice- game freezes when trying to manually save

### ISSUE THREAD

**Issue by TryingToLove** [Vita3K/Vita3K#3325]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

Build 3621

### Description of Issue

When selecting SAVE manually, game freezes. When restarting game, a save was not created.

### Expected Behavior

A save should be created

### Reproduction Steps

1. Hit triangle button
2. Try to save game 

### Log File

N/A

### System Configuration

CPU: 
GPU/Driver:
RAM:
OS: SteamOS

**Comment by scribam** [comment]
@TryingToLove I had no issues on Windows and the game is playable according to the compatibility database. Can you post a vita3k.log file?

**Comment by TryingToLove** [comment]
> @TryingToLove I had no issues on Windows and the game is playable according to the compatibility database. Can you post a vita3k.log file?

Apologies…deleted the game already and re-installed a non-emudeck version of Vita3K since.

**Comment by scribam** [comment]
No worries, I am closing the issue then
