### ISSUE TITLE
[BUG]:  Emulator Attempt to decrypt Zombiebound with nonpdrm

### ISSUE THREAD

**Issue by nishinji** [Vita3K/Vita3K#3330]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

v0.2.0 3622

### Description of Issue

The game is homebrew, but attempts to use nonpdrm to decrypt and failed.
![image](https://github.com/user-attachments/assets/9fd8a351-7360-4a21-86a6-0d1dc2e91617)

### Expected Behavior

installed with no issue.

### Reproduction Steps

Download  Zombiebound from https://vitadb.rinnegatamante.it/#/info/328 , and try to install by install vpk. 

### Log File

[vita3k.log](https://github.com/user-attachments/files/16263025/vita3k.log)

### System Configuration

CPU:  AMD Ryzen 3 3100 4-Core Processor
GPU/Driver: Vulkan device: AMD Radeon RX 6800
RAM: 16GB
OS: Windows10

**Comment by Zangetsu38** [comment]
totaly works if you delete or erename package folder in zip
