### ISSUE TITLE
[BUG]: PCSG00755 

### ISSUE THREAD

**Issue by LittleTeddy1234** [Vita3K/Vita3K#3335]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

v.0.2.

### Description of Issue

I cannot seem to be able to open the game once it is downloaded on Vita3K, it just crashes and I have this message in log : 
[logging::init::<lambda_2>::operator ()]: Unhandled C++ exception. invalid string position

![Capture](https://github.com/user-attachments/assets/53e06e27-72b8-46eb-83fe-787c2f1fe530)

### Expected Behavior

Should be able to open game

### Reproduction Steps

![Capture](https://github.com/user-attachments/assets/835089db-a604-4cf2-8211-bd97288c2a68)

### Log File

![Capture](https://github.com/user-attachments/assets/1da51108-3a75-49c9-b1a1-b971bdb99d20)

### System Configuration

CPU: Intel(R) Core(TM) i5-8257U CPU @ 1.40GHz   1.40 GHz
GPU/Driver:
RAM: 8,00
OS:

**Comment by nn9dev** [comment]
Well... judging by the "Base Path" shown, it seems you're attempting to run the emulator without having extracted it first. So you should right click on the `windows-latest.zip` and press "Extract All..."

Additionally, the OpenGL backend isn't often worked on in favor of Vulkan. You should switch your backend to Vulkan for best results.

**Comment by LittleTeddy1234** [comment]
Yes my bad, I redid everything and it works.

But thanks
