### ISSUE TITLE
Random crash when starting an homebrew

### ISSUE THREAD

**Issue by Xeeynamo** [Vita3K/Vita3K#336]
I got a crash on shader.cpp:99 at glLinkProgram with the following exception:
> Unhandled exception at 0x00007FF9A23F4D3B (ntdll.dll) in Vita3K.exe: 0xC0000374: A heap has been corrupted (parameters: 0x00007FF9A24597B0).

It does not happen 100% of the times and it happens only with the homebrew provided in the ticket. It will not come with the sce_sys folder and it is just a .zip file. 
[TEST00000.zip](https://github.com/Vita3K/Vita3K/files/2417029/TEST00000.zip)

**Comment by scribam** [comment]
@Xeeynamo I don't think the zip file you provided is enough to help you on this issue. So, unless I am mistaken, can you add a vpk or any other means to reproduce your issue?

**Comment by Xeeynamo** [comment]
With the last build it does not happen anymore (still I have a different output that does not come with the expected result). I am closing the ticket.
