### ISSUE TITLE
crashes on launch when using a unmounted partition

### ISSUE THREAD

**Issue by eiiiiix** [Vita3K/Vita3K#338]
my main partition is only 50gb so i have it set to use a separate 220gb partition for ux0:
if i try to launch while the partition is unmounted i get an instant crash instead of loading without a list of vpks

**Comment by pent0** [comment]
Please try again. I will put this as No feedback in mean time.

**Comment by scribam** [comment]
Closing, 3 years old issue without feedback from the author
