### ISSUE TITLE
[BUG]: Vulkan and OpenGL not working (AMD)

### ISSUE THREAD

**Issue by Dalk1607** [Vita3K/Vita3K#3391]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

v0.2.0 3650

### Description of Issue

Opening Vita3K with GPU configured to use Vulkan crashes Vita3K and closes it. OpenGL doesn't exhibit this behavior, but games get stuck on the first loading screen.

### Expected Behavior

Vita3K is able to run the games on my computer.

### Reproduction Steps

Open Vita3K and try to run any game. In the case of Vulkan, only opening Vita3K is also enough.

### Log File

[vita3k.log](https://github.com/user-attachments/files/17121059/vita3k.log)
[vita3k.log](https://github.com/user-attachments/files/17121121/vita3k.log)

### System Configuration

CPU: AMD Ryzen 7 5700U
GPU/Driver: Radeon Graphics 1.80 GHz
RAM: 12 GB
OS: Windows 11

**Comment by AnakinMoon** [comment]
Can you go to Window Settings >> Apps and uninstall (OpenCL™, OpenGL®, and Vulkan® compatibility pack) and see if it fix your issue?

**Comment by Dalk1607** [comment]
Yes, it fixes it. Thank you.

**Comment by AnakinMoon** [comment]
> Yes, it fixes it. Thank you.

No problem, enjoy.
