### ISSUE TITLE
NID NOT FOUND

### ISSUE THREAD

**Issue by JamesZheng8088** [Vita3K/Vita3K#351]
Load_var_imports error: NID NOT FOUND
`|W| [load_var_imports]: NID NOT FOUND 0xD662E07C (_Tolotab) at 0x81071120, setting to stub value 0xDEADBEEF`

**Comment by pent0** [comment]
Please provide more context. What game were you testing (name, id ?), what dumper did you use ? Full Log?

**Comment by VelocityRa** [comment]
Known error.

**Comment by VelocityRa** [comment]
Again, it's a known error. When I know more about it I will open an issue myself, this offers no information.
And next time upload logs to pastebin or similar, don't spam here.
