### ISSUE TITLE
Add an FPS limit option

### ISSUE THREAD

**Issue by Grzybojad** [Vita3K/Vita3K#367]
Currently Vita3K syncs the frame rate to the displays refresh rate, which is fine for 60Hz users, but becomes an issue for people who use higher refresh rate displays. For example a 60FPS game will run at 2x speed on a 120Hz display.

Please add an option to limit the frame rate to 60 FPS or even a specified FPS limit.

![screenshot](https://i.imgur.com/u0YvjUd.png)

**Comment by Zangetsu38** [comment]
this issue is now obsolete, if you re run on last build you get max 60 fps
![image](https://user-images.githubusercontent.com/5261759/60137021-0d98e500-97a6-11e9-9bb7-50e94c9a56a8.png)

**Comment by pent0** [comment]
Did you enable sync rendering?

**Comment by Zangetsu38** [comment]
No i speek on normal mode, sync rendering is only for debug

**Comment by Macdu** [comment]
Closing as this is no longer appropriate, Vita3K is now more accurate and the fps directly depends on the game. For example in Uncharted and Tales of Hearts, most of the game runs at 30 fps except some parts running at 60fps. It is not possible to increase the FPS except by patching the game.
