### ISSUE TITLE
Controller Port wrong VS actual console.

### ISSUE THREAD

**Issue by wfscans** [Vita3K/Vita3K#373]
On the Henkaku discord there was talk over port usage(I forget why, maybe it started with Vita3k). Anyway, cag made a simple homebrew to test the port and if the unit was a PSTV or not(I remember, I think it started with being able to tell if it was a Vita TV, not sure where the controller port thing came from). Anyway you can find that here - https://github.com/caghandemir/vitaPUTest

It was also mentioned that on actual consoles(PSTV, I'm not sure about Vita, but I assume it's the same) that for whatever reason, even though it only has 4 controller ports, there are 5 in code(0-4 instead of the sane 0-3). 0 and 1 are the same port while controller 2-4 map to their respected port. On Vita3K controller 1 is only shown on port 0 as of current MASTER https://github.com/Vita3K/Vita3K/commit/61b5f517300d0a804e404b4a4a762a6285b35d07

![image](https://user-images.githubusercontent.com/20528385/50873824-930f1100-138f-11e9-835c-6384f139bd76.png)

EDIT: Compiled vpk from source above(remove ".zip" from end as .vpk aren't supported) - 
[vitaPUTest.vpk.zip](https://github.com/Vita3K/Vita3K/files/2739349/vitaPUTest.vpk.zip) (based off https://github.com/caghandemir/vitaPUTest/commit/9d4af7de7ffb6a4c6fc73499d7dda79bd11d7f96)

**Comment by caghandemir** [comment]
Dang, I had forgotten about this. A normal Vita only says occupied on port 0 so I really have no idea what causes 1 to be occupied on a PSTV.

**Comment by Rinnegatamante** [comment]
Said "controller 1" is a controller plugged in in the PC or not? PSTV without a paired controller will actually give SCE_CTRL_TYPE_UNPAIRED on port 1 as Vita3K does.

**Comment by wfscans** [comment]
> Said "controller 1" is a controller plugged in in the PC or not? PSTV without a paired controller will actually give SCE_CTRL_TYPE_UNPAIRED on port 1 as Vita3K does.

So it does... so it really only does this on PSTV consoles...so I guess it's not to big of a deal... but I wonder what is holding up slot 0 when then controller is off.
