### ISSUE TITLE
Startup Crash

### ISSUE THREAD

**Issue by MrMeeseesks** [Vita3K/Vita3K#386]
![capture](https://user-images.githubusercontent.com/31322692/51441835-e6dcfc80-1ca3-11e9-882f-06a0d021c8b5.PNG)
Immediate crash on startup. Any fixes?

**Comment by IllusionMan1212** [comment]
It seems like your GPU doesn't support openGL 4.1 which is the minimum requirement for Vita3k to work right now. you can either upgrade your GPU or wait until (maybe) the minimum requirements are lowered.

**Comment by HolyMcDiver** [comment]
Just being cautious here but @MrMeeseesks , what are your system specs? Most importantly, your GPU.

**Comment by MrMeeseesks** [comment]
My Lenovo Ideapad y700 has an Nvidia GTX 960.

**Comment by HolyMcDiver** [comment]
OpenGL version : 4.4
🤔 
I blame the drivers, try reinstalling your drivers and see if the problem still persists.

**Comment by IllusionMan1212** [comment]
@MrMeeseesks your graphics card seems to support openGL up to 4.4. 
maybe your drivers are outdated??
also it'd be easier to help you with your issues if you could join our [discord server](https://discord.gg/6aGwQzh)

**Comment by 1whatleytay** [comment]
Yep. Do a driver update. Remember that OpenGL versions aren't the only thing that can cause the host to fail initialization. I want to see your log, its covered up by your window.

**Comment by MrMeeseesks** [comment]
Updating my graphics driver did the trick. Thanks for the tip!
