### ISSUE TITLE
Implement GDB Stub for remote guest debugging

### ISSUE THREAD

**Issue by VelocityRa** [Vita3K/Vita3K#393]
Being able to debug with IDA would be extremely useful, especially if the GDB stub also has breakpoint support.

**Comment by 1whatleytay** [comment]
Anything that needs to be added to close this issue? Might as well get any features we need out of the way before I move on.

**Comment by sunho** [comment]
GDB breakpoint is really fragile. Continuing almost always crashes the emu. I'll look into this.

**Comment by sunho** [comment]
Done

**Comment by sunho** [comment]
https://github.com/Vita3K/Vita3K/pull/1248
