### ISSUE TITLE
High Priority QOL Request - CFG or in app setting to specify the working memory card directory

### ISSUE THREAD

**Issue by Fallenleader** [Vita3K/Vita3K#395]
Not everyone has a massive HDD/SSD as their C drive. I personally have a 120GB SSD that holds Windows and some important applications, and as such don't have a lot of breathing room for much else. Every time I go to test a new build, I have to have V3k "install" the game I want to test, test, delete from appdata/recyclebin, and repeat for every game. I also have to do this every time a major release happens just to update logs. As such I have failed to proactively update the status of the games I am testing, instead defaulting to a month or more at a time since this process is very unproductive use of limited time.

V3K dumps everything to appdata with either no, or at least no apparent option to change this without a symlink, which for the average joe might not be readily evident.

Considering people have lost symlinked data in the past to a windows 10 update (not just a broken symlink, we are talking complete data GONE), I personally am uncomfortable poping in an OS level modification for something that should be resolved in the application.

It shouldn't be difficult to allow the user a means to redirect from appdata to another location, by either editing a cfg file, or through a sexy menu. I personally would like at minimal a cfg option on the next build please, as I brought this up in chat multiple times 6 months ago.

Having a hardcoded location for anything isn't an ideal move for any application, since user setups can vary dramatically from PC to PC.

**Comment by wfscans** [comment]
This my not be ideal... but I know people working on this my not like half doing a cfg... would you be find with a tack option? `--path` maybe? Then again... that as well maybe is a little half backed... but I feel they'd be better then a half backed cfg... maybe now is the time to work on the start of the cfg system? I can't really speak though :x

**Comment by pent0** [comment]
I will try to add a config system that allows edit of game storage folder

**Comment by pent0** [comment]
I guess this is ok now ?
