### ISSUE TITLE
QOL: Unimportant - Have option for Vita3K to make a copy of the log with the game's title ID for easier compatibility reporting/debugging

### ISSUE THREAD

**Issue by Fallenleader** [Vita3K/Vita3K#402]
Not important, but it would make tracking games easier if V3K either has an option to make a new log file or make a duplicate with the title ID of the game on launch rather than overwriting the existing one.
If someone get's a chance, this would be highly appreciated since I have a large number of games I test.

**Comment by pent0** [comment]
For any newcomers who want to take this issue, the file you need to look for is [config.cpp](
https://github.com/Vita3K/Vita3K/blob/master/src/emulator/host/src/config.cpp) and 
https://github.com/Vita3K/Vita3K/blob/429a388404f007e2e10ad0ac361a9084a510a2b4/src/emulator/util/src/util.cpp#L51-L52

LOG_FILE_NAME is name of file log, true/false toggle on ```basic_file_sink_mt``` means (delete old log, replace with new log)/(append to old log)

**Comment by pent0** [comment]
I will do this on 9 Feb if no one hasn't done this (that maybe a deadline :P)
