### ISSUE TITLE
Add touchscreen support for devices having one

### ISSUE THREAD

**Issue by Rinnegatamante** [Vita3K/Vita3K#407]
There are laptops actually having a touchscreen in which it would be cool to have real touch support for sceTouch in order to implement multitouch too. SDL has SDL_Touch for this manner.

**Comment by BogdanTheGeek** [comment]
https://github.com/Vita3K/Vita3K/pull/501
this is a PR that implements that

**Comment by BogdanTheGeek** [comment]
This can be closed.
