### ISSUE TITLE
Deploying macOs/Linux builds as releases

### ISSUE THREAD

**Issue by Rinnegatamante** [Vita3K/Vita3K#413]
According to GitHub rules, the way we're actually deploying nightlies for macOs and Linux is not compliant to how a repository is meant to be and we could be subject to warnings from GitHub itself.

Some related info:
https://help.github.com/en/articles/distributing-large-binaries
https://help.github.com/en/articles/what-is-my-disk-quota

**Comment by scribam** [comment]
Do you need to keep an history of all nightly builds or just the last one from master is enough?

**Comment by Rinnegatamante** [comment]
Holding an history would be better, similarly to this repo: https://github.com/vitasdk/autobuilds/releases
