### ISSUE TITLE
Fix sceFios psarc loading

### ISSUE THREAD

**Issue by VelocityRa** [Vita3K/Vita3K#423]
Old issue, `psarc`'s fail to load:
![image](https://user-images.githubusercontent.com/6632271/53901970-df519700-4048-11e9-83cd-4a318c2d7bf7.png)
Freezes after this.
`0xE7F5BE01` _may_ be related to SceUlobjMgr, needs more investigation.

**Comment by Zangetsu38** [comment]
see on Flower game
(!image)(https://media.discordapp.net/attachments/442344583293304833/557004643859693570/unknown.png?width=1430&height=221)

**Comment by Zangetsu38** [comment]
I add here also other game before game, with ilot NID not found, and with Vita3K don't try open game file
Game is : Shinobido 2: Revenge of Zen
![image](https://cdn.discordapp.com/attachments/408916678911459331/561005289222963223/unknown.png)
# Log : 
[vita3k.log](https://github.com/Vita3K/Vita3K/files/3020809/vita3k.log)

**Comment by frangarcj** [comment]
Fixed with #636
