### ISSUE TITLE
Port format code formatting script to Windows

### ISSUE THREAD

**Issue by VelocityRa** [Vita3K/Vita3K#44]
`format.sh` needs to be ported to Windows for developers on that platform.

**Comment by mailwl** [comment]
there is clang-format plugin for Visual Studio, maybe it helps?
https://marketplace.visualstudio.com/items?itemName=LLVMExtensions.ClangFormat

**Comment by VelocityRa** [comment]
Yea I guess we could just add that to the contrubor guide, I think @petmac is already making one.
