### ISSUE TITLE
Drawing from a thread different from the one that's created the context

### ISSUE THREAD

**Issue by xyzz** [Vita3K/Vita3K#455]
If the game's created a context (sceGxmCreateContext) from one thread, but draws or does any gl-related operation such as create shader, etc, on another, Vita3k crashes (on linux nvidia drivers, possible that it just doesn't draw anything on other drivers).

The reason is that vita3k calls SDL_GL_CreateContext in its implementation of sceGxmCreateContext which assigns the OpenGL context to the current thread, however when trying to draw from a different thread, there is no gl context.

Here's an example change to a homebrew which works on vita but crashes on vita3k https://github.com/xyzz/VitaTester/commit/e51f2ed5e33e086dad568ab00ece6341e760a85a

Also, this behavior is seen in a commercial game "BreakQuest: Extra Evolution".

I've tried working around it like so https://github.com/xyzz/Vita3K/commit/08b88634af134bb4346f7d74a34f956080a86caa but SDL_GL_MakeCurrent just returns a generic error "Unable to make GL context current".

**Comment by xyzz** [comment]
After adding a https://github.com/xyzz/Vita3K/commit/86eaf9c9cdb93302474acecb505a968930089cbe the modified vitatester works fine, though it's probably still not the best solution to this problem

**Comment by petmac** [comment]
Thanks @xyzz! Historically I assumed GXM contexts were only usable from a single thread, and if we found otherwise we would cross that bridge when we came to it.

I had planned to move all OpenGL calls to the main thread using a command queue system, to make debugging with apitrace easier, and I think that would fix this too.

Or we should just bite the bullet and move to Vulkan... 🤧

**Comment by Rinnegatamante** [comment]
@petmac Gxm allows multithreaded rendering even if i think there are not a lot of titles actually using that feature.

**Comment by pent0** [comment]
Hope this is solved with newest master. Please test again.
