### ISSUE TITLE
Rerun gen-modules

### ISSUE THREAD

**Issue by VelocityRa** [Vita3K/Vita3K#503]
[gen-modules](https://github.com/Vita3K/Vita3K/tree/master/src/gen-modules) has only been run once and a lot of symbols have been added to [vita-headers/db.yml](https://github.com/vitasdk/vita-headers/blob/master/db.yml) since then.

Its code does not handle merging already implemented functions, so I will likely not be straightforward to run again (will need lots of manual merging).

[Here's](https://github.com/Vita3K/Vita3K/wiki/Module-generation) the wiki entry documenting the process.

**Comment by IllusionMan1212** [comment]
#511 fixes this
