### ISSUE TITLE
Fix SceAvPlayer/libscemp4 LLE

### ISSUE THREAD

**Issue by VelocityRa** [Vita3K/Vita3K#508]
Used by _many_ commercial games.

Can use this hb for testing: http://vitadb.rinnegatamante.it/#/info/364

**Comment by VelocityRa** [comment]
#512 improves this.

**Comment by sunho** [comment]
SceAvPlayer uses libscemp4 under the hood.

**Comment by sunho** [comment]
It looks like the games that only call scemp4 functions are statically linked with sceavplayer and using those static sceavplayer functions.

I think we have two options
1. LLE both scemp4 and sceavplayer
2. HLE scemp4 and LLE sceavplayer

We can't only HLE sceavplayer. Although HLE avplayer would work in many games, some games are statically linked with sceavplayer, so we need to make sure it works in LLE mode.

I'm first trying to go with option 1.

**Comment by sunho** [comment]
LLE scemp4 was stuck at initialization. The init function spawns one worker thread and waits for worker thread to do the work. But, the worker thread somehow doesn't do any work. I'm investigating more.

**Comment by VelocityRa** [comment]
The statically linked thing was already known btw. Should have mentioned it here. I guess I figured it out afterwards and forgot to.
You can ask next time, I don't mind getting pinged.

**Comment by sunho** [comment]
More robust implementation of audioDecDecode is needed to move forward. Especially, AAC decoding part. Audio part of avplayer is just broken without this. And, apps that use audio part of avplayer in certain way are not working.

**Comment by bookmist** [comment]
Finally implemented by this https://github.com/Vita3K/Vita3K/pull/1686

**Comment by Zangetsu38** [comment]
Very old issue, 😅 should can close it
