### ISSUE TITLE
PKG support

### ISSUE THREAD

**Issue by niko1point0** [Vita3K/Vita3K#533]
I have some PKG packages for Vita, are they compatible with the Vita3k emulator?

**Comment by pent0** [comment]
Sorry, currently it's not possible yet. An attempt has been made before but after decryption, it requires another layer (PFS) to be decrypted. Vita3K currently only support VPK.

This should be open for tracking PKG support in the future.

**Comment by rayman3003** [comment]
Please add the PKG support. It is very important.

**Comment by Zangetsu38** [comment]
pkg support is comming soon, part for install it is already done, now need works on decrypt layer and launcher

**Comment by rayman3003** [comment]
> 
> 
> pkg support is comming soon, part for install it is already done, now need works on decrypt layer and launcher

Awesome & thank u. :D

**Comment by IllusionMan1212** [comment]
resolved by #683 , we should close this.
