### ISSUE TITLE
Add option to enabling/disable TTY channel and log it to a file

### ISSUE THREAD

**Issue by pent0** [Vita3K/Vita3K#548]
TTY logging code is in src/emulator/io/src/io.cpp. TTY channel

**Comment by sunho** [comment]
I think this is solved as of now

**Comment by Zangetsu38** [comment]
not really, i have just set it inside log_trace for moment, but needpslit in inside other output with oinly it

**Comment by sunho** [comment]
You might use console mode for that case. it will redirect every tty to stdout and stdin.
