### ISSUE TITLE
Build issues on Linux

### ISSUE THREAD

**Issue by severinkaderli** [Vita3K/Vita3K#566]
Hello, I'm trying to compile vita3k on ArchLinux. I follow the build instructions in README.md and the build looks like it's working at first but at 47% it just gets stuck after `Built target kernel` with no other error.

```
make[2]: Leaving directory '/home/severin/projects/PKGBUILDS/vita3k-git/src/vita3k/build-linux'
[ 47%] Built target kernel
```

**Comment by VelocityRa** [comment]
Can't really do much without more info. 
Anyone else with this issue maybe?

**Comment by scribam** [comment]
Hi there,
As a workaround, try to use `clang` instead of `gcc` to compile Vita3K. It should solve the issue.

**Comment by severinkaderli** [comment]
> Hi there,
> As a workaround, try to use `clang` instead of `gcc` to compile Vita3K. It should solve the issue.

Using `clang` has indeed worked. Thank you for your help!

**Comment by BogdanTheGeek** [comment]
I had the same issue but after leaving it alone it eventually got over it. I have done multiple clean builds and it seems to be either an Arch Linux issue or a gcc issue.

**Comment by 1whatleytay** [comment]
Appears to be solved.
