### ISSUE TITLE
Travis can't deploy builds

### ISSUE THREAD

**Issue by MadMrCrazy** [Vita3K/Vita3K#573]
#563 changed the way Travis deploys builds, unfortunately it fails due to an authentication error even if the build itself built successfully

[Example](https://travis-ci.org/Vita3K/Vita3K/jobs/572142388#L1262)
Not at all a high priority issue but thought I'd let you know.

**Comment by VelocityRa** [comment]
@scribam Do you know how to fix this?

**Comment by pent0** [comment]
We use secure key on master, and it didnt work. I asked @petmac to look since he is the only one who can generate secure token and Travis CI access i think

**Comment by VelocityRa** [comment]
@petmac Could you give admin perms for this repo to bent or me?

**Comment by pent0** [comment]
Fixed with 74c5063. Thanks for reporting!
