### ISSUE TITLE
Add unicorn submodule for Linux

### ISSUE THREAD

**Issue by Sunderland93** [Vita3K/Vita3K#58]
Hello. Please add unicorn submodule for Linux build

**Comment by Ghabry** [comment]
Simply install unicorn(-dev) through your package manager.

**Comment by Sunderland93** [comment]
@Ghabry unicorn is absent on Debian archive

**Comment by VelocityRa** [comment]
@Sunderland93 How is that Vita3K's problem?

**Comment by Sunderland93** [comment]
@VelocityRa Vita3K contains unicorn submodules for Mac and Windows. Why not add for Linux too?

**Comment by VelocityRa** [comment]
It contains compiled libraries actually, not submodules. It isn't compiled from source.

**Comment by Sunderland93** [comment]
@VelocityRa I know that. It's a big problem to add precompiled library for Linux?

**Comment by Ghabry** [comment]
the problem is that you have hundreds of versions of Linux and that it is almost impossible to provide a precompiled binary that works everywhere.

**Comment by petmac** [comment]
I think at some point, if we add official Linux support we can change macOS to use a Unicorn install from Homebrew or something rather than bundle a prebuilt version.

I absolutely hate having it prebuilt and only did it because the process to build it on Windows was too complex and I wanted parity between platforms.

**Comment by VelocityRa** [comment]
Not sure, we don't have any active devs on Linux afaik.

**Comment by dracc** [comment]
This seems to be fixed, or am I reading the file tree incorrectly?

**Comment by pent0** [comment]
Yes, you are reading the tree incorrectly. Submodule looks like this:
![image](https://user-images.githubusercontent.com/25717050/57685782-cfff5300-7662-11e9-8e00-df3041f487d6.png)

Unicorn is being shipped as binary in 3 platforms. It reduces compile times, but debug symbols is nowhere to be found (release binary)

**Comment by scribam** [comment]
Solved with https://github.com/Vita3K/Vita3K/pull/478?

**Comment by dracc** [comment]
You ought to be correct, @scribam
