### ISSUE TITLE
Assert on debug build

### ISSUE THREAD

**Issue by mailwl** [Vita3K/Vita3K#582]
assert in https://github.com/Vita3K/Vita3K/blob/master/vita3k/config/src/config.cpp#L293

unneeded space between long and short options "color-surface-debug, C"

**Comment by 1whatleytay** [comment]
That causes an assert!? I saw it when I was adding config options but I didn't think it would cause an issue. Thanks for the heads up!

**Comment by mailwl** [comment]
Ah, yes, assert itself here: https://github.com/Vita3K/ext-boost/blob/6b780f14b64013e601fb8ada0626855a39de07ee/libs/program_options/src/options_description.cpp#L177

**Comment by 1whatleytay** [comment]
Fixed in new PR.
