### ISSUE TITLE
Develop plan?

### ISSUE THREAD

**Issue by Omoinemie** [Vita3K/Vita3K#59]
hello, do you have a plan to develop a Android PSV emulator?

**Comment by Zangetsu38** [comment]
Just look psp emulator, is very slow on Galaxy S8 sot euu you can wait long time i think ^^

**Comment by shadowbrony33** [comment]
Not for a long time

**Comment by VelocityRa** [comment]
@petmac Need to mark this as invalid and close it. Sorry for all the pings, if I had appropriate perms I'd do it myself.

**Comment by petmac** [comment]
I think if you want to run 32-bit ARM code on an ARM device that supports 32-bit code (pretty sure Google haven't removed support yet) then emulation like this project is not the way to go.

What you probably want to do is something like WINE, where the code is run natively, and you implement all the libraries as if they were just Android libraries.

A good project for someone else I think.
