### ISSUE TITLE
10 Second Ninja (and probably others) regression

### ISSUE THREAD

**Issue by VelocityRa** [Vita3K/Vita3K#597]
Crash in `load_self.cpp`.

According to @IllusionMan1212 it's probably this commit that broke it: https://github.com/Vita3K/Vita3K/pull/586/commits/9d41a205803c080979f26f0747a3592c3622990f.

**Comment by 1whatleytay** [comment]
That's likely... Is it windows only?

**Comment by VelocityRa** [comment]
I've only tested on Windows.
