### ISSUE TITLE
Window : My Vita3K instantly close ;---; 

### ISSUE THREAD

**Issue by Rongcover** [Vita3K/Vita3K#602]
When i open Vita3k , My vita3k it white and then instantly close ;---; 
![50DandxtTw](https://user-images.githubusercontent.com/22428924/67621652-bda55a00-f83b-11e9-8c75-8371778980d2.jpg)

**Comment by Zangetsu38** [comment]
sorry, i my fault, is fixed on news pr https://github.com/Vita3K/Vita3K/pull/599 is because you don't have firmware instaled

**Comment by VelocityRa** [comment]
@Rongcover Download again, the issue is fixed now.
