### ISSUE TITLE
TLS: Implement __tls_get_addr

### ISSUE THREAD

**Issue by VelocityRa** [Vita3K/Vita3K#613]
Stardew Valley crashes here: ![](https://media.discordapp.net/attachments/408917432934072321/642641432921899024/unknown.png)

`__tls_get_addr` can probably implemented with https://github.com/Vita3K/Vita3K/blob/06299de24231ad089bec55a37df15826d32ce76b/vita3k/kernel/src/kernel.cpp

**Comment by frangarcj** [comment]
Fixed with #631
