### ISSUE TITLE
Quickstart Guide

### ISSUE THREAD

**Issue by VelocityRa** [Vita3K/Vita3K#615]
RPCS3 has this page: http://rpcs3.net/quickstart
And a relevant dialog the first time you boot it.

The most important/relevant thing for us would be a quickstart guide for downloading and decrypting/installing the firmware.

**Comment by TehPsychedelic** [comment]
Where would the quickstart guide be located, is the web project behind this ORG being used to power the current website, or...?

**Comment by VelocityRa** [comment]
Yes, our website's code is at https://github.com/Vita3K/Vita3K.github.io

**Comment by sunho** [comment]
@VelocityRa Don't we have this one?

**Comment by VelocityRa** [comment]
We do now yes.
