### ISSUE TITLE
Figure out ScePvf and similar preloaded (?) modules

### ISSUE THREAD

**Issue by VelocityRa** [Vita3K/Vita3K#616]
Games use `scePvf` functions, but it even doesn't exist in `SceSysmodule` as something that can be loaded at will.

_Maybe_ there's a list of such libraries that are supposed to be preloaded.
If so, we could have a hardcoded list of them, analyze the imports of the elf and load them up as necessary.

Example game:
Virus Named Tom
![](https://media.discordapp.net/attachments/541044762627538944/604987357615357953/unknown.png?width=760&height=383)
![](https://media.discordapp.net/attachments/541044762627538944/604986465461731338/unknown.png?width=727&height=101)

**Comment by sunho** [comment]
Should be fixed by https://github.com/Vita3K/Vita3K/pull/780
