### ISSUE TITLE
Integrate SPIR-V shader validation

### ISSUE THREAD

**Issue by VelocityRa** [Vita3K/Vita3K#620]
Currently recompiled shaders are usually not valid SPIR-V, they would not pass `spirv-val`.
They only work because SPIRV-Cross does not validate them and can accept very wrong shaders.

The solution for this is to programmatically invoke the validator from SPIRV-Tools every time we recompile a shader.

*Edit:* We can invoke glslang's wrapper, no need to import SPIRV-Tools https://github.com/KhronosGroup/glslang/blob/ea69a2982986cd668ed15287cdcb7e96a637d92b/SPIRV/SpvTools.h#L70

**Comment by GamingDucking** [comment]
SPIR-V didn't exactly went to plan in my opinion and it's currently "deprecated" as of the latest bulid.

**Comment by Macdu** [comment]
Actually, SPIR-V is the only backend used by the Vulkan renderer, but it is marked as deprecated for opengl. Moreover, this PR is about making valid Spir-V code. Vulkan Validation layers check for spirV validity. So as part of making the Vulkan renderer I also fixed all spirV validation issues.
