### ISSUE TITLE
What Game(s) Is Compatible With Vita3K ?

### ISSUE THREAD

**Issue by FunnyParadox** [Vita3K/Vita3K#63]
What Game(s) Is Compatible With Vita3K ?

**Comment by VelocityRa** [comment]
...Did you even visit the website?
Only some homebrews are supported, no commercial games yet: https://github.com/Vita3K/homebrew-compatibility/issues

**Comment by VelocityRa** [comment]
@petmac Need to mark this as invalid and close it.
