### ISSUE TITLE
Add a new button to open Vita3K partitions folder in File Explorer

### ISSUE THREAD

**Issue by Rinnegatamante** [Vita3K/Vita3K#644]
Most likely the best place would be as a new button for File submenu. It should open up %appdata%/Vita3K/Vita3K (or whatever Emulated System Storage Folder is set to) in file explorer (eg. explorer.exe for Windows). This would be handy when an user have to install sa0 fonts and/or game data files for homebrews.

**Comment by IllusionMan1212** [comment]
Should we close?

**Comment by 1whatleytay** [comment]
Yeah lets close it.
