### ISSUE TITLE
unity engine issue

### ISSUE THREAD

**Issue by Zangetsu38** [Vita3K/Vita3K#667]
- All Games using sprx mono-vita get same Unicorn error and crash.

# Log: 
[vita3k.log](https://github.com/Vita3K/Vita3K/files/4280378/vita3k.log)

**Comment by Margen67** [comment]
* `All Games using sprx mono-vita get same Unicorn error and crash.`

**Comment by Zangetsu38** [comment]
thx

**Comment by Zangetsu38** [comment]
implemented can load libkernel and driversd_us have improved it, and with hack can acces on ingame for 2 3 game

**Comment by pent0** [comment]
Move to #1404 for visibilty
