### ISSUE TITLE
Error at loading game: "miniz error: file not found extracting file: sce_sys/param.sfo"

### ISSUE THREAD

**Issue by rayman3003** [Vita3K/Vita3K#669]
When I try to loading a *.zip vita game, It won't load the game & just shows the following error:

[read_file_from_zip]: miniz error: file not found extracting file: sce_sys/param.sfo

Whats the solution?

**Comment by Zangetsu38** [comment]
already explain on discord, your game have probably folder title_id before data;
so is like PCSE01456/sce_sys/param.sfo and for can works need "sce_sys/param.sfo"

**Comment by rayman3003** [comment]
> 
> 
> already explain on discord, your game have probably folder title_id before data;
> so is like PCSE01456/sce_sys/param.sfo and for can works need "sce_sys/param.sfo"

Sorry But I don't get it. This is the folders inside the game zip:

![010101](https://user-images.githubusercontent.com/17022701/76614961-4ea07780-6536-11ea-92cb-154c1a4e28cd.jpg)

I renamed the parent directory from "PCSE01456" to "data" & then "app "and made zips out of them, But Vita3K always shows the same error for both newly created zips (data.zip & app.zip): "miniz error: file not found extracting file: sce_sys/param.sfo"

**Comment by Zangetsu38** [comment]
wut, your archive is ,pkg structure so not works is normal lol

**Comment by Ristellise** [comment]
I guess you tried selecting all the folders and then zipping them. you need to createa folder `PCSE01456`, copy all the sce and game_data files into the folder mentioned above, and then zip that folder.

If your zip has more than 1 folder as the root, it will not work.

**Comment by rayman3003** [comment]
> I guess you tried selecting all the folders and then zipping them. you need to create a folder named `PCSE01456`, copy all the sce and game_data files into the folder mentioned above, and then zip that folder.
> 
> If your zip has more than 1 folder as the root, it will not work.

Tried ur solution But didn't work.

**Comment by rayman3003** [comment]
> wut, your archive is ,pkg structure so not works is normal lol

Yes, u r right. Basically its a pkg. I hope that Vita3K soon support pkg games. Bcuz most of the games r in pkg format.

**Comment by pent0** [comment]
No, your zip must directly contains all these folder (eboot.bin, etc..) right away

**Comment by pent0** [comment]
If you have any more problem go on Discord, people work fine with this emulator and Github is not a support forum

**Comment by rayman3003** [comment]
> 
> 
> No, your zip must directly contains all these folder (eboot.bin, etc..) right away

It has. These folders must have a parent directory, or u can't make a zip out of it! I even used (no compression) in making the zip. But no success.

These files was produced out of a pkg file. And as Zangetsu38 said, Vita3K doesn't support pkg format yet. So I need to wait for pkg support in Vita3K.

**Comment by pent0** [comment]
> These folders must have a parent directory, or u can't make a zip out of it! 

Select all folders you want to compress and zip it. For example

![image](https://user-images.githubusercontent.com/25717050/76672714-582aed80-65d1-11ea-9ffd-8946b2b6eec7.png)

No one has issue with vpk before, so you are doing it wrong. Please search for a tutorial next time to dump correctly.

**Comment by Zangetsu38** [comment]
@pent0 normaly yes, but for it no can works, is just nonpdrm version archived on zip, need decrypt layer for install can works

**Comment by rayman3003** [comment]
> No one has issue with vpk before

Its not vpk. Its pkg (encrypted pkg!)

**Comment by Zangetsu38** [comment]
@rayman3003 if you have discord i can explain you how instal it

**Comment by rayman3003** [comment]
> 
> 
> @rayman3003 if you have discord i can explain you how instal it

Unfortunately I don't have discord.
Is it possible for u to send it to my email?

**Comment by Zangetsu38** [comment]
go on discord, and join vita3k server

**Comment by rayman3003** [comment]
> join vita3k server

It needs an invite. I'm new to discord. How can I get an invite for vita3k?

**Comment by Ristellise** [comment]
> > join vita3k server
> 
> It needs an invite. I'm new to discord. How can I get an invite for vita3k?

![image](https://user-images.githubusercontent.com/7894419/77129827-5c9f4c80-6a90-11ea-85bc-98f060d9e890.png)

**Comment by rayman3003** [comment]
> 
> 
> > > join vita3k server
> > 
> > 
> > It needs an invite. I'm new to discord. How can I get an invite for vita3k?
> 
> ![image](https://user-images.githubusercontent.com/7894419/77129827-5c9f4c80-6a90-11ea-85bc-98f060d9e890.png)

OK, Thank u.

**Comment by 1whatleytay** [comment]
Assuming this has been resolved.

**Comment by rayman3003** [comment]
> Assuming this has been resolved.

No, no. Not yet.

**Comment by ichisadashioko** [comment]
@rayman3003 You can extract all the files and copy them to the installation directory. Currently, I think Vita3k does quite a lot of checking even though it can at least show title screen but still rejects the installation.

- On Windows: `%AppData%\Roaming\Vita3KVita3k\ux0\app\<Title_ID>`
- On Linux: `~/.local/share/Vita3K/Vita3K/ux0/app/<Title_ID>`

**Comment by rayman3003** [comment]
I copied the game the to the path u said & the game's name appeared inside the Vita3K, But when I try to launch the game, It shows the following error:

"[20:34:54.055] |C| [load_self]: SELF app0:sce_module/libc.suprx is corrupt or encrypted. Decryption is not yet supported."

**Comment by rayman3003** [comment]
> You can extract all the files and copy them to the installation directory. Currently, I think Vita3k does quite a lot of checking even though it can at least show title screen but still rejects the installation.
> 
>     * On Windows: `%AppData%\Roaming\Vita3K\Vita3K\ux0\app\<Title_ID>`
> 
>     * On Linux: `~/.local/share/Vita3K/Vita3K/ux0/app/<Title_ID>`

I copied the game the to the path u said & the game's name appeared inside the Vita3K, But when I try to launch the game, It shows the following error:

"[20:34:54.055] |C| [load_self]: SELF app0:sce_module/libc.suprx is corrupt or encrypted. Decryption is not yet supported."

**Comment by ichisadashioko** [comment]
@rayman3003 Well, I think that's all we can do for now.

**Comment by KorewaWatchful** [comment]
Hey, as said before, what he has is an encrypted game dump, those are not supported on vita3k, so there's nothing to do for now, except get a decrypted dump that works with vita3k

**Comment by rayman3003** [comment]
> encrypted game dump, those are not supported on vita3k

1- Will the vita3k support encrypted games in the future?

2- Is there any tool available for windows to decrypt these encrypted games?
