### ISSUE TITLE
Switch to Dynarmic ARM Recompiler

### ISSUE THREAD

**Issue by 0x8080** [Vita3K/Vita3K#68]
https://github.com/MerryMage/dynarmic

This would be recommended to do when possible.

Unicorn is notoriously slow compared to JIT or any other decent recompiler so switching to dynarmic would  result in far better performance the will be greatly needed later on.

(Side Note: YUZU is moving away from unicorn due to performance issues too)

**Comment by VelocityRa** [comment]
We've been talking about this for a few days now (contacted MerryMage as well), so it's definitely planned.

**Comment by shadowbrony33** [comment]
Good to know, also it technically isn't a typo but I should change it to "Switch to a Dynamic ARM Recompiler"

**Comment by VelocityRa** [comment]
Not sure what you mean, unicorn is a"dynamic" (JIT) recompiler too, just slower.

Anyway to add to my previous message, dynarmic isn't compatible with the arch of Vita's CPU yet, else I (or maybe someone else) would have started porting it already. It's in the works though.

**Comment by shadowbrony33** [comment]
Does it just not have all of the opcodes or just doesn't have anything for ARMv7A?

**Comment by VelocityRa** [comment]
There's several differences between ARMv6K and ARMv7A which will need to be implemented, but perhaps the main difference is Thumb-2, which includes a lot of new instructions.

Their semantics for the most part are identical to equivalent ARM instructions (with different encoding) though, so hooking the preexisting ARM emitters for those is what's needed. The decoder for them was already done in the [latest commit](https://github.com/MerryMage/dynarmic/commit/e585e1d49ed65c31edd567510e00508d42decb1c) as you can see.

**Comment by sunho** [comment]
🔥 🦄

**Comment by sunho** [comment]
https://github.com/Vita3K/Vita3K/pull/845

**Comment by sunho** [comment]
We now support dynarmic!
