### ISSUE TITLE
Linux build issues - boost issues

### ISSUE THREAD

**Issue by KorewaWatchful** [Vita3K/Vita3K#682]
Linux builds are being super finicky for most people, boost doesn’t build without installing through apt-get (or similar package managers), and the user has to get dependencies that are not mentioned in the readme file. I think this process should be more automatic and working properly.

**Comment by KorewaWatchful** [comment]
the custom boost folder is missing some files for Linux

**Comment by ichisadashioko** [comment]
This might be fixed in PR #686
