### ISSUE TITLE
Hoping

### ISSUE THREAD

**Issue by Danergil5** [Vita3K/Vita3K#684]
Wish this could also be on Android

**Comment by Ristellise** [comment]
No.

This has been brought up many times on the discord as well. Please do not create an issue about it. =_=

**Comment by mobrine-mob** [comment]
OpenGL...

**Comment by Ristellise** [comment]
Yes, I know its OpenGL. So what?

Be my guest trying to port it to a mostly java based android. Vita3K is developed in C++. You could argue that "There is also C in Android" but to be frank, its different. You also have to deal with android libraries which differ.

Performance-wise, its a horrendous idea at this stage. Vita3K doesn't run well with lower-end processors.
