### ISSUE TITLE
Non-standard code prevents compilation under Linux

### ISSUE THREAD

**Issue by MrTimscampi** [Vita3K/Vita3K#7]
I'm slowly fixing the various errors needed to build on Linux.

Most of them are pretty simple (Forgotten imports that the other compilers let slide, mostly) but I'm stuck on this one.

Here's the message:
```
In file included from /home/mrtimscampi/Vita3K/src/emulator/module/include/module/module.h:21:0,
                 from /home/mrtimscampi/Vita3K/src/emulator/module/src/module.cpp:18:
/home/mrtimscampi/Vita3K/src/emulator/module/include/module/bridge_args.h:102:83: error: declaration of ‘using StackLayout = struct StackLayout<const typename StackArg<StackHead>::Type, StackType<StackTail>...>’ [-fpermissive]
     using StackLayout = StackLayout<StackType<StackHead>, StackType<StackTail>...>;
                                                                                   ^
/home/mrtimscampi/Vita3K/src/emulator/module/include/module/bridge_args.h:25:8: error: changes meaning of ‘StackLayout’ from ‘struct StackLayout<const typename StackArg<StackHead>::Type, StackType<StackTail>...>’ [-fpermissive]
 struct StackLayout {
        ^~~~~~~~~~~
make[2]: *** [emulator/module/CMakeFiles/module.dir/build.make:87: emulator/module/CMakeFiles/module.dir/src/module.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:1592: emulator/module/CMakeFiles/module.dir/all] Error 2
make: *** [Makefile:141: all] Error 2
```

Any help in fixing this would be appreciated, as this is beyond my (limited) knowledge of C++.

From looking at some docs, I noticed we could add the -lpermissive flag to the compiler. However, the documentations discourages its use:
`Downgrade some diagnostics about nonconformant code from errors to warnings. Thus, using -fpermissive will allow some nonconforming code to compile.`

I'll add it momentarily to continue fixing, but it would probably be wise to fix this in the future and remove the flag.

**Comment by petmac** [comment]
#6 may fix this.

**Comment by MrTimscampi** [comment]
Oh, you beat me to it, nice :)

Just adding a number seems quite hack-y though, but I guess this can be closed for now.
