### ISSUE TITLE
[Feature Request] Ability to set a game directory

### ISSUE THREAD

**Issue by klepp0906** [Vita3K/Vita3K#793]
Hoping to see the ability to set a game directory from within Vita3k so you can name your files to the redump or no-intro standard and store them where you wish, yet still have them parsed/populate properly within the emulator.   Similar to how its handled by RPCS3/Cemu/yuzu etc.  

At current youre stuck keeping your titles named after the titleID and while you can move the vfs directory, youre stuck keeping your titles within the ux0/app folder.

With RPCS3 for example, you can choose your own directory for the vfs (just like vita3k) and if left at that, you'd also be stuck placing your titles in the dev_hdd0/disc directory.

Fortunately they also included the ability to choose a game directory which evidently just reads the param.sfo to add the proper titleID.

Cemu is the same business.  they allow you to choose a directory for your mlc01 (the wiiu Fs) and you could simply place your titles in the same location as they'd be on legitimate wii u hardware.  This again comes w/ the caveat that it be named as the titleID.  Fortunately they also provide the ability to specify a games directory. 

with the current limitations vita3k is operating under, you cannot name your files to any standard/use datfiles unless you intend to keep a double of your files, or symlink them into the app folder and rename them back to the titleID there as anything in the app folder takes its titleID from the name of the folder and not the param.sfo etc.

discussed a bit more in depth/at length in the vita3k discord beginning with this comment. https://discordapp.com/channels/408916678911459329/408916678911459331/727552528404971522

**Comment by stzokev** [comment]
New to Vita emulation and a little surprised that this feature isn't available in the emulator. All other emulators already support this, so please prioritize this feature accordingly. Using symlink as workaround simply ain't a good one, not to mention it would not work at all if you keep your emulation on external HDD and it can be assigned random letters on different machines it connects to. So to add to the above request - please add the ability to specify relative path for the games, not only absolute.

**Comment by Zangetsu38** [comment]
i no understund what you want 🤔 app0 is obligatory inside ux0 no possible can move it 🤔

**Comment by stzokev** [comment]
@Zangetsu38 Implementing virtual file system like rpcs3 for example i.e. they keep the structure required, but that VFS can be set anywhere e.g. on a different drive letter or completely different drive. This way you can have your rom collection separately from the emulators. Remember not everyone uses your emulator to directly play games, many of us use front-ends to do that and that separation is required for ease of maintenance and backup.

**Comment by stzokev** [comment]
@Zangetsu38 Maybe I cannot explain indeed, so I'll just hope the original author description of the request is clear for the developer who is going to work on this.

**Comment by SergioMartinezIngelmo** [comment]
It would be a great improvement, I have all my games on a NAS (read only for security purposes) and It's impossible to launch the games copying entire "Vita3k" folder to the NAS because there are a lot of files that need to be written during a game installation.
It would be wonderful to have the ability to separate "/ux0/app/" folder from ux0 and launch the games externally as most emulators allow.

Thank you very much for all your work and for sharing it with us!
