### ISSUE TITLE
Linux build instructions

### ISSUE THREAD

**Issue by parkerlreed** [Vita3K/Vita3K#8]
### Prerequisites
[CMake](https://cmake.org/) is used to generate Visual Studio and Xcode project files. It is assumed that you have CMake installed and on your path. Other dependencies are provided as Git submodules or as prebuilt binaries.

[unicorn](http://www.unicorn-engine.org/) 

### Linux
1. `git submodule init && git submodule update`
2. `mkdir build-linux && cd build-linux`
3. `cmake ../src/`
4. `make`

**Comment by petmac** [comment]
Worth noting that SDL 2.0.7 is needed for SDL_AudioStream, used to convert audio during playback.
