### ISSUE TITLE
Madoka Battle Pentagram - A bunch of weird errors (not booting)

### ISSUE THREAD

**Issue by kanghyewonii** [Vita3K/Vita3K#849]
Hopefully this helps in development? Kinda wished this game worked. Attached is the log file...
[vita3k.log](https://github.com/Vita3K/Vita3K/files/5074211/vita3k.log)

**Comment by Zangetsu38** [comment]
this game boot but black screen

**Comment by scribam** [comment]
@kanghyewonii Can you create an issue on https://github.com/Vita3K/compatibility with your log file?

**Comment by Zangetsu38** [comment]
fixed and now it menu and can acces randomly on 3d ingame, unicorn error
