### ISSUE TITLE
I Can't Build The Emulator

### ISSUE THREAD

**Issue by FunnyParadox** [Vita3K/Vita3K#89]
Help Me Please

**Comment by VelocityRa** [comment]
Upload `Vita3k/build-windows/CMakeFiles/CMakeError.log` to pastebin or a similar site and post it here.

**Comment by FunnyParadox** [comment]
i download cmake that work but after that what i do ?

**Comment by VelocityRa** [comment]
I literally just told you what to do.

**Comment by FunnyParadox** [comment]
I Dont Have CMakeError.log

**Comment by VelocityRa** [comment]
Run cmake-gui (just type it in Start and press enter), add vita3k's path on the top where it says "Where is the source code" and the build-windows path below that.
Press configure and then generate, (use version 15 x64),
Post the text output you get below, here.

**Comment by FunnyParadox** [comment]
i try that don't work

**Comment by FunnyParadox** [comment]
But After Lanch Vita3K.exe I Got The Message
C:/User/*/Downloads/Emulator/Vita3K-Master/Vita3K <path to VPK file>

**Comment by FunnyParadox** [comment]
In The Output File The Text Was
The system is: Windows - 10.0.16299 - AMD64

**Comment by VelocityRa** [comment]
Please stop spamming messages.

I'm talking about the text in the lower half of the cmake-gui window.

Do you know that there are builds available for users? Unless you're a developer you don't need to do all this.

**Comment by FunnyParadox** [comment]
I'm a User And I Gonna Write It On 1 Message Not 3 Don't Worry

**Comment by VelocityRa** [comment]
Then you can always get the latest Windows build from here: https://ci.appveyor.com/project/Vita3K/vita3k/branch/master/artifacts
