### ISSUE TITLE
Can't install the game

### ISSUE THREAD

**Issue by Rusiann** [Vita3K/Vita3K#891]
I can't install saenai heroine ps vita game. Here's the log file
[vita3k.log](https://github.com/Vita3K/Vita3K/files/5133803/vita3k.log)

**Comment by Zangetsu38** [comment]
is normal, vitamin dump is not supported

**Comment by Rusiann** [comment]
But I saw that you succeeded in running saenai heroine on textractor github. Also can you explain me what a vitamin dump is?

**Comment by sunho** [comment]
https://vita3k.org/quickstart.html

**Comment by IllusionMan1212** [comment]
closing this since it's resolved, if we want an issue to track vitamin support in the future, we can open a new one
