### ISSUE TITLE
Vita3K i get virus detected messages from the website download

### ISSUE THREAD

**Issue by MythRriter** [Vita3K/Vita3K#892]
when i try to get Vita3K i get virus detected messages and the download from the Vita3K web site stops then fails

**Comment by MythRriter** [comment]
im also on a pc

**Comment by demmythecard2** [comment]
https://www.reddit.com/user/demmythecard

**Comment by sunho** [comment]
We filed a report to microsoft. Hopefully, they'll resolve this issue...

**Comment by Zangetsu38** [comment]
i have same issue with norton 360, is just false positivbe, ignore it

**Comment by scribam** [comment]
@MythRriter Any update on this?

**Comment by scribam** [comment]
Closing this, feel free to open a new issue if this still happens.
