### ISSUE TITLE
Unhandled relocation code 102

### ISSUE THREAD

**Issue by frangarcj** [Vita3K/Vita3K#92]
[11:56:37.578] [warning] [ relocate ]:    Unhandled relocation code 102.

**Comment by petmac** [comment]
I think this may actually be a bug in vitasdk, as homebrews that have this relocation code don't seem to crash... for this reason anyway.

**Comment by VelocityRa** [comment]
@frangarcj Could you document the game(s) for which this happens?

**Comment by frangarcj** [comment]
pfba for example

**Comment by frangarcj** [comment]
This is a relative jump so it can be ignored
