### ISSUE TITLE
PCSG00786 ご注文はうさぎですか？？Wonderful party！unicorn error at boot

### ISSUE THREAD

**Issue by zkyhzxf** [Vita3K/Vita3K#947]
PCSG00786 unicorn error at boot
Tried playing this game and it came with errors..
I included the log info file. Not sure what any of it means. I just want this game to work.
[vita3k.log](https://github.com/Vita3K/Vita3K/files/5165936/vita3k.log)

**Comment by sunho** [comment]
This looks promising. I'll try debugging.

**Comment by Zangetsu38** [comment]
Atrac missing 🤔 function missing on module can causing that, need instal fw and try automatic mode

**Comment by zkyhzxf** [comment]
> Atrac missing 🤔 function missing on module can causing that, need instal fw and try automatic mode
Thanks! OP can be fully played normally. But it get black screen at menu and can't go any forward.
[vita3k.log](https://github.com/Vita3K/Vita3K/files/5168242/vita3k.log)

**Comment by Zangetsu38** [comment]
![image](https://user-images.githubusercontent.com/5261759/92309726-46d30480-efa8-11ea-8273-cdd2837f6296.png)

**Comment by Frain-Breeze** [comment]
#1023 fixes the black menu screens. getting in-game works for me when I enable import call logging. Same applies to all MAGES visual novels, seemingly. Performance with logging on is pretty bad, but it’s playable!

**Comment by zkyhzxf** [comment]
> #1023 fixes the black menu screens. getting in-game works for me when I enable import call logging. Same applies to all MAGES visual novels, seemingly. Performance with logging on is pretty bad, but it’s playable!

Thanks! But the emulator haven't been merged your codes into master yet. How can I get your changes work in the emulator? I know nothing about code. Can you provide your emulator? I will have a try.❤

**Comment by Frain-Breeze** [comment]
I assume It’ll get merged within a few days, if not I’ll link a build.

**Comment by zkyhzxf** [comment]
> I assume It’ll get merged within a few days, if not I’ll link a build.

I tired your build, but when I tried to start new game, the emulator crashed.
[11:22:39.204] |W| [renderer::gl::texture::translate_wrap_mode]: Unsupported texture wrap mode translated: 0x1

**Comment by zkyhzxf** [comment]
> I assume It’ll get merged within a few days, if not I’ll link a build.

how to enable the import call logging?

**Comment by sunho** [comment]
This should be fixed if one enables the automatic LLE mode and do as Frain said.
