### ISSUE TITLE
Memory leak in renderer

### ISSUE THREAD

**Issue by sunho** [Vita3K/Vita3K#964]
The currently reported increasing ram is surprisingly casued by one or two leaks. 

This can be fixed by using delete[] in https://github.com/Vita3K/Vita3K/blob/master/vita3k/renderer/src/state_set.cpp#L109 and adding delete[] stream_data; in https://github.com/Vita3K/Vita3K/blob/master/vita3k/renderer/src/state_set.cpp#L374.

But, these changes somehow causes crash in release build. (check out p4g)

**Comment by ichisadashioko** [comment]
I will try to look into this bug.
