### ISSUE TITLE
Crash on start [linux]

### ISSUE THREAD

**Issue by Shoegzer** [Vita3K/Vita3K#967]
Vita3k commit e8656f89b7fca299647d9ef4e8755dab67554db9 crashes on start with a segmentation fault.  Latest working build  is 3b714115103d036f978b3194bc25934087bc22ad though I have not had a chance to bisect the specific commit that caused this.

Test system is linux mint 20, kernel 5.4 and gcc 9.3.0.

Log:
```
[15:30:21.802] |I| [init_config]: backend-renderer: OpenGL
[15:30:21.802] |I| [init_config]: log-level: 0
[15:30:21.919] |I| [main]: Vita3K v0.1 1694-e8656f89
[15:30:22.035] |I| [create]: Swap interval = -1
[15:30:22.038] |I| [create]: GPU = GeForce GTX 1070/PCIe/SSE2
[15:30:22.038] |I| [create]: GL_VERSION = 4.5.0 NVIDIA 440.100
[15:30:22.038] |I| [create]: GL_SHADING_LANGUAGE_VERSION = 4.50 NVIDIA
[15:30:22.038] |I| [create]: Your GPU supports shader interlock, some games that use programmable blending will have better performance.
[15:30:22.039] |W| [init_font]: Could not find font file at "/home/shoegzer/Emulation/Emulators/Vita3K/data/fonts/mplus-1mn-bold.ttf", falling back to default imgui font.
[15:30:22.039] |W| [init_live_area_font]: Could not find firmware font file at "/home/shoegzer/.local/share/Vita3K/Vita3K/sa0/data/font/pvf/jpn0.pvf", using defaut vita3k font.
Segmentation fault (core dumped)
```

**Comment by Zangetsu38** [comment]
check more recent compare https://github.com/Vita3K/Vita3K/commit/e8656f89b7fca299647d9ef4e8755dab67554db9, it is very old, and no idea what you get probleme

**Comment by Shoegzer** [comment]
Thanks @Zangetsu38, but my older (working) build complains about the missing font file too, and that one doesn't segfault.  What files should I extract specifically?

**Comment by Zangetsu38** [comment]
just extract all, data folder is request

**Comment by Shoegzer** [comment]
Not sure what you mean,  I copy the Vita3k binary from the source directory where I compile, to another direcotry where I keep my bins and run from there.  Are you saying I should also move something else?

**Comment by Zangetsu38** [comment]
no copy only binnary, you need also copy data and shaders-builtin folder

**Comment by Shoegzer** [comment]
Ah yes, I see now - and it's working without segfault.  Thanks!   

I still get the message `Could not find firmware font file at "/home/shoegzer/.local/share/Vita3K/Vita3K/sa0/data/font/pvf/jpn0.pvf", using defaut vita3k font.` I guess that's expected since I'm using unofficial fonts?

**Comment by Zangetsu38** [comment]
yes, you using ,default font set inside project
install it for can using official font, better and needed obligatory for some game
[font](http://dus01.psp2.update.playstation.net/update/psp2/image/2019_0924/sd_8b5f60b56c3da8365b973dba570c53a5/PSP2UPDAT.PUP?dest=us)

file-> install firmware

**Comment by Shoegzer** [comment]
Thanks again.  What website did that come from?  I know Sony posts their official firmware [here](https://www.playstation.com/en-us/support/system-updates/ps-vita/) but the file you just linked is not the 3.73 firmware.  Is that a separate font package posted elsewhere?

**Comment by Zangetsu38** [comment]
yes, psvita using 3 package for firmware, main firmware, and other, other is not obligatory updated, so sony have split it, for get update fw more fast ^^

**Comment by Shoegzer** [comment]
Thanks.  Just to be sure I understand, what you're saying is that Sony split the firmware into two files - main firmware, and fonts.  This lets them update the main firmware more frequently without forcing people to keep downloading the same font files over and over.  Is that right?

If so, do you know the website where sony posts any updates to fonts?  Not the direct file, but the website?

**Comment by Zangetsu38** [comment]
sorry but website no existe for it, only this official link

**Comment by Shoegzer** [comment]
No problem.  I appreciate your help, everything's working now with no errors in console.  Closing this issue.

**Comment by Zangetsu38** [comment]
you can try install fw with this binnary file ?
https://github.com/Vita3K/Vita3K/suites/1162765475/artifacts/16870924
like font file
and said me if that good works please, i no have linux for test
