### ISSUE TITLE
Permission to use code from SceJpegUser.cpp ìn VitaSDK

### ISSUE THREAD

**Issue by bythos14** [Vita3K/Vita3K#978]
Hello. I wish to use the function prototypes and data structures defined in [SceJpegUser.cpp](https://github.com/Vita3K/Vita3K/blob/master/vita3k/modules/SceJpeg/SceJpegUser.cpp)  to write a header for the [vita-headers](https://github.com/vitasdk/vita-headers) repository. 

To do this I will need explicit permission to re-license the code used under the MIT license. I hope that is okay with you.

Credits will be given, but I must ask, should credit be given per contributor to the file or would simply giving credit to the Vita3K Team be sufficient?

I look forward to hearing from you.

**Comment by Zangetsu38** [comment]
@1whatleytay

**Comment by 1whatleytay** [comment]
Yep you can use it.
