### ISSUE TITLE
Utility: Use Vita3K to "test" custom bubbles/livearea screens

### ISSUE THREAD

**Issue by IngwiePhoenix** [Vita3K/Vita3K#981]
Hello there!

I want to make custom bubbles and liveareas for my RetroArch games - but, testing them is a little hard. I'd have to create a "dumb" bubble (an app that just launches, returns 0, and thus exists) and then edit my template there, refreshing the livearea every single time. It'd be much more convenient to use Vita3K for that and make all preparations on my desktop before packaging it up and moving it to my Vita.

Since viewing bubbles and liveareas is mostly implemented (bubbles aren't actually bubbles, but thats okay), would it be possible to  add a utility that'd allow the usage of Vita3K to preview a bubble's `template.xml` while changing it?

Thanks and kind regards,
Ingwie

**Comment by sunho** [comment]
If I understand correctly, you need some kind of "refresh app list" menu, right? I think we can implement it easily.

You can actually just edit template.xml on C:\Users\(name)\AppData\Roaming\Vita3K\Vita3K\ux0\app\(your app id) and restart vita3k in the mean time. I believe this should work.

**Comment by Zangetsu38** [comment]
Refresh buttons clean also live area content
