### ISSUE TITLE
Xcode 12 compilation error

### ISSUE THREAD

**Issue by SwiftBMan** [Vita3K/Vita3K#985]
ld: in /Users/zhengqihui/Desktop/Github/Vita3K/external/ffmpeg/macos/x86_64/libswscale.a(input.o), building for macOS, but linking in object file built for free standing,
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by 1whatleytay** [comment]
Are you on Big Sur Preview? 🤔

**Comment by SwiftBMan** [comment]
> Are you on Big Sur Preview? 🤔

Xcode 12
on macOS Catalina

**Comment by scribam** [comment]
@SwiftBMan Can you try to add `-DCMAKE_OSX_ARCHITECTURES=x86_64` to your cmake command line? You might also need cmake >= 3.18.1

**Comment by scribam** [comment]
Details on this issue can be found here: https://github.com/yasm/yasm/issues/141

**Comment by scribam** [comment]
Fixed with #1079
